//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.28 at 03:32:08 PM IST 
//


package com.opl.mudra.api.cibil.model.highmark.individual.request.acknow;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HEADERSEGMENT }
     * 
     */
    public HEADERSEGMENT createHEADERSEGMENT() {
        return new HEADERSEGMENT();
    }

    /**
     * Create an instance of {@link APPLICANTSEGMENT }
     * 
     */
    public APPLICANTSEGMENT createAPPLICANTSEGMENT() {
        return new APPLICANTSEGMENT();
    }

    /**
     * Create an instance of {@link ADDRESSSEGMENT }
     * 
     */
    public ADDRESSSEGMENT createADDRESSSEGMENT() {
        return new ADDRESSSEGMENT();
    }

    /**
     * Create an instance of {@link APPLICANTSEGMENT.PHONES }
     * 
     */
    public APPLICANTSEGMENT.PHONES createAPPLICANTSEGMENTPHONES() {
        return new APPLICANTSEGMENT.PHONES();
    }

    /**
     * Create an instance of {@link APPLICANTSEGMENT.RELATIONS }
     * 
     */
    public APPLICANTSEGMENT.RELATIONS createAPPLICANTSEGMENTRELATIONS() {
        return new APPLICANTSEGMENT.RELATIONS();
    }

    /**
     * Create an instance of {@link APPLICANTSEGMENT.IDS }
     * 
     */
    public APPLICANTSEGMENT.IDS createAPPLICANTSEGMENTIDS() {
        return new APPLICANTSEGMENT.IDS();
    }

    /**
     * Create an instance of {@link REQUESTREQUESTFILE }
     * 
     */
    public REQUESTREQUESTFILE createREQUESTREQUESTFILE() {
        return new REQUESTREQUESTFILE();
    }

    /**
     * Create an instance of {@link HEADERSEGMENT.MFI }
     * 
     */
    public HEADERSEGMENT.MFI createHEADERSEGMENTMFI() {
        return new HEADERSEGMENT.MFI();
    }

    /**
     * Create an instance of {@link HEADERSEGMENT.CONSUMER }
     * 
     */
    public HEADERSEGMENT.CONSUMER createHEADERSEGMENTCONSUMER() {
        return new HEADERSEGMENT.CONSUMER();
    }

    /**
     * Create an instance of {@link INQUIRY }
     * 
     */
    public INQUIRY createINQUIRY() {
        return new INQUIRY();
    }

    /**
     * Create an instance of {@link APPLICANTSEGMENT.APPLICANTNAME }
     * 
     */
    public APPLICANTSEGMENT.APPLICANTNAME createAPPLICANTSEGMENTAPPLICANTNAME() {
        return new APPLICANTSEGMENT.APPLICANTNAME();
    }

    /**
     * Create an instance of {@link APPLICANTSEGMENT.DOB }
     * 
     */
    public APPLICANTSEGMENT.DOB createAPPLICANTSEGMENTDOB() {
        return new APPLICANTSEGMENT.DOB();
    }

    /**
     * Create an instance of {@link APPLICANTSEGMENT.KEYPERSON }
     * 
     */
    public APPLICANTSEGMENT.KEYPERSON createAPPLICANTSEGMENTKEYPERSON() {
        return new APPLICANTSEGMENT.KEYPERSON();
    }

    /**
     * Create an instance of {@link APPLICANTSEGMENT.NOMINEE }
     * 
     */
    public APPLICANTSEGMENT.NOMINEE createAPPLICANTSEGMENTNOMINEE() {
        return new APPLICANTSEGMENT.NOMINEE();
    }

    /**
     * Create an instance of {@link ADDRESSSEGMENT.ADDRESS }
     * 
     */
    public ADDRESSSEGMENT.ADDRESS createADDRESSSEGMENTADDRESS() {
        return new ADDRESSSEGMENT.ADDRESS();
    }

    /**
     * Create an instance of {@link APPLICATIONSEGMENT }
     * 
     */
    public APPLICATIONSEGMENT createAPPLICATIONSEGMENT() {
        return new APPLICATIONSEGMENT();
    }

    /**
     * Create an instance of {@link APPLICANTSEGMENT.PHONES.PHONE }
     * 
     */
    public APPLICANTSEGMENT.PHONES.PHONE createAPPLICANTSEGMENTPHONESPHONE() {
        return new APPLICANTSEGMENT.PHONES.PHONE();
    }

    /**
     * Create an instance of {@link APPLICANTSEGMENT.RELATIONS.RELATION }
     * 
     */
    public APPLICANTSEGMENT.RELATIONS.RELATION createAPPLICANTSEGMENTRELATIONSRELATION() {
        return new APPLICANTSEGMENT.RELATIONS.RELATION();
    }

    /**
     * Create an instance of {@link APPLICANTSEGMENT.IDS.ID }
     * 
     */
    public APPLICANTSEGMENT.IDS.ID createAPPLICANTSEGMENTIDSID() {
        return new APPLICANTSEGMENT.IDS.ID();
    }

}
