//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.19 at 05:48:48 PM IST 
//


package com.opl.mudra.api.cibil.model.report;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {// Do nothing because of X and Y.
    }

    /**
     * Create an instance of {@link DCResponse }
     * 
     */
    public DCResponse createDCResponse() {
        return new DCResponse();
    }

    /**
     * Create an instance of {@link DCResponse.ContextData }
     * 
     */
    public DCResponse.ContextData createDCResponseContextData() {
        return new DCResponse.ContextData();
    }

    /**
     * Create an instance of {@link DCResponse.Authentication }
     * 
     */
    public DCResponse.Authentication createDCResponseAuthentication() {
        return new DCResponse.Authentication();
    }

    /**
     * Create an instance of {@link DCResponse.ResponseInfo }
     * 
     */
    public DCResponse.ResponseInfo createDCResponseResponseInfo() {
        return new DCResponse.ResponseInfo();
    }

    /**
     * Create an instance of {@link DCResponse.ContextData.Field }
     * 
     */
    public DCResponse.ContextData.Field createDCResponseContextDataField() {
        return new DCResponse.ContextData.Field();
    }

}
