package com.opl.mudra.api.notification.utils;

public enum EmailSubjectAlias {

	EMAIL_PRIMARY_VIEW_FS(NotificationAlias.EMAIL_PRIMARY_VIEW_FS,2L) ,
	EMAIL_INPRINCIPLE_LETTER_FOR_MSME_FOR_FS(NotificationAlias.EXISTING_COMMON_PRINCIPLE_LETTER_SANCTION ,3L) ,
	EMAIL_INPRINCIPLE_LETTER_FOR_MSME_FOR_FP(NotificationAlias.EXISTING_COMMON_PRINCIPLE_LETTER_SANCTION ,4L) ,
	EMAIL_OF_THANKYOU_BANKSPECIFIC_FS(NotificationAlias.EMAIL_OF_THANKYOU_BANKSPECIFIC_FS ,5L) ,
	EMAIL_INPRINCIPLE_LETTER_FOR_PL_FOR_FS(NotificationAlias.PL_COMMON_PRINCIPLE_LETTER ,6L) ,
	EMAIL_INPRINCIPLE_LETTER_FOR_PL_FOR_FP(NotificationAlias.PL_COMMON_PRINCIPLE_LETTER ,7L) ,
	EMAIL_INPRINCIPLE_LETTER_FOR_HL_FOR_FS(NotificationAlias.HL_COMMON_INPRINCIPLE_LETTER ,8L) ,
	EMAIL_INPRINCIPLE_LETTER_FOR_HL_FOR_FP(NotificationAlias.HL_COMMON_INPRINCIPLE_LETTER ,9L) ,
	EMAIL_INPRINCIPLE_LETTER_FOR_AL_FOR_FS(NotificationAlias.AL_COMMON_INPRINCIPLE_LETTER ,10L) ,
	EMAIL_INPRINCIPLE_LETTER_FOR_AL_FOR_FP(NotificationAlias.AL_COMMON_INPRINCIPLE_LETTER ,11L) ,
	EMAIL_INTIMATION_FOR_MSME(NotificationAlias.EMAIL_ALL_MAKERS_AFTER_INPRINCIPLE_TO_FS ,12L) ,
	EMAIL_INTIMATION_FOR_PL(NotificationAlias.EMAIL_ALL_MAKERS_AFTER_INPRINCIPLE_TO_FS ,13L) ,
	EMAIL_INTIMATION_FOR_HL(NotificationAlias.EMAIL_ALL_MAKERS_AFTER_INPRINCIPLE_TO_FS ,14L) ,
	EMAIL_INTIMATION_FOR_AL(NotificationAlias.EMAIL_ALL_MAKERS_AFTER_INPRINCIPLE_TO_FS ,15L),//16 and 17 for header and footer
	EMAIL_FS_SIGNUP_COMPLETE(NotificationAlias.EMAIL_FS_SIGNUP_COMPLETE ,18L),
	EMAIL_FS_LEAVES_AFTER_OTP(NotificationAlias.EMAIL_FS_LEAVES_AFTER_OTP ,19L),
	EMAIL_FS_PRODUCT_SELECTED_NTB(NotificationAlias.EMAIL_FS_PRODUCT_SELECTED_NTB ,20L),
	EMAIL_FS_PRODUCT_SELECTED_FOR_RETAIL(NotificationAlias.PL_EMAIL_FS_PRODUCT_SELECTED ,21L),
	EMAIL_FS_PRODUCT_SELECTED_For_ONEPAGER(NotificationAlias.PL_EMAIL_FS_PRODUCT_SELECTED ,22L),
	EMAIL_FS_PRODUCT_SELECTED_EXISTING(NotificationAlias.EMAIL_FS_PRODUCT_SELECTED_EXISTING ,23L),
	EMAIL_FS_LEAVES_GST(NotificationAlias.EMAIL_FS_LEAVES_GST ,24L),
	EMAIL_FS_LEAVES_ITR(NotificationAlias.EMAIL_FS_LEAVES_ITR ,25L),
	PL_EMAIL_FS_LEAVES_ITR_PAGE(NotificationAlias.PL_EMAIL_FS_LEAVES_ITR_PAGE ,26L),
	EMAIL_FS_LEAVES_BANK_STATEMENT_PAGE(NotificationAlias.EMAIL_FS_LEAVES_BANK_STATEMENT_PAGE ,27L),
	PL_EMAIL_FS_LEAVES_BANK_STATEMENT_PAGE(NotificationAlias.PL_EMAIL_FS_LEAVES_BANK_STATEMENT_PAGE ,28L),
	EMAIL_FS_LEAVES_DIRECTOR_DETAILS_PAGE(NotificationAlias.EMAIL_FS_LEAVES_DIRECTOR_DETAILS_PAGE ,29L),
	EMAIL_FS_LEAVES_ONE_FORM(NotificationAlias.EMAIL_FS_LEAVES_ONE_FORM ,30L),
	EMAIL_FS_ACCEPTED_BY_MAKER(NotificationAlias.EMAIL_FS_ACCEPTED_BY_MAKER ,31L),
	PL_EMAIL_TO_FS_WHEN_MAKKER_ACCEPT_PROPOSAL(NotificationAlias.PL_EMAIL_TO_FS_WHEN_MAKKER_ACCEPT_PROPOSAL ,32L),
	EMAIL_FS_CHECKER_HOLDS_PROPOSAL(NotificationAlias.EMAIL_FS_CHECKER_HOLDS_PROPOSAL ,33L),
	EMAIL_FS_CHECKER_REJECTS_PROPOSAL(NotificationAlias.EMAIL_FS_CHECKER_REJECTS_PROPOSAL ,34L),
	EMAIL_FS_CHECKER_SANCTIONED(NotificationAlias.EMAIL_FS_CHECKER_SANCTIONED ,35L),
	EMAIL_FS_CHECKER_SANCTIONED_OFFLINE(NotificationAlias.EMAIL_FS_CHECKER_SANCTIONED ,36L),
	EMAIL_FS_CHECKER_DISBURSED_PROPOSAL(NotificationAlias.EMAIL_FS_CHECKER_DISBURSED_PROPOSAL ,37L),
	EMAIL_VERIFY_ACCOUNT_FP(NotificationAlias.EMAIL_VERIFY_ACCOUNT_FP ,38L),
	EMAIL_FORGOT_PASSWORD(NotificationAlias.EMAIL_FORGOT_PASSWORD ,39L),
	EMAIL_BRANCH_TRANSFER_HO_DDRCHECKER_DDRMAKER_BO_FS(NotificationAlias.EMAIL_BRANCH_TRANSFER_HO_DDRCHECKER_DDRMAKER_BO_FS ,40L),
	EMAIL_BRANCH_TRANSFER_HO_DDRCHECKER_DDRMAKER_BO_FS_ANOTHER_BRANCH(NotificationAlias.EMAIL_BRANCH_TRANSFER_HO_DDRCHECKER_DDRMAKER_BO_FS ,41L),
	EMAIL_MULTIPLEBANK_SCHEDULER_FS(NotificationAlias.EMAIL_MULTIPLEBANK_SCHEDULER_FS ,42L),
	EMAIL_MULTIPLEBANK_SCHEDULER_FS_OFFLINE(NotificationAlias.EMAIL_MULTIPLEBANK_SCHEDULER_FS ,43L),
	
	/** Fp*/
	EMAIL_MAKER_ACCEPT_PROPOSAL_OF_FS(NotificationAlias.EMAIL_MAKER_ACCEPT_PROPOSAL_OF_FS,44L),
	EMAIL_ADMIN_MAKER_PRODUCT_REVERTED_BY_CHECKER(NotificationAlias.EMAIL_ADMIN_MAKER_PRODUCT_REVERTED_BY_CHECKER,45L),
	EMAIL_MAKER_AFTER_CHECKER_APPROVED_DDR(NotificationAlias.EMAIL_MAKER_AFTER_CHECKER_APPROVED_DDR,46L),
	EMAIL_MAKER_AFTER_CHECKER_SUBMIT_SANCTION_POPUP(NotificationAlias.EMAIL_MAKER_AFTER_CHECKER_SUBMIT_SANCTION_POPUP,47L),
	EMAIL_MAKER_AFTER_CHECKER_HOLDS_PROPOSAL(NotificationAlias.EMAIL_MAKER_AFTER_CHECKER_HOLDS_PROPOSAL,48L),
	EMAIL_MAKER_AFTER_CHECKER_REJECTS_PROPOSAL(NotificationAlias.EMAIL_MAKER_AFTER_CHECKER_REJECTS_PROPOSAL,49L),
	EMAIL_MAKER_AFTER_CHECKER_DISBURSED_PROPOSAL(NotificationAlias.EMAIL_MAKER_AFTER_CHECKER_DISBURSED_PROPOSAL,50L),
	EMAIL_SANCTION_CHECKER_MULTIPLE_BANK(NotificationAlias.EMAIL_SANCTION_CHECKER_MULTIPLE_BANK,51L),
	EMAIL_HO_MULTIPLE_BANK(NotificationAlias.EMAIL_HO_MULTIPLE_BANK,52L),
	EMAIL_ADMIN_CHECKER_ADMIN_MAKER_CREATES_PRODUCT(NotificationAlias.EMAIL_ADMIN_CHECKER_ADMIN_MAKER_CREATES_PRODUCT,53L),
	EMAIL_ADMIN_MAKER_PRODUCT_APPROVED_BY_CHECKER(NotificationAlias.EMAIL_ADMIN_MAKER_PRODUCT_APPROVED_BY_CHECKER,54L),
	EMAIL_ADMIN_CHECKER_ADMIN_MAKER_RESENDS_PRODUCT(NotificationAlias.EMAIL_ADMIN_CHECKER_ADMIN_MAKER_RESENDS_PRODUCT,55L),
	EMAIL_ADMIN_MAKER_WHEN_PURPOSE_OF_LOAN_APPROVED(NotificationAlias.EMAIL_ADMIN_MAKER_WHEN_PURPOSE_OF_LOAN_APPROVED,56L),
	EMAIL_CHECKER_MAKER_ASSIGN_APPLICATION_TO_CHECKER(NotificationAlias.EMAIL_CHECKER_MAKER_ASSIGN_APPLICATION_TO_CHECKER,57L),
	EMAIL_CHECKER_MAKER_REASSIGN_TO_CHECKER(NotificationAlias.EMAIL_CHECKER_MAKER_REASSIGN_TO_CHECKER,58L),
	EMAIL_ADMIN_CHECKER_ADMIN_MAKER_RESENDS_SCORING(NotificationAlias.EMAIL_ADMIN_CHECKER_ADMIN_MAKER_RESENDS_SCORING,59L),
	EMAIL_ADMIN_CHECKER_ADMIN_MAKER_SET_SCORE(NotificationAlias.EMAIL_ADMIN_CHECKER_ADMIN_MAKER_SET_SCORE,60L),
	EMAIL_ADMIN_CHECKER_ADMIN_MAKER_EDITED_SCORING(NotificationAlias.EMAIL_ADMIN_CHECKER_ADMIN_MAKER_EDITED_SCORING,61L),
	EMAIL_ADMIN_MAKER_SCORING_APPROVED_BY_CHECKER(NotificationAlias.EMAIL_ADMIN_MAKER_SCORING_APPROVED_BY_CHECKER,62L),
	EMAIL_OTP_VERIFY_ACCOUNT(NotificationAlias.EMAIL_OTP_VERIFY_ACCOUNT,63L),
	EMAIL_FS_OTP_VERIFY(NotificationAlias.EMAIL_FS_OTP_VERIFY,64L),
	EMAIL_BRANCH_TRANSFER_TO_FS(NotificationAlias.EMAIL_BRANCH_TRANSFER_HO_DDRCHECKER_DDRMAKER_BO_FS ,65L),
	EMAIL_ADMIN_MAKER_WHEN_PURPOSE_OF_LOAN_REVERTED(NotificationAlias.EMAIL_ADMIN_MAKER_WHEN_PURPOSE_OF_LOAN_REVERTED ,66L),
	EMAIL_ADMIN_CHECKER_PURPOSE_OF_LOAN_CREATED(NotificationAlias.EMAIL_ADMIN_CHECKER_PURPOSE_OF_LOAN_CREATED ,67L),
	EMAIL_ADMINCHECKER_PURPOSE_OF_LOAN_RE_APPROVAL(NotificationAlias.EMAIL_ADMINCHECKER_PURPOSE_OF_LOAN_RE_APPROVAL ,68L),
	EMAIL_FS_WHEN_IN_ELIGIBLE(NotificationAlias.EMAIL_FS_WHEN_IN_ELIGIBLE ,69L),
	EMAIL_BRANCH_FS_WHEN_IN_ELIGIBLE_FOR_PERSONAL_LOAN(NotificationAlias.EMAIL_BRANCH_FS_WHEN_IN_ELIGIBLE ,70L),
	EMAIL_BRANCH_FS_WHEN_IN_ELIGIBLE_FOR_HOME_LOAN(NotificationAlias.EMAIL_BRANCH_FS_WHEN_IN_ELIGIBLE ,71L),
	EMAIL_BRANCH_FS_WHEN_IN_ELIGIBLE_FOR_AUTO_LOAN(NotificationAlias.EMAIL_BRANCH_FS_WHEN_IN_ELIGIBLE ,72L),
	EMAIL_BRANCH_FS_WHEN_IN_ELIGIBLE_MSME(NotificationAlias.EMAIL_FS_WHEN_IN_ELIGIBLE ,73L),
	EMAIL_OF_THANKYOU_BANKSPECIFIC_FP(NotificationAlias.EMAIL_OF_THANKYOU_BANKSPECIFIC_FP ,74L),
	COLANDING_INPRINCIPLE_LETTER(NotificationAlias.COLANDING_INPRINCIPLE_LETTER ,75L),
	
	//CO-Origination Mails
	CO_ORIGINATION_MAIL_ADMIN_MAKER_PRODUCT_APPROVED_BY_CHECKER(NotificationAlias.CO_ORIGINATION_MAIL_ADMIN_MAKER_PRODUCT_APPROVED_BY_CHECKER,127L),
	
	
	/** need to over ride */
	UNABLE_TO_REACH_HOLD_AND_REJECT_MAIL(NotificationAlias.EMAIL_FS_WHEN_PROPOSAL_REJECT_HOLD_FOR_SPECIFIC_REASON ,512L)
	;
	
	Long templateId;
	Long subjectId;
	
	EmailSubjectAlias(Long templateId,Long subjectId){
		this.templateId=templateId;
		this.subjectId=subjectId;
	}
	
	
	
	public Long getSubjectId(){
		return this.subjectId;
	}
	
	public Long getTemplateId() {
		return this.templateId;
	}
	public static Long getFirstSubjectIdByTemplateId(Long templateId) {
		for(EmailSubjectAlias alias	:	EmailSubjectAlias.values()) {
			if(alias.templateId == templateId) {
				return alias.subjectId;
			}
		}
		return null;
	}
	public static EmailSubjectAlias getFirstAliasByTemplateId(Long templateId) {
		for(EmailSubjectAlias alias	:	EmailSubjectAlias.values()) {
			if(alias.templateId == templateId) {
				return alias;
			}
		}
		return null;
	}
}
