package com.opl.mudra.api.notification.utils;

/**
 * @author maaz.shaikh
 *
 */
public enum NotificationMasterAlias {

	EMAIL_PRIMARY_VIEW_FS(1L,"EMAIL_PRIMARY_VIEW_FS",1),
	/** inprinciple*/
	MSME_INPRINCIPLE_LETTER(2L,"EXISTING_COMMON_PRINCIPLE_LETTER_SANCTION",1),
	EMAIL_OF_THANKYOU_BANKSPECIFIC_FS(3L,"EMAIL_OF_THANKYOU_BANKSPECIFIC_FS",1),
	PL_IN_PRINCIPLE_LETTER(4L,"PL_COMMON_INPRINCIPLE_LETTER",1),
	HL_IN_PRINCIPLE_LETTER(5L,"HL_COMMON_INPRINCIPLE_LETTER",1),
	AL_IN_PRINCIPLE_LETTER(6L,"AL_COMMON_INPRINCIPLE_LETTER",1),
	ML_IN_PRINCIPLE_LETTER(280L,"ML_COMMON_INPRINCIPLE_LETTER",1),
	EMAIL_ALL_MAKERS_AFTER_INPRINCIPLE_TO_FS(7L,"EMAIL_ALL_MAKERS_AFTER_INPRINCIPLE_TO_FS",1),
	
	SMS_ALL_MAKERS_AFTER_INPRINCIPLE_TO_FS(138L,"SMS_ALL_MAKERS_AFTER_INPRINCIPLE_TO_FS",2),
	SYS_ALL_MAKERS_AFTER_INPRINCIPLE_TO_FS(139L,"SYS_ALL_MAKERS_AFTER_INPRINCIPLE_TO_FS",3),
	
	
	/** otp and registration*/
	EMAIL_FS_SIGNUP_COMPLETE(8L,"EMAIL_FS_SIGNUP_COMPLETE",1),
	SMS_FS_COMPLETES_SIGNUP(9L,"SMS_FS_COMPLETES_SIGNUP",2),
	EMAIL_FS_LEAVES_AFTER_OTP(10L,"EMAIL_FS_LEAVES_AFTER_OTP",1),
	
	/** product selected*/
	PL_EMAIL_FS_RETAIL_PRODUCT_SELECTED(11L,"PL_EMAIL_FS_RETAIL_PRODUCT_SELECTED",1),
	PL_SMS_FS_RETAIL_PRODUCT_SELECTED(12L,"PL_SMS_FS_RETAIL_PRODUCT_SELECTED",2),
	EMAIL_FS_CORPORATE_PRODUCT_SELECTED(13L,"EMAIL_FS_CORPORATE_PRODUCT_SELECTED",1),
	
	/** leaves pages in msme */
	EMAIL_FS_LEAVES_GST(14L,"EMAIL_FS_LEAVES_GST",1),
	SMS_FS_LEAVES_GST(15L,"SMS_FS_LEAVES_GST",2),
	EMAIL_FS_LEAVES_ITR(16L,"EMAIL_FS_LEAVES_ITR",1),
	SMS_FS_LEAVES_ITR(17L,"EMAIL_FS_LEAVES_ITR",2),
	EMAIL_FS_LEAVES_BANK_STATEMENT_PAGE(18L,"EMAIL_FS_LEAVES_BANK_STATEMENT_PAGE",1),
	SMS_FS_LEAVES_BANK_STATEMENT(19L,"EMAIL_FS_LEAVES_BANK_STATEMENT_PAGE",2),
	EMAIL_FS_LEAVES_DIRECTOR_DETAILS_PAGE(20L,"EMAIL_FS_LEAVES_DIRECTOR_DETAILS_PAGE",1),
	SMS_FS_LEAVES_DIRECTOR_DETAILS_PAGE(21L,"SMS_FS_LEAVES_DIRECTOR_DETAILS_PAGE",2),
	EMAIL_FS_LEAVES_ONE_FORM(22L,"EMAIL_FS_LEAVES_ONE_FORM",1),
	SMS_FS_LEAVES_ONE_FORM(23L,"SMS_FS_LEAVES_ONE_FORM",2),
	
	/** proposal accepted by maker*/
	EMAIL_FS_ACCEPTED_BY_MAKER(24L,"EMAIL_FS_ACCEPTED_BY_MAKER",1),
	SMS_ALL_MAKERS_AFTER_MAKER_ACCEPT_PROPOSAL_OF_FS(25L,"SMS_ALL_MAKERS_AFTER_MAKER_ACCEPT_PROPOSAL_OF_FS",2),
	SYS_ALL_MAKERS_AFTER_MAKER_ACCEPT_PROPOSAL_OF_FS(26L,"SYS_ALL_MAKERS_AFTER_MAKER_ACCEPT_PROPOSAL_OF_FS",3),
	PL_EMAIL_TO_FS_WHEN_MAKKER_ACCEPT_PROPOSAL(27L,"PL_EMAIL_TO_FS_WHEN_MAKKER_ACCEPT_PROPOSAL",1),
	EMAIL_MAKER_ACCEPT_PROPOSAL_OF_FS(28L,"EMAIL_MAKER_ACCEPT_PROPOSAL_OF_FS",1),
	SMS_MAKER_ACCEPT_PROPOSAL_OF_FS(29L,"SMS_MAKER_ACCEPT_PROPOSAL_OF_FS",2),
	SYS_MAKER_ACCEPT_PROPOSAL_OF_FS(30L,"SYS_MAKER_ACCEPT_PROPOSAL_OF_FS",3),
	
	/** proposal hold*/
	EMAIL_FS_CHECKER_HOLDS_PROPOSAL(31L,"EMAIL_FS_CHECKER_HOLDS_PROPOSAL",1),
	SMS_FS_CHECKER_HOLDS_PROPOSAL(32L,"SMS_FS_CHECKER_HOLDS_PROPOSAL",2),
	SYS_FS_CHECKER_HOLDS_PROPOSAL(33L,"SYS_FS_CHECKER_HOLDS_PROPOSAL",3),
	
	/** proposal rejected*/
	EMAIL_FS_CHECKER_REJECTS_PROPOSAL(34L,"EMAIL_FS_CHECKER_REJECTS_PROPOSAL",1),
	SMS_FS_CHECKER_REJECTS_PROPOSAL(35L,"SMS_FS_CHECKER_REJECTS_PROPOSAL",2),
	SYS_FS_CHECKER_REJECTS_PROPOSAL(36L,"SMS_FS_CHECKER_REJECTS_PROPOSAL",3),
	
	/** proposal sanctioned*/
	EMAIL_FS_CHECKER_SANCTIONED(37L,"EMAIL_FS_CHECKER_SANCTIONED",1),
	SMS_FS_CHECKER_SANCTIONED(38L,"SMS_FS_CHECKER_SANCTIONED",2),
	SYS_FS_CHECKER_SANCTIONED(39L,"SYS_FS_CHECKER_SANCTIONED",3),
	 
	/** proposal disbursed*/
	EMAIL_FS_CHECKER_DISBURSED_PROPOSAL(40L,"EMAIL_FS_CHECKER_DISBURSED_PROPOSAL",1),
	SMS_FS_CHECKER_DISBURSED_PROPOSAL(41L,"SMS_FS_CHECKER_DISBURSED_PROPOSAL",2),
	SYS_FS_CHECKER_DISBURSED_PROPOSAL(42L,"SYS_FS_CHECKER_DISBURSED_PROPOSAL",3),
	
	EMAIL_VERIFY_ACCOUNT_FP(43L,"EMAIL_VERIFY_ACCOUNT_FP",1),
	EMAIL_FORGOT_PASSWORD(44L,"EMAIL_FORGOT_PASSWORD",1),
	
	/** multiple bank intemation to user*/
	EMAIL_MULTIPLEBANK_SCHEDULER_FS(45L,"EMAIL_MULTIPLEBANK_SCHEDULER_FS",1),
	SMS_MULTIPLEBANK_SCHEDULER_FS(46L,"SMS_MULTIPLEBANK_SCHEDULER_FS",2),
	SYS_MULTIPLEBANK_SCHEDULER_FS(47L,"SYS_MULTIPLEBANK_SCHEDULER_FS",3),
	
	/** products*/
	EMAIL_ADMIN_MAKER_PRODUCT_REVERTED_BY_CHECKER(48L,"EMAIL_ADMIN_MAKER_PRODUCT_REVERTED_BY_CHECKER",1),
	SMS_ADMIN_MAKER_PRODUCT_REVERTED_BY_CHECKER(49L,"SMS_ADMIN_MAKER_PRODUCT_REVERTED_BY_CHECKER",2),
	SYS_ADMIN_MAKER_PRODUCT_REVERTED_BY_CHECKER(50L,"SYS_ADMIN_MAKER_PRODUCT_REVERTED_BY_CHECKER",3),
	
	/** ddr*/
	EMAIL_MAKER_AFTER_CHECKER_APPROVED_DDR(51L,"EMAIL_MAKER_AFTER_CHECKER_APPROVED_DDR",1),
	SMS_MAKER_AFTER_CHECKER_APPROVED_DDR(52L,"SMS_MAKER_AFTER_CHECKER_APPROVED_DDR",2),
	SYS_MAKER_AFTER_CHECKER_APPROVED_DDR(53L,"SYS_MAKER_AFTER_CHECKER_APPROVED_DDR",3),
	SMS_HO_CHECKER_APPROVED_DDR(126L,"SMS_HO_CHECKER_APPROVED_DDR",2),
	EMAIL_ALL_BO_CHECKER_APPROVED_DDR(127L,"EMAIL_ALL_BO_CHECKER_APPROVED_DDR",1),
	SMS_ALL_BO_CHECKER_APPROVED_DDR(128L,"SMS_ALL_BO_CHECKER_APPROVED_DDR",2),
	SYS_ALL_BO_CHECKER_APPROVED_DDR(129L,"SYS_ALL_BO_CHECKER_APPROVED_DDR",3),
	SYS_HO_CHECKER_APPROVED_DDR(130L,"SYS_HO_CHECKER_APPROVED_DDR",3),
	
	
	/** proposal sanctioned email to fp*/
	EMAIL_MAKER_AFTER_CHECKER_SUBMIT_SANCTION_POPUP(54L,"EMAIL_MAKER_AFTER_CHECKER_SUBMIT_SANCTION_POPUP",1),
	SYS_MAKER_AFTER_CHECKER_SUBMIT_SANCTION_POPUP(55L,"SYS_MAKER_AFTER_CHECKER_SUBMIT_SANCTION_POPUP",3),
	SMS_HO_CHECKER_SANCTIONED(56L,"SMS_HO_CHECKER_SANCTIONED",2),

	/** proposal Hold email to fp*/
	EMAIL_MAKER_AFTER_CHECKER_HOLDS_PROPOSAL(57L,"EMAIL_MAKER_AFTER_CHECKER_HOLDS_PROPOSAL",1),
	SYS_MAKER_AFTER_CHECKER_HOLDS_PROPOSAL(58L,"SYS_MAKER_AFTER_CHECKER_HOLDS_PROPOSAL",3),
	SMS_HO_CHECKER_HOLDS_PROPOSAL(59L,"SMS_HO_CHECKER_HOLDS_PROPOSAL",2),
	SYS_HO_CHECKER_HOLDS_PROPOSAL(60L,"SYS_HO_CHECKER_HOLDS_PROPOSAL",3),
	EMAIL_HO_CHECKER_HOLDS_PROPOSAL(61L,"EMAIL_HO_CHECKER_HOLDS_PROPOSAL",1),
	
	/** proposal reject email to fp*/
	EMAIL_MAKER_AFTER_CHECKER_REJECTS_PROPOSAL(62L,"EMAIL_MAKER_AFTER_CHECKER_REJECTS_PROPOSAL",1),
	SYS_MAKER_AFTER_CHECKER_REJECTS_PROPOSAL(63L,"SYS_MAKER_AFTER_CHECKER_REJECTS_PROPOSAL",3),
	SMS_HO_CHECKER_REJECTS_PROPOSAL(64L,"SMS_HO_CHECKER_REJECTS_PROPOSAL",2),
	SYS_HO_CHECKER_REJECTS_PROPOSAL(65L,"SYS_HO_CHECKER_REJECTS_PROPOSAL",3),
	EMAIL_HO_CHECKER_REJECTS_PROPOSAL(66L,"EMAIL_HO_CHECKER_REJECTS_PROPOSAL",1),
	
	/** proposal Hold email to fp*/
	EMAIL_MAKER_AFTER_CHECKER_DISBURSED_PROPOSAL(67L,"EMAIL_MAKER_AFTER_CHECKER_DISBURSED_PROPOSAL",1),
	SMS_HO_CHECKER_DISBURSED_PROPOSAL(68L,"SMS_HO_CHECKER_DISBURSED_PROPOSAL",2),
	SYS_HO_CHECKER_DISBURSED_PROPOSAL(69L,"SYS_HO_CHECKER_DISBURSED_PROPOSAL",3),
	SMS_MAKER_AFTER_CHECKER_DISBURSED_PROPOSAL(70L,"SMS_MAKER_AFTER_CHECKER_DISBURSED_PROPOSAL",2),
	SYS_MAKER_AFTER_CHECKER_DISBURSED_PROPOSAL(71L,"SYS_MAKER_AFTER_CHECKER_DISBURSED_PROPOSAL",3),

	
	/** proposal sanctioned multiple bank - email to fp*/
	EMAIL_SANCTION_CHECKER_MULTIPLE_BANK(72L,"EMAIL_SANCTION_CHECKER_MULTIPLE_BANK",1),
	SMS_SANCTION_HO_MULTIPLE_BANK(73L,"SMS_SANCTION_HO_MULTIPLE_BANK",2),
	/** Dirsbuesed*/
	EMAIL_FP_MULTIPLE_BANK_DISBURSED(74L,"EMAIL_FP_MULTIPLE_BANK_DISBURSED",1),
	SMS_FP_MULTIPLE_BANK_DISBURSED(75L,"SMS_FP_MULTIPLE_BANK_DISBURSED",2),
	
	/**product*/
	EMAIL_ADMIN_CHECKER_ADMIN_MAKER_CREATES_PRODUCT(76L,"EMAIL_ADMIN_CHECKER_ADMIN_MAKER_CREATES_PRODUCT",1),
	SYS_ADMIN_CHECKER_ADMIN_MAKER_CREATES_PRODUCT(77L,"SYS_ADMIN_CHECKER_ADMIN_MAKER_CREATES_PRODUCT",3),
	SMS_ADMIN_CHECKER_ADMIN_MAKER_CREATES_PRODUCT(78L,"SMS_ADMIN_CHECKER_ADMIN_MAKER_CREATES_PRODUCT",2),
	EMAIL_ADMIN_MAKER_PRODUCT_APPROVED_BY_CHECKER(79L,"EMAIL_ADMIN_MAKER_PRODUCT_APPROVED_BY_CHECKER",1),
	SMS_ADMIN_MAKER_PRODUCT_APPROVED_BY_CHECKER(80L,"SMS_ADMIN_MAKER_PRODUCT_APPROVED_BY_CHECKER",2),
	SYS_ADMIN_MAKER_PRODUCT_APPROVED_BY_CHECKER(81L,"SYS_ADMIN_MAKER_PRODUCT_APPROVED_BY_CHECKER",3),
	EMAIL_ADMIN_CHECKER_ADMIN_MAKER_RESENDS_PRODUCT(82L,"EMAIL_ADMIN_CHECKER_ADMIN_MAKER_RESENDS_PRODUCT",1),
	SMS_ADMIN_CHECKER_ADMIN_MAKER_RESENDS_PRODUCT(83L,"SMS_ADMIN_CHECKER_ADMIN_MAKER_RESENDS_PRODUCT",2),
	SYS_ADMIN_CHECKER_ADMIN_MAKER_RESENDS_PRODUCT(84L,"SYS_ADMIN_CHECKER_ADMIN_MAKER_RESENDS_PRODUCT",3),

	/** purpose of loan*/
	EMAIL_ADMIN_MAKER_WHEN_PURPOSE_OF_LOAN_APPROVED(85L,"EMAIL_ADMIN_MAKER_WHEN_PURPOSE_OF_LOAN_APPROVED",1),
	SMS_ADMIN_MAKER_WHEN_PURPOSE_OF_LOAN_APPROVED(86L,"SMS_ADMIN_MAKER_WHEN_PURPOSE_OF_LOAN_APPROVED",2),
	EMAIL_ADMIN_MAKER_WHEN_PURPOSE_OF_LOAN_REVERTED(87L,"EMAIL_ADMIN_MAKER_WHEN_PURPOSE_OF_LOAN_REVERTED",1),
	SMS_ADMIN_MAKER_WHEN_PURPOSE_OF_LOAN_REVERT_BECK(88L,"SMS_ADMIN_MAKER_WHEN_PURPOSE_OF_LOAN_APPROVED",2),
	EMAIL_ADMIN_CHECKER_PURPOSE_OF_LOAN_CREATED(89L,"EMAIL_ADMIN_CHECKER_PURPOSE_OF_LOAN_CREATED",1),
	SMS_ADMIN_CHECKER_PURPOSE_OF_LOAN_CREATED(90L,"SMS_ADMIN_CHECKER_PURPOSE_OF_LOAN_CREATED",2),
	EMAIL_ADMINCHECKER_PURPOSE_OF_LOAN_RE_APPROVAL(91L,"EMAIL_ADMINCHECKER_PURPOSE_OF_LOAN_RE_APPROVAL",1),
	SMS_ADMIN_CHECKER_PURPOSE_OF_LOAN_RE_APPROVAL_BY_MAKER(92L,"SMS_ADMIN_CHECKER_PURPOSE_OF_LOAN_RE_APPROVAL_BY_MAKER",2),

	/** MakerAssignDDRToChecker */
	EMAIL_CHECKER_MAKER_ASSIGN_APPLICATION_TO_CHECKER(93L,"EMAIL_CHECKER_MAKER_ASSIGN_APPLICATION_TO_CHECKER",1),
	SMS_CHECKER_MAKER_ASSIGN_APPLICATION_TO_CHECKER(94L,"SMS_CHECKER_MAKER_ASSIGN_APPLICATION_TO_CHECKER",2),
	SYS_CHECKER_MAKER_ASSIGN_APPLICATION_TO_CHECKER(95L,"SYS_CHECKER_MAKER_ASSIGN_APPLICATION_TO_CHECKER",3),
	/** MakerReAssignDDRToChecker */
	EMAIL_CHECKER_MAKER_REASSIGN_TO_CHECKER(96L,"EMAIL_CHECKER_MAKER_REASSIGN_TO_CHECKER",1),
	SMS_CHECKER_MAKER_REASSIGN_TO_CHECKER(97L,"SMS_CHECKER_MAKER_REASSIGN_TO_CHECKER",2),
	SYS_CHECKER_MAKER_REASSIGN_TO_CHECKER(98L,"SYS_CHECKER_MAKER_ASSIGN_APPLICATION_TO_CHECKER",3),
	
	/** scoring */
	EMAIL_ADMIN_CHECKER_ADMIN_MAKER_RESENDS_SCORING(99L,"EMAIL_ADMIN_CHECKER_ADMIN_MAKER_RESENDS_SCORING",1),
	SMS_ADMIN_CHECKER_ADMIN_MAKER_RESENDS_SCORING(100L,"SMS_ADMIN_CHECKER_ADMIN_MAKER_RESENDS_SCORING",2),
	SYS_ADMIN_CHECKER_ADMIN_MAKER_RESENDS_SCORING(101L,"SYS_ADMIN_CHECKER_ADMIN_MAKER_RESENDS_SCORING",3),
	
	EMAIL_ADMIN_CHECKER_ADMIN_MAKER_SET_SCORE(102L,"EMAIL_ADMIN_CHECKER_ADMIN_MAKER_SET_SCORE",1),
	SMS_ADMIN_CHECKER_ADMIN_MAKER_SET_SCORE(103L,"SMS_ADMIN_CHECKER_ADMIN_MAKER_SET_SCORE",2),
	SYS_ADMIN_CHECKER_ADMIN_MAKER_SET_SCORE(104L,"SYS_ADMIN_CHECKER_ADMIN_MAKER_SET_SCORE",3),
	
	EMAIL_ADMIN_CHECKER_ADMIN_MAKER_EDITED_SCORING(105L,"EMAIL_ADMIN_CHECKER_ADMIN_MAKER_EDITED_SCORING",1),
	SMS_ADMIN_CHECKER_ADMIN_MAKER_EDITED_SCORING(106L,"SMS_ADMIN_CHECKER_ADMIN_MAKER_EDITED_SCORING",2),
	SYS_ADMIN_CHECKER_ADMIN_MAKER_EDITED_SCORING(107L,"SYS_ADMIN_CHECKER_ADMIN_MAKER_EDITED_SCORING",3),
	
	EMAIL_ADMIN_MAKER_SCORING_APPROVED_BY_CHECKER(108L,"EMAIL_ADMIN_MAKER_SCORING_APPROVED_BY_CHECKER",1),
	SMS_ADMIN_MAKER_SCORING_APPROVED_BY_CHECKER(109L,"SMS_ADMIN_MAKER_SCORING_APPROVED_BY_CHECKER",2),
	SYS_ADMIN_MAKER_SCORING_APPROVED_BY_CHECKER(110L,"SYS_ADMIN_MAKER_SCORING_APPROVED_BY_CHECKER",3),
	
	/** otp varification*/
	EMAIL_FS_OTP_VERIFY(111L,"EMAIL_FS_OTP_VERIFY",1),
	SMS_OTP(116L,"SMS_OTP",2),
	SMS_LOGIN_OTP(226L,"SMS_LOGIN_OTP",2),
	
	/** inEligible */
	EMAIL_FS_WHEN_IN_ELIGIBLE(112L,"EMAIL_FS_WHEN_IN_ELIGIBLE",1),
	EMAIL_BRANCH_FS_WHEN_IN_ELIGIBLE(113L,"EMAIL_BRANCH_FS_WHEN_IN_ELIGIBLE",1),
	/** Sidbi specific and sbi renewal */
	EMAIL_OF_THANKYOU_BANKSPECIFIC_FP(114L,"EMAIL_OF_THANKYOU_BANKSPECIFIC_FP",1),
	
	/** Co landing inprinciple letter*/
	COLANDING_INPRINCIPLE_LETTER(115L,"COLANDING_INPRINCIPLE_LETTER",1),
	
	/** ddr reverted*/
	EMAIL_MAKER_AFTER_CHECKER_REVERTS_MAKER(117L,"EMAIL_MAKER_AFTER_CHECKER_REVERTS_MAKER",1),
	EMAIL_HO_CHECKER_APPROVED_DDR(118L,"EMAIL_HO_CHECKER_APPROVED_DDR",1),
	/** hold or reject for reason - Unable to contact client*/
	EMAIL_FS_REJECT_HOLD_FOR_UNABLE_CONTACT_CLIENT_REASEON(119L,"EMAIL_FS_REJECT_HOLD_FOR_UNABLE_CONTACT_CLIENT_REASEON",1),
	SMS_FS_REJECT_HOLD_FOR_UNABLE_CONTACT_CLIENT_REASEON(120L,"SMS_FS_REJECT_HOLD_FOR_UNABLE_CONTACT_CLIENT_REASEON",2),
	SYS_FS_REJECT_HOLD_FOR_UNABLE_CONTACT_CLIENT_REASEON(122L,"SYS_FS_REJECT_HOLD_FOR_UNABLE_CONTACT_CLIENT_REASEON",3),
	
	/** hold or reject for reason - Unable to contact client*/
	SMS_SANCTION_CHECKER_MULTIPLE_BANK(121L,"SMS_SANCTION_CHECKER_MULTIPLE_BANK",2),
	
	/** assign from workflow*/
	EMAIL_CHECKER_ASSIGNED_MAKER(131L,"EMAIL_CHECKER_ASSIGNED_MAKER",1),
	SMS_CHECKER_ASSIGN_CLIENT(132L,"SMS_CHECKER_ASSIGN_CLIENT",2),
	
	/** payment success */
	SMS_FS_PAYS_CONVIENCE_FEE (135L,"SMS_FS_PAYS_CONVIENCE_FEE",2),
	SYS_FS_PAYS_CONVIENCE_FEE (134L,"SYS_FS_PAYS_CONVIENCE_FEE",3),
	
	
	/** payment canceled*/
	EMAIL_FS_PAYS_CANCEL_PAYMENT(136L,"EMAIL_FS_PAYS_CANCEL_PAYMENT",1),
	SMS_FS_CANCELS_PAYMENT(137L,"SMS_FS_CANCELS_PAYMENT",2),
	
	
	EMAIL_DDR_APPROVED(133L,"EMAIL_DDR_APPROVED",1),
	SMS_APPROVER_APPROVE_DDR_MAKER(140L,"SMS_APPROVER_APPROVE_DDR_MAKER",2),
	
	MAIL_FS_DDR_FAILED(141L,"MAIL_FS_DDR_FAILED",1),
	SYS_FS_DDR_FAILED(143L,"SYS_FS_DDR_FAILED",3),
	
	MAIL_CKR_APPROVER_APPROVED(142L,"MAIL_CKR_APPROVER_APPROVED",1),
	SMS_APPROVER_APPROVE_DDR(144L,"SMS_APPROVER_APPROVE_DDR",2),

	SMS_DDR_APPROVED(145L,"SMS_DDR_APPROVED",2),
	
	EMAIL_ADMIN_MAKER_SCORING_REVERTED_BY_CHECKER(148L,"EMAIL_ADMIN_MAKER_SCORING_REVERTED_BY_CHECKER",1),
    SMS_ADMIN_MAKER_SCORING_REVERTED_BY_CHECKER(149L,"SMS_ADMIN_MAKER_SCORING_REVERTED_BY_CHECKER",2),
    SYS_ADMIN_MAKER_SCORING_REVERTED_BY_CHECKER(156L,"SYS_ADMIN_MAKER_SCORING_REVERTED_BY_CHECKER",3),
	
	MAIL_FS_MARKER_ASSIGNED(150L,"MAIL_FS_MARKER_ASSIGNED",1),
	SYS_FS_MARKER_ASSIGNED(151L,"SYS_FS_MARKER_ASSIGNED",3),
	
	SYS_MKR_CKR_ASSIGN_CLIENT(152L,"SYS_MKR_CKR_ASSIGN_CLIENT",3),
	
	SMS_MAKER_AFTER_CHECKER_REVERTS_MAKER(153L,"SMS_MAKER_AFTER_CHECKER_REVERTS_MAKER",2),
	SYS_MAKER_AFTER_CHECKER_REVERTS_MAKER(154L,"SYS_MAKER_AFTER_CHECKER_REVERTS_MAKER",3),
	
	EMAIL_HO_CHECKER_REVERTS_MAKER(155L,"EMAIL_HO_CHECKER_REVERTS_MAKER",1),
	SMS_HO_CHECKER_REVERTS_MAKER(157L,"SMS_HO_CHECKER_REVERTS_MAKER",2),
	SYS_HO_CHECKER_REVERTS_MAKER(158L,"SYS_HO_CHECKER_REVERTS_MAKER",3),
	
	EMAIL_ALL_BO_CHECKER_REVERTS_MAKER(159L,"EMAIL_ALL_BO_CHECKER_REVERTS_MAKER",1),
	SMS_ALL_BO_CHECKER_REVERTS_MAKER(160L,"SMS_ALL_BO_CHECKER_REVERTS_MAKER",2),
	SYS_ALL_BO_CHECKER_REVERTS_MAKER(161L,"SYS_ALL_BO_CHECKER_REVERTS_MAKER",3),
	
	MAIL_CKR_MKR_SUMBIT_DDR(162L,"MAIL_CKR_MKR_SUMBIT_DDR",1),
	SMS_MAKER_SUBMIT_DDR_CKR(163L,"SMS_MAKER_SUBMIT_DDR_CKR",2),
	SYS_CKR_MKR_SUMBIT_DDR(164L,"SYS_CKR_MKR_SUMBIT_DDR",3),
	
	MAIL_CKR_APPROVER_SEND_BACK(165L,"MAIL_CKR_APPROVER_SEND_BACK",1),
	
	MAIL_APPROVER_CKR_SEND_DDR_TO_APPROVER_AFTR_REVIEW(166L,"MAIL_APPROVER_CKR_SEND_DDR_TO_APPROVER_AFTR_REVIEW",1),
	SMS_CKR_SEND_DDR_TO_APPROVER_AFTER_REVIEW(167L,"SMS_CKR_SEND_DDR_TO_APPROVER_AFTER_REVIEW",2),
	
	SYS_APPROVER_CKR_REVERT_PROPOSAL(168L,"SYS_APPROVER_CKR_REVERT_PROPOSAL",3),
	
	MAIL_APPROVER_CKR_SEND_DDR_TO_APPROVER(169L,"MAIL_APPROVER_CKR_SEND_DDR_TO_APPROVER",1),
	SMS_CKR_SEND_DDR_TO_APPROVER_FOR_REVIEW(170L,"SMS_CKR_SEND_DDR_TO_APPROVER_FOR_REVIEW",2),
	SYS_APPROVER_CKR_SEND_DDR_TO_APPROVER(171L,"SYS_APPROVER_CKR_SEND_DDR_TO_APPROVER",3),
	
	// CO-Origination Mail
	CO_ORIGINATION_MAIL_ADMIN_MAKER_PRODUCT_APPROVED_BY_CHECKER(172L,"CO_ORIGINATION_MAIL_ADMIN_MAKER_PRODUCT_APPROVED_BY_CHECKER",1),
	CO_ORIGINATION_SMS_ADMIN_MAKER_PRODUCT_APPROVED_BY_CHECKER(173L,"CO_ORIGINATION_SMS_ADMIN_MAKER_PRODUCT_APPROVED_BY_CHECKER",2),
	CO_ORIGINATION_SYS_ADMIN_MAKER_PRODUCT_APPROVED_BY_CHECKER(174L,"CO_ORIGINATION_SYS_ADMIN_MAKER_PRODUCT_APPROVED_BY_CHECKER",3),
	
	CO_ORIGINATION_EMAIL_ADMIN_MAKER_SCORING_APPROVED_BY_CHECKER(175L,"CO_ORIGINATION_EMAIL_ADMIN_MAKER_SCORING_APPROVED_BY_CHECKER",1),
	CO_ORIGINATION_SMS_ADMIN_MAKER_SCORING_APPROVED_BY_CHECKER(176L,"CO_ORIGINATION_SMS_ADMIN_MAKER_SCORING_APPROVED_BY_CHECKER",2),
	CO_ORIGINATION_SYS_ADMIN_MAKER_SCORING_APPROVED_BY_CHECKER(177L,"SYS_ADMIN_MAKER_SCORING_APPROVED_BY_CHECKER",3),
	
	CO_ORIGINATION_EMAIL_ADMIN_MAKER_PRODUCT_REVERTED_BY_CHECKER(178L,"CO_ORIGINATION_EMAIL_ADMIN_MAKER_PRODUCT_REVERTED_BY_CHECKER",1),
	CO_ORIGINATION_SMS_ADMIN_MAKER_PRODUCT_REVERTED_BY_CHECKER(179L,"CO_ORIGINATION_SYS_ADMIN_MAKER_PRODUCT_REVERTED_BY_CHECKER",2),
	CO_ORIGINATION_SYS_ADMIN_MAKER_PRODUCT_REVERTED_BY_CHECKER(180L,"CO_ORIGINATION_SYS_ADMIN_MAKER_PRODUCT_REVERTED_BY_CHECKER",3),
	
	CO_ORIGINATION_EMAIL_ADMIN_MAKER_SCORING_REVERTED_BY_CHECKER(181L,"CO_ORIGINATION_EMAIL_ADMIN_MAKER_SCORING_REVERTED_BY_CHECKER",1),
	CO_ORIGINATION_SMS_ADMIN_MAKER_SCORING_REVERTED_BY_CHECKER(182L,"CO_ORIGINATION_SMS_ADMIN_MAKER_SCORING_REVERTED_BY_CHECKER",2),
	CO_ORIGINATION_SYS_ADMIN_MAKER_SCORING_REVERTED_BY_CHECKER(183L,"CO_ORIGINATION_SYS_ADMIN_MAKER_SCORING_REVERTED_BY_CHECKER",3),
	
	CO_ORIGINATION_EMAIL_ADMIN_CHECKER_ADMIN_MAKER_CREATES_PRODUCT(184L,"CO_ORIGINATION_EMAIL_ADMIN_CHECKER_ADMIN_MAKER_CREATES_PRODUCT",1),
	CO_ORIGINATION_SMS_ADMIN_CHECKER_ADMIN_MAKER_CREATES_PRODUCT(185L,"CO_ORIGINATION_SMS_ADMIN_CHECKER_ADMIN_MAKER_CREATES_PRODUCT",2),
	CO_ORIGINATION_SYS_ADMIN_CHECKER_ADMIN_MAKER_CREATES_PRODUCT(186L,"CO_ORIGINATION_SYS_ADMIN_CHECKER_ADMIN_MAKER_CREATES_PRODUCT",3),
	
	CO_ORIGINATION_EMAIL_ADMIN_CHECKER_ADMIN_MAKER_SET_SCORE(187L,"CO_ORIGINATION_EMAIL_ADMIN_CHECKER_ADMIN_MAKER_SET_SCORE",1),
	CO_ORIGINATION_SMS_ADMIN_CHECKER_ADMIN_MAKER_SET_SCORE(188L,"CO_ORIGINATION_SMS_ADMIN_CHECKER_ADMIN_MAKER_SET_SCORE",2),
	CO_ORIGINATION_SYS_ADMIN_CHECKER_ADMIN_MAKER_SET_SCORE(189L,"CO_ORIGINATION_SYS_ADMIN_CHECKER_ADMIN_MAKER_SET_SCORE",3),
	
	CO_ORIGINATION_EMAIL_ADMIN_CHECKER_ADMIN_MAKER_RESENDS_PRODUCT(190L,"CO_ORIGINATION_EMAIL_ADMIN_CHECKER_ADMIN_MAKER_RESENDS_PRODUCT",1),
	CO_ORIGINATION_SMS_ADMIN_CHECKER_ADMIN_MAKER_RESENDS_PRODUCT(191L,"CO_ORIGINATION_SMS_ADMIN_CHECKER_ADMIN_MAKER_RESENDS_PRODUCT",2),
	CO_ORIGINATION_SYS_ADMIN_CHECKER_ADMIN_MAKER_RESENDS_PRODUCT(192L,"CO_ORIGINATION_SYS_ADMIN_CHECKER_ADMIN_MAKER_RESENDS_PRODUCT",3),
	
	CO_ORIGINATION_EMAIL_ADMIN_CHECKER_ADMIN_MAKER_RESENDS_SCORING(193L,"CO_ORIGINATION_EMAIL_ADMIN_CHECKER_ADMIN_MAKER_RESENDS_SCORING",1),
	CO_ORIGINATION_SMS_ADMIN_CHECKER_ADMIN_MAKER_RESENDS_SCORING(194L,"CO_ORIGINATION_SMS_ADMIN_CHECKER_ADMIN_MAKER_RESENDS_SCORING",2),
	CO_ORIGINATION_SYS_ADMIN_CHECKER_ADMIN_MAKER_RESENDS_SCORING(195L,"CO_ORIGINATION_SYS_ADMIN_CHECKER_ADMIN_MAKER_RESENDS_SCORING",3),
	
	CO_ORIGINATION_EMAIL_ADMIN_CHECKER_ADMIN_MAKER_EDITED_SCORING(196L,"CO_ORIGINATION_EMAIL_ADMIN_CHECKER_ADMIN_MAKER_EDITED_SCORING",1),
	CO_ORIGINATION_SMS_ADMIN_CHECKER_ADMIN_MAKER_EDITED_SCORING(197L,"CO_ORIGINATION_SMS_ADMIN_CHECKER_ADMIN_MAKER_EDITED_SCORING",2),
	CO_ORIGINATION_SYS_ADMIN_CHECKER_ADMIN_MAKER_EDITED_SCORING(198L,"CO_ORIGINATION_SYS_ADMIN_CHECKER_ADMIN_MAKER_EDITED_SCORING",3),
	
	CO_ORIGINATION_EMAIL_ALL_MAKERS_AFTER_INPRINCIPLE_TO_FS(199L,"CO_ORIGINATION_EMAIL_ALL_MAKERS_AFTER_INPRINCIPLE_TO_FS",1),
	CO_ORIGINATION_SMS_ALL_MAKERS_AFTER_INPRINCIPLE_TO_FS(200L,"CO_ORIGINATION_SMS_ALL_MAKERS_AFTER_INPRINCIPLE_TO_FS",2),
	CO_ORIGINATION_SYS_ALL_MAKERS_AFTER_INPRINCIPLE_TO_FS(201L,"CO_ORIGINATION_SYS_ALL_MAKERS_AFTER_INPRINCIPLE_TO_FS",3),
	
	//	============	Co-Origination Ratio	============================================================
	
	CO_ORIGINATION_EMAIL_MAKER_RATIO_APPROVED_BY_CHECKER(202L,"CO_ORIGINATION_EMAIL_MAKER_RATIO_APPROVED_BY_CHECKER",1),
	CO_ORIGINATION_SMS_MAKER_RATIO_APPROVED_BY_CHECKER(203L,"CO_ORIGINATION_SMS_MAKER_RATIO_APPROVED_BY_CHECKER",2),
	CO_ORIGINATION_SYS_MAKER_RATIO_APPROVED_BY_CHECKER(204L,"CO_ORIGINATION_SYS_MAKER_RATIO_APPROVED_BY_CHECKER",3),
	
	CO_ORIGINATION_EMAIL_MAKER_RATIO_SENT_BACK_BY_CHECKER(205L,"CO_ORIGINATION_EMAIL_MAKER_RATIO_SENT_BACK_BY_CHECKER",1),
	CO_ORIGINATION_SMS_MAKER_RATIO_SENT_BACK_BY_CHECKER(206L,"CO_ORIGINATION_SMS_MAKER_RATIO_SENT_BACK_BY_CHECKER",2),
	CO_ORIGINATION_SYS_MAKER_RATIO_SENT_BACK_BY_CHECKER(207L,"CO_ORIGINATION_SYS_MAKER_RATIO_SENT_BACK_BY_CHECKER",3),
	
	CO_ORIGINATION_EMAIL_CHECKER_RATIO_SENT_FOR_APPROVAL(208L,"CO_ORIGINATION_EMAIL_CHECKER_RATIO_SENT_FOR_APPROVAL",1),
	CO_ORIGINATION_SMS_CHECKER_RATIO_SENT_FOR_APPROVAL(209L,"CO_ORIGINATION_SMS_CHECKER_RATIO_SENT_FOR_APPROVAL",2),
	CO_ORIGINATION_SYS_CHECKER_RATIO_SENT_FOR_APPROVAL(210L,"CO_ORIGINATION_SYS_CHECKER_RATIO_SENT_FOR_APPROVAL",3),
	
	CO_ORIGINATION_EMAIL_CHECKER_RATIO_RESENT_FOR_APPROVAL(211L,"CO_ORIGINATION_EMAIL_CHECKER_RATIO_RESENT_FOR_APPROVAL",1),
	CO_ORIGINATION_SMS_CHECKER_RATIO_RESENT_FOR_APPROVAL(212L,"CO_ORIGINATION_SMS_CHECKER_RATIO_RESENT_FOR_APPROVAL",2),
	CO_ORIGINATION_SYS_CHECKER_RATIO_RESENT_FOR_APPROVAL(213L,"CO_ORIGINATION_SYS_CHECKER_RATIO_RESENT_FOR_APPROVAL",3),
	
	CO_ORIGINATION_EMAIL_CHECKER_RATIO_SENT_TO_BANK_FOR_APPROVAL_BY_NBFC(214L,"CO_ORIGINATION_EMAIL_CHECKER_RATIO_SENT_TO_BANK_FOR_APPROVAL_BY_NBFC",1),
	CO_ORIGINATION_SMS_CHECKER_RATIO_SENT_TO_BANK_FOR_APPROVAL_BY_NBFC(215L,"CO_ORIGINATION_SMS_CHECKER_RATIO_SENT_TO_BANK_FOR_APPROVAL_BY_NBFC",2),
	CO_ORIGINATION_SYS_CHECKER_RATIO_SENT_TO_BANK_FOR_APPROVAL_BY_NBFC(216L,"CO_ORIGINATION_SYS_CHECKER_RATIO_SENT_TO_BANK_FOR_APPROVAL_BY_NBFC",3),
	
	CO_ORIGINATION_EMAIL_CHECKER_RATIO_RESENT_TO_BANK_FOR_APPROVAL_BY_NBFC(217L,"CO_ORIGINATION_EMAIL_CHECKER_RATIO_RESENT_TO_BANK_FOR_APPROVAL_BY_NBFC",1),
	CO_ORIGINATION_SMS_CHECKER_RATIO_RESENT_TO_BANK_FOR_APPROVAL_BY_NBFC(218L,"CO_ORIGINATION_SMS_CHECKER_RATIO_RESENT_TO_BANK_FOR_APPROVAL_BY_NBFC",2),
	CO_ORIGINATION_SYS_CHECKER_RATIO_RESENT_TO_BANK_FOR_APPROVAL_BY_NBFC(219L,"CO_ORIGINATION_SYS_CHECKER_RATIO_RESENT_TO_BANK_FOR_APPROVAL_BY_NBFC",3),
	
	CO_ORIGINATION_EMAIL_CHECKER_RATIO_APPROVED_BY_BANK(220L,"CO_ORIGINATION_EMAIL_CHECKER_RATIO_APPROVED_BY_BANK",1),
	CO_ORIGINATION_SMS_CHECKER_RATIO_APPROVED_BY_BANK(221L,"CO_ORIGINATION_SMS_CHECKER_RATIO_APPROVED_BY_BANK",2),
	CO_ORIGINATION_SYS_CHECKER_RATIO_APPROVED_BY_BANK(222L,"CO_ORIGINATION_SYS_CHECKER_RATIO_APPROVED_BY_BANK",3),
	
	CO_ORIGINATION_EMAIL_MAKER_CHECKER_RATIO_SENT_BACK_BY_BANK(223L,"CO_ORIGINATION_EMAIL_MAKER_CHECKER_RATIO_SENT_BACK_BY_BANK",1),
	CO_ORIGINATION_SMS_MAKER_CHECKER_RATIO_SENT_BACK_BY_BANK(224L,"CO_ORIGINATION_SMS_MAKER_CHECKER_RATIO_SENT_BACK_BY_BANK",2),
	CO_ORIGINATION_SYS_MAKER_CHECKER_RATIO_SENT_BACK_BY_BANK(225L,"CO_ORIGINATION_SYS_MAKER_CHECKER_RATIO_SENT_BACK_BY_BANK",3),

	// ==================================================================================================================================
	
	CO_ORIGINATION_EMAIL_MAKER_AFTER_CHECKER_HOLDS_PROPOSAL(227L,"CO_ORIGINATION_EMAIL_MAKER_AFTER_CHECKER_HOLDS_PROPOSAL",1),
	CO_ORIGINATION_SMS_MAKER_AFTER_CHECKER_HOLDS_PROPOSAL(228L,"CO_ORIGINATION_SMS_MAKER_AFTER_CHECKER_HOLDS_PROPOSAL",2),
	CO_ORIGINATION_SYS_MAKER_AFTER_CHECKER_HOLDS_PROPOSAL(229L,"CO_ORIGINATION_SYS_MAKER_AFTER_CHECKER_HOLDS_PROPOSAL",3),
	
	CO_ORIGINATION_EMAIL_HO_CHECKER_REJECTS_PROPOSAL(230L,"CO_ORIGINATION_EMAIL_HO_CHECKER_REJECTS_PROPOSAL",1),
	CO_ORIGINATION_SMS_HO_CHECKER_REJECTS_PROPOSAL(231L,"CO_ORIGINATION_SMS_HO_CHECKER_REJECTS_PROPOSAL",2),
	CO_ORIGINATION_SYS_HO_CHECKER_REJECTS_PROPOSAL(232L,"CO_ORIGINATION_SYS_HO_CHECKER_REJECTS_PROPOSAL",3),
	
	CO_ORIGINATION_EMAIL_HO_CHECKER_SANCTIONED(234L,"CO_ORIGINATION_EMAIL_HO_CHECKER_SANCTIONED",1),
	CO_ORIGINATION_SMS_HO_CHECKER_SANCTIONED(235L,"CO_ORIGINATION_SMS_HO_CHECKER_SANCTIONED",2),
	CO_ORIGINATION_SYS_HO_CHECKER_SANCTIONED(236L,"CO_ORIGINATION_SYS_HO_CHECKER_SANCTIONED",3),
	
	CO_ORIGINATION_EMAIL_MAKER_AFTER_CHECKER_DISBURSED_PROPOSAL(237L,"CO_ORIGINATION_EMAIL_MAKER_AFTER_CHECKER_DISBURSED_PROPOSAL",1),
	CO_ORIGINATION_SMS_MAKER_AFTER_CHECKER_DISBURSED_PROPOSAL(238L,"CO_ORIGINATION_SMS_MAKER_AFTER_CHECKER_DISBURSED_PROPOSAL",2),
	CO_ORIGINATION_SYS_MAKER_AFTER_CHECKER_DISBURSED_PROPOSAL(239L,"CO_ORIGINATION_SYS_MAKER_AFTER_CHECKER_DISBURSED_PROPOSAL",3),
	
	CO_ORIGINATION_EMAIL_MAKER_CHECKER_WHEN_MAKER_CHECKER_SANCTIONED(240L,"CO_ORIGINATION_EMAIL_MAKER_CHECKER_WHEN_MAKER_CHECKER_SANCTIONED",1),
	CO_ORIGINATION_SMS_MAKER_CHECKER_WHEN_MAKER_CHECKER_SANCTIONED(241L,"CO_ORIGINATION_SMS_MAKER_CHECKER_WHEN_MAKER_CHECKER_SANCTIONED",2),
	CO_ORIGINATION_SYS_MAKER_CHECKER_WHEN_MAKER_CHECKER_SANCTIONED(242L,"CO_ORIGINATION_SYS_MAKER_CHECKER_WHEN_MAKER_CHECKER_SANCTIONED",3),
	
	CO_ORIGINATION_EMAIL_MAKER_CHECKER_AFTER_MAKER_CHECKER_DISBURSED_PROPOSAL(243L,"CO_ORIGINATION_EMAIL_MAKER_CHECKER_AFTER_MAKER_CHECKER_DISBURSED_PROPOSAL",1),
	CO_ORIGINATION_SMS_MAKER_CHECKER_AFTER_MAKER_CHECKER_DISBURSED_PROPOSAL(244L,"CO_ORIGINATION_SMS_MAKER_CHECKER_AFTER_MAKER_CHECKER_DISBURSED_PROPOSAL",2),
	CO_ORIGINATION_SYS_MAKER_CHECKER_AFTER_MAKER_CHECKER_DISBURSED_PROPOSAL(245L,"CO_ORIGINATION_SYS_MAKER_CHECKER_AFTER_MAKER_CHECKER_DISBURSED_PROPOSAL",3),
	
	CO_ORIGINATION_EMAIL_ALL_FP_AFTER_CHECKER_DISBURSED_PROPOSAL(246L,"CO_ORIGINATION_EMAIL_ALL_FP_AFTER_CHECKER_DISBURSED_PROPOSAL",1),
	CO_ORIGINATION_SMS_ALL_FP_AFTER_CHECKER_DISBURSED_PROPOSAL(247L,"CO_ORIGINATION_SMS_ALL_FP_AFTER_CHECKER_DISBURSED_PROPOSAL",2),
	CO_ORIGINATION_SYS_ALL_FP_AFTER_CHECKER_DISBURSED_PROPOSAL(248L,"CO_ORIGINATION_SYS_ALL_FP_AFTER_CHECKER_DISBURSED_PROPOSAL",3),
	
	CO_ORIGINATION_EMAIL_ALL_FP_WHEN_MAKER_CHECKER_SENT_BACK_SANCTION(250L,"CO_ORIGINATION_EMAIL_ALL_FP_WHEN_MAKER_CHECKER_SENT_BACK_SANCTION",1),
	CO_ORIGINATION_SMS_ALL_FP_WHEN_MAKER_CHECKER_SENT_BACK_SANCTION(251L,"CO_ORIGINATION_SMS_ALL_FP_WHEN_MAKER_CHECKER_SENT_BACK_SANCTION",2),
	CO_ORIGINATION_SYS_ALL_FP_WHEN_MAKER_CHECKER_SENT_BACK_SANCTION(252L,"CO_ORIGINATION_SYS_ALL_FP_WHEN_MAKER_CHECKER_SENT_BACK_SANCTION",3),
	
	CO_ORIGINATION_EMAIL_ALL_FP_WHEN_MAKER_CHECKER_RESENT_SANCTION(253L,"CO_ORIGINATION_EMAIL_ALL_FP_WHEN_MAKER_CHECKER_RESENT_SANCTION",1),
	CO_ORIGINATION_SMS_ALL_FP_WHEN_MAKER_CHECKER_RESENT_SANCTION(254L,"CO_ORIGINATION_SMS_ALL_FP_WHEN_MAKER_CHECKER_RESENT_SANCTION",2),
	CO_ORIGINATION_SYS_ALL_FP_WHEN_MAKER_CHECKER_RESENT_SANCTION(255L,"CO_ORIGINATION_SYS_ALL_FP_WHEN_MAKER_CHECKER_RESENT_SANCTION",3),
	
	CO_ORIGINATION_EMAIL_ALL_FP_WHEN_MAKER_CHECKER_SENT_BACK_DISBURSEMENT(259L,"CO_ORIGINATION_EMAIL_ALL_FP_WHEN_MAKER_CHECKER_SENT_BACK_DISBURSEMENT",1),
	CO_ORIGINATION_SMS_ALL_FP_WHEN_MAKER_CHECKER_SENT_BACK_DISBURSEMENT(260L,"CO_ORIGINATION_SMS_ALL_FP_WHEN_MAKER_CHECKER_SENT_BACK_DISBURSEMENT",2),
	CO_ORIGINATION_SYS_ALL_FP_WHEN_MAKER_CHECKER_SENT_BACK_DISBURSEMENT(261L,"CO_ORIGINATION_SYS_ALL_FP_WHEN_MAKER_CHECKER_SENT_BACK_DISBURSEMENT",3),
	
	CO_ORIGINATION_EMAIL_ALL_FP_WHEN_MAKER_CHECKER_RESENT_DISBURSEMENT(262L,"CO_ORIGINATION_EMAIL_ALL_FP_WHEN_MAKER_CHECKER_RESENT_DISBURSEMENT",1),
	CO_ORIGINATION_SMS_ALL_FP_WHEN_MAKER_CHECKER_RESENT_DISBURSEMENT(263L,"CO_ORIGINATION_SMS_ALL_FP_WHEN_MAKER_CHECKER_RESENT_DISBURSEMENT",2),
	CO_ORIGINATION_SYS_ALL_FP_WHEN_MAKER_CHECKER_RESENT_DISBURSEMENT(264L,"CO_ORIGINATION_SYS_ALL_FP_WHEN_MAKER_CHECKER_RESENT_DISBURSEMENT",3),
	
	CO_ORIGINATION_EMAIL_ALL_FP_WHEN_CHECKER_SANCTIONED(268L,"CO_ORIGINATION_EMAIL_ALL_FP_WHEN_CHECKER_SANCTIONED",1),
	CO_ORIGINATION_SMS_ALL_FP_WHEN_CHECKER_SANCTIONED(269L,"CO_ORIGINATION_SMS_ALL_FP_WHEN_CHECKER_SANCTIONED",2),
	CO_ORIGINATION_SYS_ALL_FP_WHEN_CHECKER_SANCTIONED(270L,"CO_ORIGINATION_SYS_ALL_FP_WHEN_CHECKER_SANCTIONED",3),
	
	CO_ORIGINATION_EMAIL_BRANCH_TRANSFER_TO_MAKER_WHEN_CHECKER_ASSIGN_PROPOSAL(274L,"CO_ORIGINATION_EMAIL_BRANCH_TRANSFER_TO_MAKER_WHEN_CHECKER_ASSIGN_PROPOSAL",1),
	CO_ORIGINATION_SMS_BRANCH_TRANSFER_TO_MAKER_WHEN_CHECKER_ASSIGN_PROPOSAL(275L,"CO_ORIGINATION_SMS_BRANCH_TRANSFER_TO_MAKER_WHEN_CHECKER_ASSIGN_PROPOSAL",2),
	CO_ORIGINATION_SYS_BRANCH_TRANSFER_TO_MAKER_WHEN_CHECKER_ASSIGN_PROPOSAL(276L,"CO_ORIGINATION_SYS_BRANCH_TRANSFER_TO_MAKER_WHEN_CHECKER_ASSIGN_PROPOSAL",3),
	
	CO_ORIGINATION_EMAIL_MAKER_CHECKER_HANDOFF_DIRSBURSEMENT_RESENT_APPROVAL(277L,"CO_ORIGINATION_EMAIL_MAKER_CHECKER_HANDOFF_DIRSBURSEMENT_RESENT_APPROVAL",1),
	CO_ORIGINATION_SMS_MAKER_CHECKER_HANDOFF_DIRSBURSEMENT_RESENT_APPROVAL(278L,"CO_ORIGINATION_SMS_MAKER_CHECKER_HANDOFF_DIRSBURSEMENT_RESENT_APPROVAL",2),
	CO_ORIGINATION_SYS_MAKER_CHECKER_HANDOFF_DIRSBURSEMENT_RESENT_APPROVAL(279L,"CO_ORIGINATION_SYS_MAKER_CHECKER_HANDOFF_DIRSBURSEMENT_RESENT_APPROVAL",3),
	
	// 122 is above
	
	//Hand off Request
	CO_ORIGINATION_SYS_CHECKER_MAKER_SENT_REQUEST_HANDOFF(256L,"CO_ORIGINATION_SYS_CHECKER_MAKER_SENT_REQUEST_HANDOFF",3),
	CO_ORIGINATION_SMS_CHECKER_MAKER_SENT_REQUEST_HANDOFF(257L,"CO_ORIGINATION_SMS_CHECKER_MAKER_SENT_REQUEST_HANDOFF",2),
	CO_ORIGINATION_EMAIL_CHECKER_MAKER_SENT_REQUEST_HANDOFF(258L,"CO_ORIGINATION_EMAIL_CHECKER_MAKER_SENT_REQUEST_HANDOFF",1),
	
	// Hand off request approved
	CO_ORIGINATION_EMAIL_CHECKER_MAKER_NBFC_MAKER_HAND_OFF_DISBURSEDMENT_REQUEST_APPROVED(267L,"CO_ORIGINATION_EMAIL_CHECKER_MAKER_NBFC_MAKER_HAND_OFF_DISBURSEDMENT_REQUEST_APPROVED",1),
	CO_ORIGINATION_SMS_CHECKER_MAKER_NBFC_MAKER_HAND_OFF_DISBURSEDMENT_APPROVED_BY_CHECKER(265L,"CO_ORIGINATION_SMS_CHECKER_MAKER_NBFC_MAKER_HAND_OFF_DISBURSEDMENT_APPROVED_BY_CHECKER",2),
	CO_ORIGINATION_SYS_CHECKER_MAKER_NBFC_MAKER_HAND_OFF_DISBURSEDMENT_REQUEST_APPROVED(266L,"CO_ORIGINATION_SYS_CHECKER_MAKER_NBFC_MAKER_HAND_OFF_DISBURSEDMENT_REQUEST_APPROVED",3),
	
	// Hand off request send back
	CO_ORIGINATION_EMAIL_FP_HANDOFF_REQUEST_SEND_BACK_BY_FP(271L,"CO_ORIGINATION_EMAIL_FP_HANDOFF_REQUEST_SEND_BACK_BY_FP",1),
	CO_ORIGINATION_SMS_FP_HANDOFF_REQUEST_SEND_BACK_BY_FP(272L,"CO_ORIGINATION_SMS_FP_HANDOFF_REQUEST_SEND_BACK_BY_FP",2),
	CO_ORIGINATION_SYS_FP_HANDOFF_REQUEST_SEND_BACK_BY_FP(273L,"CO_ORIGINATION_SYS_FP_HANDOFF_REQUEST_SEND_BACK_BY_FP",3),
	
	/** otp verify*/
	EMAIL_OTP_VERIFY_ACCOUNT(123L,"EMAIL_OTP_VERIFY_ACCOUNT",1),
	/** select sub product of retail loan*/
	PL_EMAIL_FS_PRODUCT_SELECTED_SUB_PRODUCT(124L,"PL_EMAIL_FS_PRODUCT_SELECTED_SUB_PRODUCT",1),
	SMS_FS_SUB_PRODUCT_SELECTED_FOR_RETAIL(125L,"SMS_FS_SUB_PRODUCT_SELECTED_FOR_RETAIL",2),
	
	/** gst specific*/
	BANK_SPECIFIC_GST_LINK(249L,"BANK_SPECIFIC_GST_LINK",1),
	
	//----------------------------------------------------------------------------------------------------------------
	//slab and servicing fees
	
	CO_ORIGINATION_EMAIL_CHECKER_WHEN_MAKER_SET_SLAB_AND_SEND_FOR_APPROVAL(281L,"CO_ORIGINATION_EMAIL_CHECKER_WHEN_MAKER_SET_SLAB_AND_SEND_FOR_APPROVAL",1),
	CO_ORIGINATION_SMS_CHECKER_WHEN_MAKER_SET_SLAB_AND_SEND_FOR_APPROVAL(282L,"CO_ORIGINATION_SMS_CHECKER_WHEN_MAKER_SET_SLAB_AND_SEND_FOR_APPROVAL",2),
	CO_ORIGINATION_SYS_CHECKER_WHEN_MAKER_SET_SLAB_AND_SEND_FOR_APPROVAL(283L,"CO_ORIGINATION_SYS_CHECKER_WHEN_MAKER_SET_SLAB_AND_SEND_FOR_APPROVAL",3),
	
	CO_ORIGINATION_EMAIL_CHECKER_WHEN_MAKER_RESENT_REVERTED_SLAB_FOR_APPROVAL(284L,"CO_ORIGINATION_EMAIL_CHECKER_WHEN_MAKER_RESENT_REVERTED_SLAB_FOR_APPROVAL",1),
	CO_ORIGINATION_SMS_CHECKER_WHEN_MAKER_RESENT_REVERTED_SLAB_FOR_APPROVAL(285L,"CO_ORIGINATION_SMS_CHECKER_WHEN_MAKER_RESENT_REVERTED_SLAB_FOR_APPROVAL",2),
	CO_ORIGINATION_SYS_CHECKER_WHEN_MAKER_RESENT_REVERTED_SLAB_FOR_APPROVAL(286L,"CO_ORIGINATION_SYS_CHECKER_WHEN_MAKER_RESENT_REVERTED_SLAB_FOR_APPROVAL",3),
	
	CO_ORIGINATION_EMAIL_CHECKER_WHEN_MAKER_EDITED_SLAB_AND_SEND_FOR_APPROVAL(287L,"CO_ORIGINATION_EMAIL_CHECKER_WHEN_MAKER_EDITED_SLAB_AND_SEND_FOR_APPROVAL",1),
	CO_ORIGINATION_SMS_CHECKER_WHEN_MAKER_EDITED_SLAB_AND_SEND_FOR_APPROVAL(288L,"CO_ORIGINATION_SMS_CHECKER_WHEN_MAKER_EDITED_SLAB_AND_SEND_FOR_APPROVAL",2),
	CO_ORIGINATION_SYS_CHECKER_WHEN_MAKER_EDITED_SLAB_AND_SEND_FOR_APPROVAL(289L,"CO_ORIGINATION_SYS_CHECKER_WHEN_MAKER_EDITED_SLAB_AND_SEND_FOR_APPROVAL",3),
	
	CO_ORIGINATION_EMAIL_MAKER_WHEN_CHECKER_SENT_BACK_SLAB(290L,"CO_ORIGINATION_EMAIL_MAKER_WHEN_CHECKER_SENT_BACK_SLAB",1),
	CO_ORIGINATION_SMS_MAKER_WHEN_CHECKER_SENT_BACK_SLAB(291L,"CO_ORIGINATION_SMS_MAKER_WHEN_CHECKER_SENT_BACK_SLAB",2),
	CO_ORIGINATION_SYS_MAKER_WHEN_CHECKER_SENT_BACK_SLAB(292L,"CO_ORIGINATION_SYS_MAKER_WHEN_CHECKER_SENT_BACK_SLAB",3),
	
	CO_ORIGINATION_EMAIL_MAKER_WHEN_CHECKER_APPROVES_SLAB(293L,"CO_ORIGINATION_EMAIL_MAKER_WHEN_CHECKER_APPROVES_SLAB",1),
	CO_ORIGINATION_SMS_MAKER_WHEN_CHECKER_APPROVES_SLAB(294L,"CO_ORIGINATION_SMS_MAKER_WHEN_CHECKER_APPROVES_SLAB",2),
	CO_ORIGINATION_SYS_MAKER_WHEN_CHECKER_APPROVES_SLAB(295L,"CO_ORIGINATION_SYS_MAKER_WHEN_CHECKER_APPROVES_SLAB",3),
	
	CO_ORIGINATION_EMAIL_CHECKER_WHEN_MAKER_SET_SERVICING_FEES_AND_SEND_FOR_APPROVAL(296L,"CO_ORIGINATION_EMAIL_CHECKER_WHEN_MAKER_SET_SERVICING_FEES_AND_SEND_FOR_APPROVAL",1),
	CO_ORIGINATION_SMS_CHECKER_WHEN_MAKER_SET_SERVICING_FEES_AND_SEND_FOR_APPROVAL(297L,"CO_ORIGINATION_SMS_CHECKER_WHEN_MAKER_SET_SERVICING_FEES_AND_SEND_FOR_APPROVAL",2),
	CO_ORIGINATION_SYS_CHECKER_WHEN_MAKER_SET_SERVICING_FEES_AND_SEND_FOR_APPROVAL(298L,"CO_ORIGINATION_SYS_CHECKER_WHEN_MAKER_SET_SERVICING_FEES_AND_SEND_FOR_APPROVAL",3),
	
	CO_ORIGINATION_EMAIL_CHECKER_WHEN_MAKER_RESENDS_REVERTED_SERVICING_FEES_FOR_APPROVAL(299L,"CO_ORIGINATION_EMAIL_CHECKER_WHEN_MAKER_RESENDS_REVERTED_SERVICING_FEES_FOR_APPROVAL",1),
	CO_ORIGINATION_SMS_CHECKER_WHEN_MAKER_RESENDS_REVERTED_SERVICING_FEES_FOR_APPROVAL(300L,"CO_ORIGINATION_SMS_CHECKER_WHEN_MAKER_RESENDS_REVERTED_SERVICING_FEES_FOR_APPROVAL",2),
	CO_ORIGINATION_SYS_CHECKER_WHEN_MAKER_RESENDS_REVERTED_SERVICING_FEES_FOR_APPROVAL(301L,"CO_ORIGINATION_SYS_CHECKER_WHEN_MAKER_RESENDS_REVERTED_SERVICING_FEES_FOR_APPROVAL",3),
	
	CO_ORIGINATION_EMAIL_CHECKER_WHEN_MAKER_EDITED_SERVICING_FEES_AND_SENT_FOR_APPROVAL(302L,"CO_ORIGINATION_EMAIL_CHECKER_WHEN_MAKER_EDITED_SERVICING_FEES_AND_SENT_FOR_APPROVAL",1),
	CO_ORIGINATION_SMS_CHECKER_WHEN_MAKER_EDITED_SERVICING_FEES_AND_SENT_FOR_APPROVAL(303L,"CO_ORIGINATION_SMS_CHECKER_WHEN_MAKER_EDITED_SERVICING_FEES_AND_SENT_FOR_APPROVAL",2),
	CO_ORIGINATION_SYS_CHECKER_WHEN_MAKER_EDITED_SERVICING_FEES_AND_SENT_FOR_APPROVAL(304L,"CO_ORIGINATION_SYS_CHECKER_WHEN_MAKER_EDITED_SERVICING_FEES_AND_SENT_FOR_APPROVAL",3),
	
	CO_ORIGINATION_EMAIL_MAKER_WHEN_CHECKER_REVERTS_BACK_SERVICING_FEES(305L,"CO_ORIGINATION_EMAIL_MAKER_WHEN_CHECKER_REVERTS_BACK_SERVICING_FEES",1),
	CO_ORIGINATION_SMS_MAKER_WHEN_CHECKER_REVERTS_BACK_SERVICING_FEES(306L,"CO_ORIGINATION_SMS_MAKER_WHEN_CHECKER_REVERTS_BACK_SERVICING_FEES",2),
	CO_ORIGINATION_SYS_MAKER_WHEN_CHECKER_REVERTS_BACK_SERVICING_FEES(307L,"CO_ORIGINATION_SYS_MAKER_WHEN_CHECKER_REVERTS_BACK_SERVICING_FEES",3),
	
	CO_ORIGINATION_EMAIL_MAKER_WHEN_CHECKER_APPROVED_SERVICING_FEES(308L,"CO_ORIGINATION_EMAIL_MAKER_WHEN_CHECKER_APPROVED_SERVICING_FEES",1),
	CO_ORIGINATION_SMS_MAKER_WHEN_CHECKER_APPROVED_SERVICING_FEES(309L,"CO_ORIGINATION_SMS_MAKER_WHEN_CHECKER_APPROVED_SERVICING_FEES",2),
	CO_ORIGINATION_SYS_MAKER_WHEN_CHECKER_APPROVED_SERVICING_FEES(310L,"CO_ORIGINATION_SYS_MAKER_WHEN_CHECKER_APPROVED_SERVICING_FEES",3),
	
	CO_ORIGINATION_EMAIL_ALL_FP_WHEN_BORROWER_APPLIED_MANUAL_PROCESSING(311L,"CO_ORIGINATION_EMAIL_ALL_FP_WHEN_BORROWER_APPLIED_MANUAL_PROCESSING",1),
	CO_ORIGINATION_SMS_ALL_FP_WHEN_BORROWER_APPLIED_MANUAL_PROCESSING(312L,"CO_ORIGINATION_SMS_ALL_FP_WHEN_BORROWER_APPLIED_MANUAL_PROCESSING",2),
	CO_ORIGINATION_SYS_ALL_FP_WHEN_BORROWER_APPLIED_MANUAL_PROCESSING(313L,"CO_ORIGINATION_SYS_ALL_FP_WHEN_BORROWER_APPLIED_MANUAL_PROCESSING",3),
	
	CO_ORIGINATION_EMAIL_ALL_HO_WHEN_BORROWER_APPLIED_MANUAL_PROCESSING(314L,"CO_ORIGINATION_EMAIL_ALL_HO_WHEN_BORROWER_APPLIED_MANUAL_PROCESSING",1),
	CO_ORIGINATION_SMS_ALL_HO_WHEN_BORROWER_APPLIED_MANUAL_PROCESSING(315L,"CO_ORIGINATION_SMS_ALL_HO_WHEN_BORROWER_APPLIED_MANUAL_PROCESSING",2),
	CO_ORIGINATION_SYS_ALL_HO_WHEN_BORROWER_APPLIED_MANUAL_PROCESSING(316L,"CO_ORIGINATION_SYS_ALL_HO_WHEN_BORROWER_APPLIED_MANUAL_PROCESSING",3),
	
	// Mudra Loan Mails
	ML_EMAIL_FS_PRODUCT_SELECTED_EXISTING(317L,"ML_EMAIL_FS_PRODUCT_SELECTED_EXISTING",1),
	
	ML_EMAIL_FS_WHEN_IN_ELIGIBLE(318L,"ML_EMAIL_FS_WHEN_IN_ELIGIBLE",1),
	ML_SMS_FS_WHEN_IN_ELIGIBLE(319L,"ML_SMS_FS_WHEN_IN_ELIGIBLE",2),
	ML_SYS_FS_WHEN_IN_ELIGIBLE(320L,"ML_SYS_FS_WHEN_IN_ELIGIBLE",3),
	
	ML_EMAIL_TO_FS_WHEN_MAKER_ACCEPT_PROPOSAL(321L,"ML_EMAIL_TO_FS_WHEN_MAKER_ACCEPT_PROPOSAL",1),
	ML_SMS_TO_FS_WHEN_MAKER_ACCEPT_PROPOSAL(322L,"ML_SMS_TO_FS_WHEN_MAKER_ACCEPT_PROPOSAL",2),
	
	ML_EMAIL_FS_WHEN_PROPOSAL_HOLD(323L,"ML_EMAIL_FS_WHEN_PROPOSAL_HOLD",1),
	ML_SMS_FS_WHEN_PROPOSAL_HOLD(324L,"ML_SMS_FS_WHEN_PROPOSAL_HOLD",2),
	ML_SYS_FS_WHEN_PROPOSAL_HOLD(325L,"ML_SYS_FS_WHEN_PROPOSAL_HOLD",3),
	
	ML_EMAIL_FS_WHEN_FP_REJECTS_PROPOSAL(326L,"ML_EMAIL_FS_WHEN_FP_REJECTS_PROPOSAL",1),
	ML_SMS_FS_WHEN_FP_REJECTS_PROPOSAL(327L,"ML_SMS_FS_WHEN_FP_REJECTS_PROPOSAL",2),
	ML_SYS_FS_WHEN_FP_REJECTS_PROPOSAL(328L,"ML_SYS_FS_WHEN_FP_REJECTS_PROPOSAL",3),
	
	ML_EMAIL_FS_WHEN_FP_SANCTIONED_PROPOSAL(329L,"ML_EMAIL_FS_WHEN_FP_SANCTIONED_PROPOSAL",1),
	ML_SMS_FS_WHEN_FP_SANCTIONED_PROPOSAL(330L,"ML_SMS_FS_WHEN_FP_SANCTIONED_PROPOSAL",2),
	ML_SYS_FS_WHEN_FP_SANCTIONED_PROPOSAL(331L,"ML_SYS_FS_WHEN_FP_SANCTIONED_PROPOSAL",3),
	
	ML_EMAIL_FS_WHEN_FP_DISBURSED_PROPOSAL(332L,"ML_EMAIL_FS_WHEN_FP_DISBURSED_PROPOSAL",1),
	ML_SMS_FS_WHEN_FP_DISBURSED_PROPOSAL(333L,"ML_SMS_FS_WHEN_FP_DISBURSED_PROPOSAL",2),
	ML_SYS_FS_WHEN_FP_DISBURSED_PROPOSAL(334L,"ML_SYS_FS_WHEN_FP_DISBURSED_PROPOSAL",3),
	
	ML_EMAIL_FS_WHEN_FP_BRANCH_TRANSFER(335L,"ML_EMAIL_FS_WHEN_FP_BRANCH_TRANSFER",1),
	ML_SMS_FS_WHEN_FP_BRANCH_TRANSFER(336L,"ML_SMS_FS_WHEN_FP_BRANCH_TRANSFER",2),
	ML_SYS_FS_WHEN_FP_BRANCH_TRANSFER(337L,"ML_SYS_FS_WHEN_FP_BRANCH_TRANSFER",3),
	
	ML_EMAIL_ADMIN_CHECKER_WHEN_ADMIN_MAKER_CREATES_PRODUCT(338L,"ML_EMAIL_ADMIN_CHECKER_WHEN_ADMIN_MAKER_CREATES_PRODUCT",1),
	ML_SMS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_CREATES_PRODUCT(339L,"ML_SMS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_CREATES_PRODUCT",2),
	ML_SYS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_CREATES_PRODUCT(340L,"ML_SYS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_CREATES_PRODUCT",3),
	
	ML_EMAIL_ADMIN_CHECKER_WHEN_ADMIN_MAKER_SET_SCORE(341L,"ML_EMAIL_ADMIN_CHECKER_WHEN_ADMIN_MAKER_SET_SCORE",1),
	ML_SMS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_SET_SCORE(342L,"ML_SMS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_SET_SCORE",2),
	ML_SYS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_SET_SCORE(343L,"ML_SYS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_SET_SCORE",3),
	
	ML_EMAIL_ADMIN_CHECKER_WHEN_ADMIN_MAKER_RESENDS_PRODUCT(344L,"ML_EMAIL_ADMIN_CHECKER_WHEN_ADMIN_MAKER_RESENDS_PRODUCT",1),
	ML_SMS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_RESENDS_PRODUCT(345L,"ML_SMS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_RESENDS_PRODUCT",2),
	ML_SYS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_RESENDS_PRODUCT(346L,"ML_SYS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_RESENDS_PRODUCT",3),
	
	ML_EMAIL_ADMIN_CHECKER_WHEN_ADMIN_MAKER_RESENDS_SCORING(347L,"ML_EMAIL_ADMIN_CHECKER_WHEN_ADMIN_MAKER_RESENDS_SCORING",1),
	ML_SMS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_RESENDS_SCORING(348L,"ML_SMS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_RESENDS_SCORING",2),
	ML_SYS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_RESENDS_SCORING(349L,"ML_SYS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_RESENDS_SCORING",3),
	
	ML_EMAIL_ADMIN_CHECKER_WHEN_ADMIN_MAKER_EDITED_SCORING(350L,"ML_EMAIL_ADMIN_CHECKER_WHEN_ADMIN_MAKER_EDITED_SCORING",1),
	ML_SMS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_EDITED_SCORING(351L,"ML_SMS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_EDITED_SCORING",2),
	ML_SYS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_EDITED_SCORING(352L,"ML_SYS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_EDITED_SCORING",3),
	
	ML_EMAIL_ADMIN_CHECKER_WHEN_ADMIN_MAKER_SET_EBLR(353L,"ML_EMAIL_ADMIN_CHECKER_WHEN_ADMIN_MAKER_SET_EBLR",1),
	ML_SMS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_SET_EBLR(354L,"ML_SMS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_SET_EBLR",2),
	ML_SYS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_SET_EBLR(355L,"ML_SYS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_SET_EBLR",3),
	
	ML_EMAIL_ADMIN_MAKER_WHEN_PRODUCT_APPROVED_BY_CHECKER(356L,"ML_EMAIL_ADMIN_MAKER_WHEN_PRODUCT_APPROVED_BY_CHECKER",1),
	ML_SMS_ADMIN_MAKER_WHEN_PRODUCT_APPROVED_BY_CHECKER(357L,"ML_SMS_ADMIN_MAKER_WHEN_PRODUCT_APPROVED_BY_CHECKER",2),
	ML_SYS_ADMIN_MAKER_WHEN_PRODUCT_APPROVED_BY_CHECKER(358L,"ML_SYS_ADMIN_MAKER_WHEN_PRODUCT_APPROVED_BY_CHECKER",3),
	
	ML_EMAIL_ADMIN_MAKER_WHEN_SCORING_APPROVED_BY_CHECKER(359L,"ML_EMAIL_ADMIN_MAKER_WHEN_SCORING_APPROVED_BY_CHECKER",1),
	ML_SMS_ADMIN_MAKER_WHEN_SCORING_APPROVED_BY_CHECKER(360L,"ML_SMS_ADMIN_MAKER_WHEN_SCORING_APPROVED_BY_CHECKER",2),
	ML_SYS_ADMIN_MAKER_WHEN_SCORING_APPROVED_BY_CHECKER(361L,"ML_SYS_ADMIN_MAKER_WHEN_SCORING_APPROVED_BY_CHECKER",3),
	
	ML_EMAIL_ADMIN_MAKER_WHEN_PRODUCT_REVERTED_BY_CHECKER(362L,"ML_EMAIL_ADMIN_MAKER_WHEN_PRODUCT_REVERTED_BY_CHECKER",1),
	ML_SMS_ADMIN_MAKER_WHEN_PRODUCT_REVERTED_BY_CHECKER(363L,"ML_SMS_ADMIN_MAKER_WHEN_PRODUCT_REVERTED_BY_CHECKER",2),
	ML_SYS_ADMIN_MAKER_WHEN_PRODUCT_REVERTED_BY_CHECKER(364L,"ML_SYS_ADMIN_MAKER_WHEN_PRODUCT_REVERTED_BY_CHECKER",3),
	
	ML_EMAIL_ADMIN_MAKER_WHEN_SCORING_REVERTED_BY_CHECKER(365L,"ML_EMAIL_ADMIN_MAKER_WHEN_SCORING_REVERTED_BY_CHECKER",1),
	ML_SMS_ADMIN_MAKER_WHEN_SCORING_REVERTED_BY_CHECKER(366L,"ML_SMS_ADMIN_MAKER_WHEN_SCORING_REVERTED_BY_CHECKER",2),
	ML_SYS_ADMIN_MAKER_WHEN_SCORING_REVERTED_BY_CHECKER(367L,"ML_SYS_ADMIN_MAKER_WHEN_SCORING_REVERTED_BY_CHECKER",3),
	
	ML_EMAIL_ADMIN_MAKER_WHEN_EBLR_APPROVED_BY_CHECKER(368L,"ML_EMAIL_ADMIN_MAKER_WHEN_EBLR_APPROVED_BY_CHECKER",1),
	ML_SMS_ADMIN_MAKER_WHEN_EBLR_APPROVED_BY_CHECKER(369L,"ML_SMS_ADMIN_MAKER_WHEN_EBLR_APPROVED_BY_CHECKER",2),
	ML_SYS_ADMIN_MAKER_WHEN_EBLR_APPROVED_BY_CHECKER(370L,"ML_SYS_ADMIN_MAKER_WHEN_EBLR_APPROVED_BY_CHECKER",3),
	
	ML_EMAIL_ALL_FP_WHEN_CHECKER_SANCTIONED(371L,"ML_EMAIL_ALL_FP_WHEN_CHECKER_SANCTIONED",1),
	ML_SMS_ALL_FP_WHEN_CHECKER_SANCTIONED(372L,"ML_SMS_ALL_FP_WHEN_CHECKER_SANCTIONED",2),
	ML_SYS_ALL_FP_WHEN_CHECKER_SANCTIONED(373L,"ML_SYS_ALL_FP_WHEN_CHECKER_SANCTIONED",3),
	
	ML_EMAIL_ALL_FP_WHEN_CHECKER_DISBURSED(374L,"ML_EMAIL_ALL_FP_WHEN_CHECKER_DISBURSED",1),
	ML_SMS_ALL_FP_WHEN_CHECKER_DISBURSED(375L,"ML_SMS_ALL_FP_WHEN_CHECKER_DISBURSED",2),
	ML_SYS_ALL_FP_WHEN_CHECKER_DISBURSED(376L,"ML_SYS_ALL_FP_WHEN_CHECKER_DISBURSED",3),
	
	ML_EMAIL_ALL_FP_WHEN_CHECKER_HOLD(377L,"ML_EMAIL_ALL_FP_WHEN_CHECKER_HOLD",1),
	ML_SMS_ALL_FP_WHEN_CHECKER_HOLD(378L,"ML_SMS_ALL_FP_WHEN_CHECKER_HOLD",2),
	ML_SYS_ALL_FP_WHEN_CHECKER_HOLD(379L,"ML_SYS_ALL_FP_WHEN_CHECKER_HOLD",3),
	
	ML_EMAIL_ALL_FP_WHEN_CHECKER_REJECT(380L,"ML_EMAIL_ALL_FP_WHEN_CHECKER_REJECT",1),
	ML_SMS_ALL_FP_WHEN_CHECKER_REJECT(381L,"ML_SMS_ALL_FP_WHEN_CHECKER_REJECT",2),
	ML_SYS_ALL_FP_WHEN_CHECKER_REJECT(382L,"ML_SYS_ALL_FP_WHEN_CHECKER_REJECT",3),
	
	DFS_WELCOME_EMAIL_FOR_DEALER(384L,"DFS_WELCOME_EMAIL_FOR_DEALER",1),
	
	ML_EMAIL_ADMIN_CHECKER_WHEN_ADMIN_MAKER_SET_MCLR(385L,"ML_EMAIL_ADMIN_CHECKER_WHEN_ADMIN_MAKER_SET_MCLR",1),
	ML_SMS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_SET_MCLR(386L,"ML_SMS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_SET_MCLR",2),
	ML_SYS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_SET_MCLR(387L,"ML_SYS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_SET_MCLR",3),
	
	ML_EMAIL_ADMIN_MAKER_WHEN_MCLR_APPROVED_BY_CHECKER(388L,"ML_EMAIL_ADMIN_MAKER_WHEN_MCLR_APPROVED_BY_CHECKER",1),
	ML_SMS_ADMIN_MAKER_WHEN_MCLR_APPROVED_BY_CHECKER(389L,"ML_SMS_ADMIN_MAKER_WHEN_MCLR_APPROVED_BY_CHECKER",2),
	ML_SYS_ADMIN_MAKER_WHEN_MCLR_APPROVED_BY_CHECKER(390L,"ML_SYS_ADMIN_MAKER_WHEN_MCLR_APPROVED_BY_CHECKER",3),
	
	DFS_EMAIL_FS_PRODUCT_SELECTED_EXISTING(391L,"DFS_EMAIL_FS_PRODUCT_SELECTED_EXISTING",1),
	DFS_WELCOME_EMAIL_FOR_EXISITNG_USER_DEALER(392L,"DFS_WELCOME_EMAIL_FOR_EXISITNG_USER_DEALER",1),
	
	PAYMENT_GATEWAY_ISSUE_MAIL(393L , "PAYMENT_GATEWAY_ISSUE_MAIL", 1),

	// Odop Loan Mails
	ODOP_COMMON_INPRINCIPLE_LETTER(383L,"ODOP_COMMON_INPRINCIPLE_LETTER",1),
	ODOP_EMAIL_FS_PRODUCT_SELECTED_EXISTING(400L,"ODOP_EMAIL_FS_PRODUCT_SELECTED_EXISTING",1),
	ODOP_EMAIL_FS_WHEN_IN_ELIGIBLE(401L,"ODOP_EMAIL_FS_WHEN_IN_ELIGIBLE",1),
	ODOP_EMAIL_FS_WHEN_PROPOSAL_HOLD(402L,"ODOP_EMAIL_FS_WHEN_PROPOSAL_HOLD",1),
	ODOP_SMS_FS_WHEN_PROPOSAL_HOLD(409L,"ODOP_SMS_FS_WHEN_PROPOSAL_HOLD",2),
	ODOP_SYS_FS_WHEN_PROPOSAL_HOLD(410L,"ODOP_SYS_FS_WHEN_PROPOSAL_HOLD",3),
	ODOP_EMAIL_FS_WHEN_FP_REJECTS_PROPOSAL(403L,"ODOP_EMAIL_FS_WHEN_FP_REJECTS_PROPOSAL",1),
	ODOP_SMS_FS_WHEN_FP_REJECTS_PROPOSAL(411L,"ODOP_SMS_FS_WHEN_FP_REJECTS_PROPOSAL",2),
	ODOP_SYS_FS_WHEN_FP_REJECTS_PROPOSAL(412L,"ODOP_SYS_FS_WHEN_FP_REJECTS_PROPOSAL",3),
	ODOP_EMAIL_FS_WHEN_FP_SANCTIONED_PROPOSAL(404L,"ODOP_EMAIL_FS_WHEN_FP_SANCTIONED_PROPOSAL",1),
	ODOP_SMS_FS_WHEN_FP_SANCTIONED_PROPOSAL(413L,"ODOP_SMS_FS_WHEN_FP_SANCTIONED_PROPOSAL",2),
	ODOP_SYS_FS_WHEN_FP_SANCTIONED_PROPOSAL(414L,"ODOP_SYS_FS_WHEN_FP_SANCTIONED_PROPOSAL",3),
	ODOP_EMAIL_FS_WHEN_FP_DISBURSED_PROPOSAL(405L,"ODOP_EMAIL_FS_WHEN_FP_DISBURSED_PROPOSAL",1),
	ODOP_SMS_FS_WHEN_FP_DISBURSED_PROPOSAL(415L,"ODOP_SMS_FS_WHEN_FP_DISBURSED_PROPOSAL",2),
	ODOP_SYS_FS_WHEN_FP_DISBURSED_PROPOSAL(416L,"ODOP_SYS_FS_WHEN_FP_DISBURSED_PROPOSAL",3),
	ODOP_EMAIL_FS_WHEN_FP_BRANCH_TRANSFER(406L,"ODOP_EMAIL_FS_WHEN_FP_BRANCH_TRANSFER",1),
	ODOP_SMS_FS_WHEN_FP_BRANCH_TRANSFER(417L,"ODOP_SMS_FS_WHEN_FP_BRANCH_TRANSFER",2),
	ODOP_SYS_FS_WHEN_FP_BRANCH_TRANSFER(418L,"ODOP_SYS_FS_WHEN_FP_BRANCH_TRANSFER",3),
	ODOP_SMS_FS_WHEN_IN_ELIGIBLE(407L,"ODOP_SMS_FS_WHEN_IN_ELIGIBLE",2),
	ODOP_SYS_FS_WHEN_IN_ELIGIBLE(408L,"ODOP_SYS_FS_WHEN_IN_ELIGIBLE",3),
	ODOP_EMAIL_ADMIN_MAKER_WHEN_PRODUCT_APPROVED_BY_CHECKER(419L,"ODOP_EMAIL_ADMIN_MAKER_WHEN_PRODUCT_APPROVED_BY_CHECKER",1),
	ODOP_SMS_ADMIN_MAKER_WHEN_PRODUCT_APPROVED_BY_CHECKER(420L,"ODOP_SMS_ADMIN_MAKER_WHEN_PRODUCT_APPROVED_BY_CHECKER",2),
	ODOP_SYS_ADMIN_MAKER_WHEN_PRODUCT_APPROVED_BY_CHECKER(421L,"ODOP_SYS_ADMIN_MAKER_WHEN_PRODUCT_APPROVED_BY_CHECKER",3),
	
	ODOP_EMAIL_ADMIN_MAKER_WHEN_SCORING_APPROVED_BY_CHECKER(422L,"ODOP_EMAIL_ADMIN_MAKER_WHEN_SCORING_APPROVED_BY_CHECKER",1),
	ODOP_SMS_ADMIN_MAKER_WHEN_SCORING_APPROVED_BY_CHECKER(423L,"ODOP_SMS_ADMIN_MAKER_WHEN_SCORING_APPROVED_BY_CHECKER",2),
	ODOP_SYS_ADMIN_MAKER_WHEN_SCORING_APPROVED_BY_CHECKER(424L,"ODOP_SYS_ADMIN_MAKER_WHEN_SCORING_APPROVED_BY_CHECKER",3),
	ODOP_EMAIL_ADMIN_MAKER_WHEN_PRODUCT_REVERTED_BY_CHECKER(425L,"ODOP_EMAIL_ADMIN_MAKER_WHEN_PRODUCT_REVERTED_BY_CHECKER",1),
	ODOP_SMS_ADMIN_MAKER_WHEN_PRODUCT_REVERTED_BY_CHECKER(426L,"ODOP_SMS_ADMIN_MAKER_WHEN_PRODUCT_REVERTED_BY_CHECKER",2),
	ODOP_SYS_ADMIN_MAKER_WHEN_PRODUCT_REVERTED_BY_CHECKER(427L,"ODOP_SYS_ADMIN_MAKER_WHEN_PRODUCT_REVERTED_BY_CHECKER",3),
	ODOP_EMAIL_ADMIN_MAKER_WHEN_SCORING_REVERTED_BY_CHECKER(428L,"ODOP_EMAIL_ADMIN_MAKER_WHEN_SCORING_REVERTED_BY_CHECKER",1),
	ODOP_SMS_ADMIN_MAKER_WHEN_SCORING_REVERTED_BY_CHECKER(429L,"ODOP_SMS_ADMIN_MAKER_WHEN_SCORING_REVERTED_BY_CHECKER",2),
	ODOP_SYS_ADMIN_MAKER_WHEN_SCORING_REVERTED_BY_CHECKER(430L,"ODOP_SYS_ADMIN_MAKER_WHEN_SCORING_REVERTED_BY_CHECKER",3),
	ODOP_EMAIL_ADMIN_CHECKER_WHEN_ADMIN_MAKER_CREATES_PRODUCT(431L,"ODOP_EMAIL_ADMIN_CHECKER_WHEN_ADMIN_MAKER_CREATES_PRODUCT",1),
	ODOP_SMS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_CREATES_PRODUCT(432L,"ODOP_SMS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_CREATES_PRODUCT",2),
	ODOP_SYS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_CREATES_PRODUCT(433L,"ODOP_SYS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_CREATES_PRODUCT",3),
	ODOP_EMAIL_ADMIN_CHECKER_WHEN_ADMIN_MAKER_SET_SCORE(434L,"ODOP_EMAIL_ADMIN_CHECKER_WHEN_ADMIN_MAKER_SET_SCORE",1),
	ODOP_SMS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_SET_SCORE(435L,"ODOP_SMS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_SET_SCORE",2),
	ODOP_SYS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_SET_SCORE(436L,"ODOP_SYS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_SET_SCORE",3),
	ODOP_EMAIL_ADMIN_CHECKER_WHEN_ADMIN_MAKER_RESENDS_PRODUCT(437L,"ODOP_EMAIL_ADMIN_CHECKER_WHEN_ADMIN_MAKER_RESENDS_PRODUCT",1),
	ODOP_SMS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_RESENDS_PRODUCT(438L,"ODOP_SMS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_RESENDS_PRODUCT",2),
	ODOP_SYS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_RESENDS_PRODUCT(439L,"ODOP_SYS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_RESENDS_PRODUCT",3),
	ODOP_EMAIL_ADMIN_CHECKER_WHEN_ADMIN_MAKER_RESENDS_SCORING(440L,"ODOP_EMAIL_ADMIN_CHECKER_WHEN_ADMIN_MAKER_RESENDS_SCORING",1),
	ODOP_SMS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_RESENDS_SCORING(441L,"ODOP_SMS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_RESENDS_SCORING",2),
	ODOP_SYS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_RESENDS_SCORING(442L,"ODOP_SYS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_RESENDS_SCORING",3),
	ODOP_EMAIL_ADMIN_CHECKER_WHEN_ADMIN_MAKER_EDITED_SCORING(443L,"ODOP_EMAIL_ADMIN_CHECKER_WHEN_ADMIN_MAKER_EDITED_SCORING",1),
	ODOP_SMS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_EDITED_SCORING(444L,"ODOP_SMS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_EDITED_SCORING",2),
	ODOP_SYS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_EDITED_SCORING(445L,"ODOP_SYS_ADMIN_CHECKER_WHEN_ADMIN_MAKER_EDITED_SCORING",3),

	ODOP_EMAIL_ALL_FP_WHEN_CHECKER_SANCTIONED(446L,"ODOP_EMAIL_ALL_FP_WHEN_CHECKER_SANCTIONED",1),
	ODOP_SMS_ALL_FP_WHEN_CHECKER_SANCTIONED(447L,"ODOP_SMS_ALL_FP_WHEN_CHECKER_SANCTIONED",2),
	ODOP_SYS_ALL_FP_WHEN_CHECKER_SANCTIONED(448L,"ODOP_SYS_ALL_FP_WHEN_CHECKER_SANCTIONED",3),
	ODOP_EMAIL_ALL_FP_WHEN_CHECKER_HOLD(449L,"ODOP_EMAIL_ALL_FP_WHEN_CHECKER_HOLD",1),
	ODOP_SMS_ALL_FP_WHEN_CHECKER_HOLD(450L,"ODOP_SMS_ALL_FP_WHEN_CHECKER_HOLD",2),
	ODOP_SYS_ALL_FP_WHEN_CHECKER_HOLD(451L,"ODOP_SYS_ALL_FP_WHEN_CHECKER_HOLD",3),
	ODOP_EMAIL_ALL_FP_WHEN_CHECKER_REJECT(452L,"ODOP_EMAIL_ALL_FP_WHEN_CHECKER_REJECT",1),
	ODOP_SMS_ALL_FP_WHEN_CHECKER_REJECT(453L,"ODOP_SMS_ALL_FP_WHEN_CHECKER_REJECT",2),
	ODOP_SYS_ALL_FP_WHEN_CHECKER_REJECT(454L,"ODOP_SYS_ALL_FP_WHEN_CHECKER_REJECT",3),
	ODOP_EMAIL_ALL_FP_WHEN_CHECKER_DISBURSED(455L,"ODOP_EMAIL_ALL_FP_WHEN_CHECKER_DISBURSED",1),
	ODOP_SMS_ALL_FP_WHEN_CHECKER_DISBURSED(456L,"ODOP_SMS_ALL_FP_WHEN_CHECKER_DISBURSED",2),
	ODOP_SYS_ALL_FP_WHEN_CHECKER_DISBURSED(457L,"ODOP_SYS_ALL_FP_WHEN_CHECKER_DISBURSED",3),

	// ALDFS 
	ALDFS_MAIL_TO_CUSTOMER_WHEN_REGISTERED_BY_DEALER(459L,"ALDFS_MAIL_TO_CUSTOMER_WHEN_REGISTERED_BY_DEALER",1),
	ALDFS_SMS_TO_CUSTOMER_WHEN_REGISTERED_BY_DEALER(460L,"ALDFS_SMS_TO_CUSTOMER_WHEN_REGISTERED_BY_DEALER",2),
	
	ALDFS_MAIL_TO_DEALER_WHEN_REGISTERED_BY_BRANCH(461L,"ALDFS_MAIL_TO_DEALER_WHEN_REGISTERED_BY_BRANCH",1),
	ALDFS_SMS_TO_DEALER_WHEN_REGISTERED_BY_BRANCH(462L,"ALDFS_SMS_TO_DEALER_WHEN_REGISTERED_BY_BRANCH",2),
	;

	Long masterId;
	String notificationName;
	Integer notificationType;
	
	NotificationMasterAlias(Long masterId,String notiName,Integer notiType){
		this.masterId = masterId;
		this.notificationName=notiName;
		this.notificationType=notiType;
	}
	
	public Long getMasterId(){
		return this.masterId;
	}
	
	public String getNotificationName() {
		return this.notificationName;
	}
	public Integer getNotiTypeId(){
		return this.notificationType;
	}
	
}
