//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.24 at 11:16:05 AM IST 
//


package com.opl.mudra.api.fraudanalytics.model.response;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MatchSchemeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MatchSchemeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Scheme" type="{}SchemeIDType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="schemeCount" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MatchSchemeType", propOrder = {
    "scheme"
})
public class MatchSchemeType {

    @XmlElement(name = "Scheme", required = true)
    protected List<SchemeIDType> scheme;
    @XmlAttribute(name = "schemeCount", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger schemeCount;

    /**
     * Gets the value of the scheme property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scheme property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScheme().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SchemeIDType }
     * 
     * 
     */
    public List<SchemeIDType> getScheme() {
        if (scheme == null) {
            scheme = new ArrayList<SchemeIDType>();
        }
        return this.scheme;
    }

    /**
     * Gets the value of the schemeCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSchemeCount() {
        return schemeCount;
    }

    /**
     * Sets the value of the schemeCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSchemeCount(BigInteger value) {
        this.schemeCount = value;
    }

}
