package com.opl.mudra.api.oneform.enums;

public enum  BankListMfi {

    ABHYUDAYA_COOPERATIVE_BANK_LIMITED("ABHYUDAYA COOPERATIVE BANK LIMITED","1","ABHYUDAYA COOPERATIVE BANK LIMITED"),
    ABU_DHABI_COMMERCIAL_BANK("ABU DHABI COMMERCIAL BANK","2","ABU DHABI COMMERCIAL BANK"),
    AHMEDABAD_MERCANTILE_COOPERATIVE_BANK("AHMEDABAD MERCANTILE COOPERATIVE BANK","3","AHMEDABAD MERCANTILE COOPERATIVE BANK"),
    AKOLA_JANATA_COMMERCIAL_COOPERATIVE_BANK("AKOLA JANATA COMMERCIAL COOPERATIVE BANK","4","AKOLA JANATA COMMERCIAL COOPERATIVE BANK"),
    ALLAHABAD_BANK("ALLAHABAD BANK","5","ALLAHABAD BANK"),
    ALMORA_URBAN_COOPERATIVE_BANK_LIMITED("ALMORA URBAN COOPERATIVE BANK LIMITED","6","ALMORA URBAN COOPERATIVE BANK LIMITED"),
    ANDHRA_BANK("ANDHRA BANK","7","ANDHRA BANK"),
    ANDHRA_PRAGATHI_GRAMEENA_BANK("ANDHRA PRAGATHI GRAMEENA BANK","8","ANDHRA PRAGATHI GRAMEENA BANK"),
    APNA_SAHAKARI_BANK_LIMITED("APNA SAHAKARI BANK LIMITED","9","APNA SAHAKARI BANK LIMITED"),
    AUSTRALIA_AND_NEW_ZEALAND_BANKING_GROUP_LIMITED("AUSTRALIA AND NEW ZEALAND BANKING GROUP LIMITED","10","AUSTRALIA AND NEW ZEALAND BANKING GROUP LIMITED"),
    AXIS_BANK("AXIS BANK","11","AXIS BANK"),
    B_N_P_PARIBAS("B N P PARIBAS","12","B N P PARIBAS"),
    BANK_INTERNASIONAL_INDONESIA("BANK INTERNASIONAL INDONESIA","13","BANK INTERNASIONAL INDONESIA"),
    BANK_OF_AMERICA("BANK OF AMERICA","14","BANK OF AMERICA"),
    BANK_OF_BAHARAIN_AND_KUWAIT_BSC("BANK OF BAHARAIN AND KUWAIT BSC","15","BANK OF BAHARAIN AND KUWAIT BSC"),
    BANK_OF_BARODA("BANK OF BARODA","16","BANK OF BARODA"),
    BANK_OF_CEYLON("BANK OF CEYLON","17","BANK OF CEYLON"),
    BANK_OF_INDIA("BANK OF INDIA","18","BANK OF INDIA"),
    BANK_OF_MAHARASHTRA("BANK OF MAHARASHTRA","19","BANK OF MAHARASHTRA"),
    BANK_OF_TOKYO_MITSUBISHI_LIMITED("BANK OF TOKYO MITSUBISHI LIMITED","20","BANK OF TOKYO MITSUBISHI LIMITED"),
    BARCLAYS_BANK("BARCLAYS BANK","21","BARCLAYS BANK"),
    BASSEIN_CATHOLIC_COOPERATIVE_BANK_LIMITED("BASSEIN CATHOLIC COOPERATIVE BANK LIMITED","22","BASSEIN CATHOLIC COOPERATIVE BANK LIMITED"),
    BHARAT_COOPERATIVE_BANK_MUMBAI_LIMITED("BHARAT COOPERATIVE BANK MUMBAI LIMITED","23","BHARAT COOPERATIVE BANK MUMBAI LIMITED"),
    BHARATIYA_MAHILA_BANK_LIMITED("BHARATIYA MAHILA BANK LIMITED","24","BHARATIYA MAHILA BANK LIMITED"),
    CANARA_BANK("CANARA BANK","25","CANARA BANK"),
    CAPITAL_LOCAL_AREA_BANK_LIMITED("CAPITAL LOCAL AREA BANK LIMITED","26","CAPITAL LOCAL AREA BANK LIMITED"),
    CATHOLIC_SYRIAN_BANK_LIMITED("CATHOLIC SYRIAN BANK LIMITED","27","CATHOLIC SYRIAN BANK LIMITED"),
    CENTRAL_BANK_OF_INDIA("CENTRAL BANK OF INDIA","28","CENTRAL BANK OF INDIA"),
    CHINATRUST_COMMERCIAL_BANK_LIMITED("CHINATRUST COMMERCIAL BANK LIMITED","29","CHINATRUST COMMERCIAL BANK LIMITED"),
    CITI_BANK("CITI BANK","30","CITI BANK"),
    CITIZEN_CREDIT_COOPERATIVE_BANK_LIMITED("CITIZEN CREDIT COOPERATIVE BANK LIMITED","31","CITIZEN CREDIT COOPERATIVE BANK LIMITED"),
    CITY_UNION_BANK_LIMITED("CITY UNION BANK LIMITED","32","CITY UNION BANK LIMITED"),
    COMMONWEALTH_BANK_OF_AUSTRALIA("COMMONWEALTH BANK OF AUSTRALIA","33","COMMONWEALTH BANK OF AUSTRALIA"),
    CORPORATION_BANK("CORPORATION BANK","34","CORPORATION BANK"),
    CREDIT_AGRICOLE_CORPORATE_AND_INVESTMENT_BANK_CALYON_BANK("CREDIT AGRICOLE CORPORATE AND INVESTMENT BANK CALYON BANK","35","CREDIT AGRICOLE CORPORATE AND INVESTMENT BANK CALYON BANK"),
    CREDIT_SUISEE_AG("CREDIT SUISEE AG","36","CREDIT SUISEE AG"),
    DCB_BANK_LIMITED("DCB BANK LIMITED","37","DCB BANK LIMITED"),
    DENA_BANK("DENA BANK","38","DENA BANK"),
    DEPOSIT_INSURANCE_AND_CREDIT_GUARANTEE_CORPORATION("DEPOSIT INSURANCE AND CREDIT GUARANTEE CORPORATION","39","DEPOSIT INSURANCE AND CREDIT GUARANTEE CORPORATION"),
    DEUSTCHE_BANK("DEUSTCHE BANK","40","DEUSTCHE BANK"),
    DEVELOPMENT_BANK_OF_SINGAPORE("DEVELOPMENT BANK OF SINGAPORE","41","DEVELOPMENT BANK OF SINGAPORE"),
    DHANALAKSHMI_BANK("DHANALAKSHMI BANK","42","DHANALAKSHMI BANK"),
    DOMBIVLI_NAGARI_SAHAKARI_BANK_LIMITED("DOMBIVLI NAGARI SAHAKARI BANK LIMITED","43","DOMBIVLI NAGARI SAHAKARI BANK LIMITED"),
    FEDERAL_BANK("FEDERAL BANK","44","FEDERAL BANK"),
    FIRSTRAND_BANK_LIMITED("FIRSTRAND BANK LIMITED","45","FIRSTRAND BANK LIMITED"),
    G_P_PARSIK_BANK("G P PARSIK BANK","46","G P PARSIK BANK"),
    GURGAON_GRAMIN_BANK("GURGAON GRAMIN BANK","47","GURGAON GRAMIN BANK"),
    HDFC_BANK("HDFC BANK","48","HDFC BANK"),
    HSBC_BANK("HSBC BANK","49","HSBC BANK"),
    HSBC_BANK_OMAN_SAOG("HSBC BANK OMAN SAOG","50","HSBC BANK OMAN SAOG"),
    ICICI_BANK_LIMITED("ICICI BANK LIMITED","51","ICICI BANK LIMITED"),
    IDBI_BANK("IDBI BANK","52","IDBI BANK"),
    INDIAN_BANK("INDIAN BANK","53","INDIAN BANK"),
    INDIAN_OVERSEAS_BANK("INDIAN OVERSEAS BANK","54","INDIAN OVERSEAS BANK"),
    INDUSIND_BANK("INDUSIND BANK","55","INDUSIND BANK"),
    INDUSTRIAL_AND_COMMERCIAL_BANK_OF_CHINA_LIMITED("INDUSTRIAL AND COMMERCIAL BANK OF CHINA LIMITED","56","INDUSTRIAL AND COMMERCIAL BANK OF CHINA LIMITED"),
    ING_VYSYA_BANK("ING VYSYA BANK","57","ING VYSYA BANK"),
    JALGAON_JANATA_SAHAKARI_BANK_LIMITED("JALGAON JANATA SAHAKARI BANK LIMITED","58","JALGAON JANATA SAHAKARI BANK LIMITED"),
    JAMMU_AND_KASHMIR_BANK_LIMITED("JAMMU AND KASHMIR BANK LIMITED","59","JAMMU AND KASHMIR BANK LIMITED"),
    JANAKALYAN_SAHAKARI_BANK_LIMITED("JANAKALYAN SAHAKARI BANK LIMITED","60","JANAKALYAN SAHAKARI BANK LIMITED"),
    JANASEVA_SAHAKARI_BANK_BORIVLI_LIMITED("JANASEVA SAHAKARI BANK BORIVLI LIMITED","61","JANASEVA SAHAKARI BANK BORIVLI LIMITED"),
    JANASEVA_SAHAKARI_BANK_LIMITED("JANASEVA SAHAKARI BANK LIMITED","62","JANASEVA SAHAKARI BANK LIMITED"),
    JANATA_SAHAKARI_BANK_LIMITED("JANATA SAHAKARI BANK LIMITED","63","JANATA SAHAKARI BANK LIMITED"),
    JP_MORGAN_BANK("JP MORGAN BANK","64","JP MORGAN BANK"),
    KALLAPPANNA_AWADE_ICHALKARANJI_JANATA_SAHAKARI_BANK_LIMITED("KALLAPPANNA AWADE ICHALKARANJI JANATA SAHAKARI BANK LIMITED","65","KALLAPPANNA AWADE ICHALKARANJI JANATA SAHAKARI BANK LIMITED"),
    KALUPUR_COMMERCIAL_COOPERATIVE_BANK("KALUPUR COMMERCIAL COOPERATIVE BANK","66","KALUPUR COMMERCIAL COOPERATIVE BANK"),
    KALYAN_JANATA_SAHAKARI_BANK("KALYAN JANATA SAHAKARI BANK","67","KALYAN JANATA SAHAKARI BANK"),
    KAPOL_COOPERATIVE_BANK_LIMITED("KAPOL COOPERATIVE BANK LIMITED","68","KAPOL COOPERATIVE BANK LIMITED"),
    KARNATAKA_BANK_LIMITED("KARNATAKA BANK LIMITED","69","KARNATAKA BANK LIMITED"),
    KARNATAKA_VIKAS_GRAMEENA_BANK("KARNATAKA VIKAS GRAMEENA BANK","70","KARNATAKA VIKAS GRAMEENA BANK"),
    KARUR_VYSYA_BANK("KARUR VYSYA BANK","71","KARUR VYSYA BANK"),
    KERALA_GRAMIN_BANK("KERALA GRAMIN BANK","72","KERALA GRAMIN BANK"),
    KOTAK_MAHINDRA_BANK_LIMITED("KOTAK MAHINDRA BANK LIMITED","73","KOTAK MAHINDRA BANK LIMITED"),
    LAXMI_VILAS_BANK("LAXMI VILAS BANK","74","LAXMI VILAS BANK"),
    MAHANAGAR_COOPERATIVE_BANK("MAHANAGAR COOPERATIVE BANK","75","MAHANAGAR COOPERATIVE BANK"),
    MAHARASHTRA_STATE_COOPERATIVE_BANK("MAHARASHTRA STATE COOPERATIVE BANK","76","MAHARASHTRA STATE COOPERATIVE BANK"),
    MASHREQBANK_PSC("MASHREQBANK PSC","77","MASHREQBANK PSC"),
    MIZUHO_CORPORATE_BANK_LIMITED("MIZUHO CORPORATE BANK LIMITED","78","MIZUHO CORPORATE BANK LIMITED"),
    NAGAR_URBAN_CO_OPERATIVE_BANK("NAGAR URBAN CO OPERATIVE BANK","79","NAGAR URBAN CO OPERATIVE BANK"),
    NAGPUR_NAGARIK_SAHAKARI_BANK_LIMITED("NAGPUR NAGARIK SAHAKARI BANK LIMITED","80","NAGPUR NAGARIK SAHAKARI BANK LIMITED"),
    NATIONAL_AUSTRALIA_BANK_LIMITED("NATIONAL AUSTRALIA BANK LIMITED","81","NATIONAL AUSTRALIA BANK LIMITED"),
    NEW_INDIA_COOPERATIVE_BANK_LIMITED("NEW INDIA COOPERATIVE BANK LIMITED","82","NEW INDIA COOPERATIVE BANK LIMITED"),
    NKGSB_COOPERATIVE_BANK_LIMITED("NKGSB COOPERATIVE BANK LIMITED","83","NKGSB COOPERATIVE BANK LIMITED"),
    NORTH_MALABAR_GRAMIN_BANK("NORTH MALABAR GRAMIN BANK","84","NORTH MALABAR GRAMIN BANK"),
    NUTAN_NAGARIK_SAHAKARI_BANK_LIMITED("NUTAN NAGARIK SAHAKARI BANK LIMITED","85","NUTAN NAGARIK SAHAKARI BANK LIMITED"),
    OMAN_INTERNATIONAL_BANK_SAOG("OMAN INTERNATIONAL BANK SAOG","86","OMAN INTERNATIONAL BANK SAOG"),
    ORIENTAL_BANK_OF_COMMERCE("ORIENTAL BANK OF COMMERCE","87","ORIENTAL BANK OF COMMERCE"),
    PRAGATHI_KRISHNA_GRAMIN_BANK("PRAGATHI KRISHNA GRAMIN BANK","88","PRAGATHI KRISHNA GRAMIN BANK"),
    PRATHAMA_BANK("PRATHAMA BANK","89","PRATHAMA BANK"),
    PRIME_COOPERATIVE_BANK_LIMITED("PRIME COOPERATIVE BANK LIMITED","90","PRIME COOPERATIVE BANK LIMITED"),
    PUNJAB_AND_MAHARSHTRA_COOPERATIVE_BANK("PUNJAB AND MAHARSHTRA COOPERATIVE BANK","91","PUNJAB AND MAHARSHTRA COOPERATIVE BANK"),
    PUNJAB_AND_SIND_BANK("PUNJAB AND SIND BANK","92","PUNJAB AND SIND BANK"),
    PUNJAB_NATIONAL_BANK("PUNJAB NATIONAL BANK","93","PUNJAB NATIONAL BANK"),
    RABOBANK_INTERNATIONAL("RABOBANK INTERNATIONAL","94","RABOBANK INTERNATIONAL"),
    RAJGURUNAGAR_SAHAKARI_BANK_LIMITED("RAJGURUNAGAR SAHAKARI BANK LIMITED","95","RAJGURUNAGAR SAHAKARI BANK LIMITED"),
    RAJKOT_NAGRIK_SAHAKARI_BANK_LIMITED("RAJKOT NAGRIK SAHAKARI BANK LIMITED","96","RAJKOT NAGRIK SAHAKARI BANK LIMITED"),
    RATNAKAR_BANK_LIMITED("RATNAKAR BANK LIMITED","97","RATNAKAR BANK LIMITED"),
    RESERVE_BANK_OF_INDIA("RESERVE BANK OF INDIA","98","RESERVE BANK OF INDIA"),
    SAHEBRAO_DESHMUKH_COOPERATIVE_BANK_LIMITED("SAHEBRAO DESHMUKH COOPERATIVE BANK LIMITED","99","SAHEBRAO DESHMUKH COOPERATIVE BANK LIMITED"),
    SARASWAT_COOPERATIVE_BANK_LIMITED("SARASWAT COOPERATIVE BANK LIMITED","100","SARASWAT COOPERATIVE BANK LIMITED"),
    SBER_BANK("SBER BANK","101","SBER BANK"),
    SHIKSHAK_SAHAKARI_BANK_LIMITED("SHIKSHAK SAHAKARI BANK LIMITED","102","SHIKSHAK SAHAKARI BANK LIMITED"),
    SHINHAN_BANK("SHINHAN BANK","103","SHINHAN BANK"),
    SHRI_CHHATRAPATI_RAJASHRI_SHAHU_URBAN_COOPERATIVE_BANK_LIMITED("SHRI CHHATRAPATI RAJASHRI SHAHU URBAN COOPERATIVE BANK LIMITED","104","SHRI CHHATRAPATI RAJASHRI SHAHU URBAN COOPERATIVE BANK LIMITED"),
    SOCIETE_GENERALE("SOCIETE GENERALE","105","SOCIETE GENERALE"),
    SOLAPUR_JANATA_SAHAKARI_BANK_LIMITED("SOLAPUR JANATA SAHAKARI BANK LIMITED","106","SOLAPUR JANATA SAHAKARI BANK LIMITED"),
    SOUTH_INDIAN_BANK("SOUTH INDIAN BANK","107","SOUTH INDIAN BANK"),
    STANDARD_CHARTERED_BANK("STANDARD CHARTERED BANK","108","STANDARD CHARTERED BANK"),
    STATE_BANK_OF_BIKANER_AND_JAIPUR("STATE BANK OF BIKANER AND JAIPUR","109","STATE BANK OF BIKANER AND JAIPUR"),
    STATE_BANK_OF_HYDERABAD("STATE BANK OF HYDERABAD","110","STATE BANK OF HYDERABAD"),
    STATE_BANK_OF_INDIA("STATE BANK OF INDIA","111","STATE BANK OF INDIA"),
    STATE_BANK_OF_MAURITIUS_LIMITED("STATE BANK OF MAURITIUS LIMITED","112","STATE BANK OF MAURITIUS LIMITED"),
    STATE_BANK_OF_MYSORE("STATE BANK OF MYSORE","113","STATE BANK OF MYSORE"),
    STATE_BANK_OF_PATIALA("STATE BANK OF PATIALA","114","STATE BANK OF PATIALA"),
    STATE_BANK_OF_TRAVANCORE("STATE BANK OF TRAVANCORE","115","STATE BANK OF TRAVANCORE"),
    SUMITOMO_MITSUI_BANKING_CORPORATION("SUMITOMO MITSUI BANKING CORPORATION","116","SUMITOMO MITSUI BANKING CORPORATION"),
    SUTEX_COOPERATIVE_BANK_LIMITED("SUTEX COOPERATIVE BANK LIMITED","117","SUTEX COOPERATIVE BANK LIMITED"),
    SYNDICATE_BANK("SYNDICATE BANK","118","SYNDICATE BANK"),
    TAMILNAD_MERCANTILE_BANK_LIMITED("TAMILNAD MERCANTILE BANK LIMITED","119","TAMILNAD MERCANTILE BANK LIMITED"),
    THE_AP_MAHESH_COOPERATIVE_URBAN_BANK_LIMITED("THE A.P. MAHESH COOPERATIVE URBAN BANK LIMITED","120","THE A.P. MAHESH COOPERATIVE URBAN BANK LIMITED"),
    THE_AKOLA_DISTRICT_CENTRAL_COOPERATIVE_BANK("THE AKOLA DISTRICT CENTRAL COOPERATIVE BANK","121","THE AKOLA DISTRICT CENTRAL COOPERATIVE BANK"),
    THE_ANDHRA_PRADESH_STATE_COOPERATIVE_BANK_LIMITED("THE ANDHRA PRADESH STATE COOPERATIVE BANK LIMITED","122","THE ANDHRA PRADESH STATE COOPERATIVE BANK LIMITED"),
    THE_BANK_OF_NOVA_SCOTIA("THE BANK OF NOVA SCOTIA","123","THE BANK OF NOVA SCOTIA"),
    THE_COSMOS_CO_OPERATIVE_BANK_LIMITED("THE COSMOS CO OPERATIVE BANK LIMITED","124","THE COSMOS CO OPERATIVE BANK LIMITED"),
    THE_DELHI_STATE_COOPERATIVE_BANK_LIMITED("THE DELHI STATE COOPERATIVE BANK LIMITED","125","THE DELHI STATE COOPERATIVE BANK LIMITED"),
    THE_GADCHIROLI_DISTRICT_CENTRAL_COOPERATIVE_BANK_LIMITED("THE GADCHIROLI DISTRICT CENTRAL COOPERATIVE BANK LIMITED","126","THE GADCHIROLI DISTRICT CENTRAL COOPERATIVE BANK LIMITED"),
    THE_GREATER_BOMBAY_COOPERATIVE_BANK_LIMITED("THE GREATER BOMBAY COOPERATIVE BANK LIMITED","127","THE GREATER BOMBAY COOPERATIVE BANK LIMITED"),
    THE_GUJARAT_STATE_COOPERATIVE_BANK_LIMITED("THE GUJARAT STATE COOPERATIVE BANK LIMITED","128","THE GUJARAT STATE COOPERATIVE BANK LIMITED"),
    THE_JALGAON_PEOPELS_COOPERATIVE_BANK_LIMITED("THE JALGAON PEOPELS COOPERATIVE BANK LIMITED","129","THE JALGAON PEOPELS COOPERATIVE BANK LIMITED"),
    THE_KANGRA_CENTRAL_COOPERATIVE_BANK_LIMITED("THE KANGRA CENTRAL COOPERATIVE BANK LIMITED","130","THE KANGRA CENTRAL COOPERATIVE BANK LIMITED"),
    THE_KANGRA_COOPERATIVE_BANK_LIMITED("THE KANGRA COOPERATIVE BANK LIMITED","131","THE KANGRA COOPERATIVE BANK LIMITED"),
    THE_KARAD_URBAN_COOPERATIVE_BANK_LIMITED("THE KARAD URBAN COOPERATIVE BANK LIMITED","132","THE KARAD URBAN COOPERATIVE BANK LIMITED"),
    THE_KARANATAKA_STATE_COOPERATIVE_APEX_BANK_LIMITED("THE KARANATAKA STATE COOPERATIVE APEX BANK LIMITED","133","THE KARANATAKA STATE COOPERATIVE APEX BANK LIMITED"),
    THE_KURMANCHAL_NAGAR_SAHAKARI_BANK_LIMITED("THE KURMANCHAL NAGAR SAHAKARI BANK LIMITED","134","THE KURMANCHAL NAGAR SAHAKARI BANK LIMITED"),
    THE_MEHSANA_URBAN_COOPERATIVE_BANK("THE MEHSANA URBAN COOPERATIVE BANK","135","THE MEHSANA URBAN COOPERATIVE BANK"),
    THE_MUMBAI_DISTRICT_CENTRAL_COOPERATIVE_BANK_LIMITED("THE MUMBAI DISTRICT CENTRAL COOPERATIVE BANK LIMITED","136","THE MUMBAI DISTRICT CENTRAL COOPERATIVE BANK LIMITED"),
    THE_MUNICIPAL_COOPERATIVE_BANK_LIMITED("THE MUNICIPAL COOPERATIVE BANK LIMITED","137","THE MUNICIPAL COOPERATIVE BANK LIMITED"),
    THE_NAINITAL_BANK_LIMITED("THE NAINITAL BANK LIMITED","138","THE NAINITAL BANK LIMITED"),
    THE_NASIK_MERCHANTS_COOPERATIVE_BANK_LIMITED("THE NASIK MERCHANTS COOPERATIVE BANK LIMITED","139","THE NASIK MERCHANTS COOPERATIVE BANK LIMITED"),
    THE_RAJASTHAN_STATE_COOPERATIVE_BANK_LIMITED("THE RAJASTHAN STATE COOPERATIVE BANK LIMITED","140","THE RAJASTHAN STATE COOPERATIVE BANK LIMITED"),
    THE_ROYAL_BANK_OF_SCOTLAND_N_V("THE ROYAL BANK OF SCOTLAND N V","141","THE ROYAL BANK OF SCOTLAND N V"),
    THE_SEVA_VIKAS_COOPERATIVE_BANK_LIMITED("THE SEVA VIKAS COOPERATIVE BANK LIMITED","142","THE SEVA VIKAS COOPERATIVE BANK LIMITED"),
    THE_SHAMRAO_VITHAL_COOPERATIVE_BANK("THE SHAMRAO VITHAL COOPERATIVE BANK","143","THE SHAMRAO VITHAL COOPERATIVE BANK"),
    THE_SURAT_DISTRICT_COOPERATIVE_BANK_LIMITED("THE SURAT DISTRICT COOPERATIVE BANK LIMITED","144","THE SURAT DISTRICT COOPERATIVE BANK LIMITED"),
    THE_SURATH_PEOPLES_COOPERATIVE_BANK_LIMITED("THE SURATH PEOPLES COOPERATIVE BANK LIMITED","145","THE SURATH PEOPLES COOPERATIVE BANK LIMITED"),
    THE_TAMIL_NADU_STATE_APEX_COOPERATIVE_BANK("THE TAMIL NADU STATE APEX COOPERATIVE BANK","146","THE TAMIL NADU STATE APEX COOPERATIVE BANK"),
    THE_THANE_BHARAT_SAHAKARI_BANK_LIMITED("THE THANE BHARAT SAHAKARI BANK LIMITED","147","THE THANE BHARAT SAHAKARI BANK LIMITED"),
    THE_THANE_DISTRICT_CENTRAL_COOPERATIVE_BANK_LIMITED("THE THANE DISTRICT CENTRAL COOPERATIVE BANK LIMITED","148","THE THANE DISTRICT CENTRAL COOPERATIVE BANK LIMITED"),
    THE_VARACHHA_COOPERATIVE_BANK_LIMITED("THE VARACHHA COOPERATIVE BANK LIMITED","149","THE VARACHHA COOPERATIVE BANK LIMITED"),
    THE_VISHWESHWAR_SAHAKARI_BANK_LIMITED("THE VISHWESHWAR SAHAKARI BANK LIMITED","150","THE VISHWESHWAR SAHAKARI BANK LIMITED"),
    THE_WEST_BENGAL_STATE_COOPERATIVE_BANK("THE WEST BENGAL STATE COOPERATIVE BANK","151","THE WEST BENGAL STATE COOPERATIVE BANK"),
    THE_ZOROASTRIAN_COOPERATIVE_BANK_LIMITED("THE ZOROASTRIAN COOPERATIVE BANK LIMITED","152","THE ZOROASTRIAN COOPERATIVE BANK LIMITED"),
    TJSB_SAHAKARI_BANK_LTD("TJSB SAHAKARI BANK LTD","153","TJSB SAHAKARI BANK LTD"),
    TUMKUR_GRAIN_MERCHANTS_COOPERATIVE_BANK_LIMITED("TUMKUR GRAIN MERCHANTS COOPERATIVE BANK LIMITED","154","TUMKUR GRAIN MERCHANTS COOPERATIVE BANK LIMITED"),
    UCO_BANK("UCO BANK","155","UCO BANK"),
    UNION_BANK_OF_INDIA("UNION BANK OF INDIA","156","UNION BANK OF INDIA"),
    UNITED_BANK_OF_INDIA("UNITED BANK OF INDIA","157","UNITED BANK OF INDIA"),
    UNITED_OVERSEAS_BANK_LIMITED("UNITED OVERSEAS BANK LIMITED","158","UNITED OVERSEAS BANK LIMITED"),
    VASAI_VIKAS_SAHAKARI_BANK_LIMITED("VASAI VIKAS SAHAKARI BANK LIMITED","159","VASAI VIKAS SAHAKARI BANK LIMITED"),
    VIJAYA_BANK("VIJAYA BANK","160","VIJAYA BANK"),
    WESTPAC_BANKING_CORPORATION("WESTPAC BANKING CORPORATION","161","WESTPAC BANKING CORPORATION"),
    WOORI_BANK("WOORI BANK","162","WOORI BANK"),
    YES_BANK("YES BANK","163","YES BANK"),
    ZILA_SAHAKRI_BANK_LIMITED_GHAZIABAD("ZILA SAHAKRI BANK LIMITED GHAZIABAD","164","ZILA SAHAKRI BANK LIMITED GHAZIABAD");



    private String id;
    private String value;
    private String description;
//    private String finbitName;

    private BankListMfi(String value, String id, String description) {
        this.value = value;
        this.description = description;
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public String getValue() {
        return value;
    }

    public String getDescription() {
        return description;
    }
    
    
    

//    public String getFinbitName() {
//        return finbitName;
//    }

    public static BankListMfi fromValue(String v) {
        for (BankListMfi c : BankListMfi.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public static BankListMfi fromId(String v) {
        for (BankListMfi c : BankListMfi.values()) {
            if (c.id.equals(v) || v == c.id) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public static BankListMfi[] getAll() {
        return BankListMfi.values();
    }
}
