//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.19 at 12:55:51 PM IST 
//


package com.opl.mudra.api.cibil_integration.msme.request.applicant;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="3">
 *         &lt;element name="Applicant">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ApplicantType" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="ApplicantFirstName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="ApplicantMiddleName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="ApplicantLastName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="DateOfBirth" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="Gender" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="Identifiers">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence maxOccurs="4">
 *                             &lt;element name="Identifier">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="IdNumber" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="IdType" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Telephones">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence maxOccurs="4">
 *                             &lt;element name="Telephone">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="TelephoneExtension" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="TelephoneNumber" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="TelephoneType" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Addresses">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence maxOccurs="2">
 *                             &lt;element name="Address">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="AddressLine1" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="AddressLine2" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="AddressLine3" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="AddressLine4" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="AddressLine5" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="AddressType" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="PinCode" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="ResidenceType" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="StateCode" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="MemberOtherId1Type" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                   &lt;element name="MemberOtherId1" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                   &lt;element name="MemberOtherId2Type" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                   &lt;element name="MemberOtherId2" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                   &lt;element name="MemberOtherId3Type" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                   &lt;element name="MemberOtherId3" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                   &lt;element name="KeyPersonName" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                   &lt;element name="KeyPersonRelation" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                   &lt;element name="MemberRelationName1" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                   &lt;element name="MemberRelationType1" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                   &lt;element name="MemberRelationName2" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                   &lt;element name="MemberRelationType2" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                   &lt;element name="MemberRelationName3" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                   &lt;element name="MemberRelationType3" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                   &lt;element name="MemberRelationName4" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                   &lt;element name="MemberRelationType4" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                   &lt;element name="NomineeName" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                   &lt;element name="NomineeRelation" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "applicant"
})
@XmlRootElement(name = "Applicants")
public class Applicants {

    @XmlElement(name = "Applicant", required = true)
    protected List<Applicant> applicant;

    /**
     * Gets the value of the applicant property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the applicant property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApplicant().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Applicants.Applicant }
     *
     *
     */
    public List<Applicant> getApplicant() {
        if (applicant == null) {
            applicant = new ArrayList<Applicant>();
        }
        return this.applicant;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ApplicantType" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="ApplicantFirstName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="ApplicantMiddleName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="ApplicantLastName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="DateOfBirth" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="Gender" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="Identifiers">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence maxOccurs="4">
     *                   &lt;element name="Identifier">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="IdNumber" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="IdType" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Telephones">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence maxOccurs="4">
     *                   &lt;element name="Telephone">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="TelephoneExtension" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="TelephoneNumber" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="TelephoneType" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Addresses">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence maxOccurs="2">
     *                   &lt;element name="Address">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="AddressLine1" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="AddressLine2" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="AddressLine3" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="AddressLine4" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="AddressLine5" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="AddressType" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="PinCode" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="ResidenceType" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="StateCode" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="MemberOtherId1Type" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *         &lt;element name="MemberOtherId1" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *         &lt;element name="MemberOtherId2Type" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *         &lt;element name="MemberOtherId2" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *         &lt;element name="MemberOtherId3Type" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *         &lt;element name="MemberOtherId3" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *         &lt;element name="KeyPersonName" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *         &lt;element name="KeyPersonRelation" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *         &lt;element name="MemberRelationName1" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *         &lt;element name="MemberRelationType1" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *         &lt;element name="MemberRelationName2" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *         &lt;element name="MemberRelationType2" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *         &lt;element name="MemberRelationName3" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *         &lt;element name="MemberRelationType3" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *         &lt;element name="MemberRelationName4" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *         &lt;element name="MemberRelationType4" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *         &lt;element name="NomineeName" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *         &lt;element name="NomineeRelation" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "applicantType",
        "applicantFirstName",
        "applicantMiddleName",
        "applicantLastName",
        "dateOfBirth",
        "gender",
        "identifiers",
        "telephones",
        "addresses",
        "memberOtherId1Type",
        "memberOtherId1",
        "memberOtherId2Type",
        "memberOtherId2",
        "memberOtherId3Type",
        "memberOtherId3",
        "keyPersonName",
        "keyPersonRelation",
        "memberRelationName1",
        "memberRelationType1",
        "memberRelationName2",
        "memberRelationType2",
        "memberRelationName3",
        "memberRelationType3",
        "memberRelationName4",
        "memberRelationType4",
        "nomineeName",
        "nomineeRelation"
    })
    public static class Applicant {

        @XmlElement(name = "ApplicantType", required = true)
        protected Object applicantType;
        @XmlElement(name = "ApplicantFirstName", required = true)
        protected Object applicantFirstName;
        @XmlElement(name = "ApplicantMiddleName", required = true)
        protected Object applicantMiddleName;
        @XmlElement(name = "ApplicantLastName", required = true)
        protected Object applicantLastName;
        @XmlElement(name = "DateOfBirth", required = true)
        protected Object dateOfBirth;
        @XmlElement(name = "Gender", required = true)
        protected Object gender;

        //Added For Solution Set Version 10
        @XmlElement(name = "EmailAddress", required = true)
        protected Object emailAddress;
        @XmlElement(name = "CompanyName", required = true)
        protected Object companyName;
       //Added For Solution Set Version 10

        @XmlElement(name = "Identifiers", required = true)
        protected Applicants.Applicant.Identifiers identifiers;
        @XmlElement(name = "Telephones", required = true)
        protected Applicants.Applicant.Telephones telephones;
        @XmlElement(name = "Addresses", required = true)
        protected Applicants.Applicant.Addresses addresses;
        @XmlElement(name = "MemberOtherId1Type")
        protected Object memberOtherId1Type;
        @XmlElement(name = "MemberOtherId1")
        protected Object memberOtherId1;
        @XmlElement(name = "MemberOtherId2Type")
        protected Object memberOtherId2Type;
        @XmlElement(name = "MemberOtherId2")
        protected Object memberOtherId2;
        @XmlElement(name = "MemberOtherId3Type")
        protected Object memberOtherId3Type;
        @XmlElement(name = "MemberOtherId3")
        protected Object memberOtherId3;
        @XmlElement(name = "KeyPersonName")
        protected Object keyPersonName;
        @XmlElement(name = "KeyPersonRelation")
        protected Object keyPersonRelation;
        @XmlElement(name = "MemberRelationName1")
        protected Object memberRelationName1;
        @XmlElement(name = "MemberRelationType1")
        protected Object memberRelationType1;
        @XmlElement(name = "MemberRelationName2")
        protected Object memberRelationName2;
        @XmlElement(name = "MemberRelationType2")
        protected Object memberRelationType2;
        @XmlElement(name = "MemberRelationName3")
        protected Object memberRelationName3;
        @XmlElement(name = "MemberRelationType3")
        protected Object memberRelationType3;
        @XmlElement(name = "MemberRelationName4")
        protected Object memberRelationName4;
        @XmlElement(name = "MemberRelationType4")
        protected Object memberRelationType4;
        @XmlElement(name = "NomineeName")
        protected Object nomineeName;
        @XmlElement(name = "NomineeRelation")
        protected Object nomineeRelation;

        /**
         * Gets the value of the applicantType property.
         *
         * @return
         *     possible object is
         *     {@link Object }
         *
         */
        public Object getApplicantType() {
            return applicantType;
        }

        /**
         * Sets the value of the applicantType property.
         *
         * @param value
         *     allowed object is
         *     {@link Object }
         *
         */
        public void setApplicantType(Object value) {
            this.applicantType = value;
        }

        /**
         * Gets the value of the applicantFirstName property.
         *
         * @return
         *     possible object is
         *     {@link Object }
         *
         */
        public Object getApplicantFirstName() {
            return applicantFirstName;
        }

        /**
         * Sets the value of the applicantFirstName property.
         *
         * @param value
         *     allowed object is
         *     {@link Object }
         *
         */
        public void setApplicantFirstName(Object value) {
            this.applicantFirstName = value;
        }

        /**
         * Gets the value of the applicantMiddleName property.
         *
         * @return
         *     possible object is
         *     {@link Object }
         *
         */
        public Object getApplicantMiddleName() {
            return applicantMiddleName;
        }

        /**
         * Sets the value of the applicantMiddleName property.
         *
         * @param value
         *     allowed object is
         *     {@link Object }
         *
         */
        public void setApplicantMiddleName(Object value) {
            this.applicantMiddleName = value;
        }

        /**
         * Gets the value of the applicantLastName property.
         *
         * @return
         *     possible object is
         *     {@link Object }
         *
         */
        public Object getApplicantLastName() {
            return applicantLastName;
        }

        /**
         * Sets the value of the applicantLastName property.
         *
         * @param value
         *     allowed object is
         *     {@link Object }
         *
         */
        public void setApplicantLastName(Object value) {
            this.applicantLastName = value;
        }

        /**
         * Gets the value of the dateOfBirth property.
         *
         * @return
         *     possible object is
         *     {@link Object }
         *
         */
        public Object getDateOfBirth() {
            return dateOfBirth;
        }

        /**
         * Sets the value of the dateOfBirth property.
         *
         * @param value
         *     allowed object is
         *     {@link Object }
         *
         */
        public void setDateOfBirth(Object value) {
            this.dateOfBirth = value;
        }

        /**
         * Gets the value of the gender property.
         *
         * @return
         *     possible object is
         *     {@link Object }
         *
         */
        public Object getGender() {
            return gender;
        }

        /**
         * Sets the value of the gender property.
         *
         * @param value
         *     allowed object is
         *     {@link Object }
         *
         */
        public void setGender(Object value) {
            this.gender = value;
        }

        /**
         * Gets the value of the identifiers property.
         *
         * @return
         *     possible object is
         *     {@link Applicants.Applicant.Identifiers }
         *
         */
        public Applicants.Applicant.Identifiers getIdentifiers() {
            return identifiers;
        }

        /**
         * Sets the value of the identifiers property.
         *
         * @param value
         *     allowed object is
         *     {@link Applicants.Applicant.Identifiers }
         *
         */
        public void setIdentifiers(Applicants.Applicant.Identifiers value) {
            this.identifiers = value;
        }

        /**
         * Gets the value of the telephones property.
         *
         * @return
         *     possible object is
         *     {@link Applicants.Applicant.Telephones }
         *
         */
        public Applicants.Applicant.Telephones getTelephones() {
            return telephones;
        }

        /**
         * Sets the value of the telephones property.
         *
         * @param value
         *     allowed object is
         *     {@link Applicants.Applicant.Telephones }
         *
         */
        public void setTelephones(Applicants.Applicant.Telephones value) {
            this.telephones = value;
        }

        /**
         * Gets the value of the addresses property.
         *
         * @return
         *     possible object is
         *     {@link Applicants.Applicant.Addresses }
         *
         */
        public Applicants.Applicant.Addresses getAddresses() {
            return addresses;
        }

        /**
         * Sets the value of the addresses property.
         *
         * @param value
         *     allowed object is
         *     {@link Applicants.Applicant.Addresses }
         *
         */
        public void setAddresses(Applicants.Applicant.Addresses value) {
            this.addresses = value;
        }

        /**
         * Gets the value of the memberOtherId1Type property.
         *
         * @return
         *     possible object is
         *     {@link Object }
         *
         */
        public Object getMemberOtherId1Type() {
            return memberOtherId1Type;
        }

        /**
         * Sets the value of the memberOtherId1Type property.
         *
         * @param value
         *     allowed object is
         *     {@link Object }
         *
         */
        public void setMemberOtherId1Type(Object value) {
            this.memberOtherId1Type = value;
        }

        /**
         * Gets the value of the memberOtherId1 property.
         *
         * @return
         *     possible object is
         *     {@link Object }
         *
         */
        public Object getMemberOtherId1() {
            return memberOtherId1;
        }

        /**
         * Sets the value of the memberOtherId1 property.
         *
         * @param value
         *     allowed object is
         *     {@link Object }
         *
         */
        public void setMemberOtherId1(Object value) {
            this.memberOtherId1 = value;
        }

        /**
         * Gets the value of the memberOtherId2Type property.
         *
         * @return
         *     possible object is
         *     {@link Object }
         *
         */
        public Object getMemberOtherId2Type() {
            return memberOtherId2Type;
        }

        /**
         * Sets the value of the memberOtherId2Type property.
         *
         * @param value
         *     allowed object is
         *     {@link Object }
         *
         */
        public void setMemberOtherId2Type(Object value) {
            this.memberOtherId2Type = value;
        }

        /**
         * Gets the value of the memberOtherId2 property.
         *
         * @return
         *     possible object is
         *     {@link Object }
         *
         */
        public Object getMemberOtherId2() {
            return memberOtherId2;
        }

        /**
         * Sets the value of the memberOtherId2 property.
         *
         * @param value
         *     allowed object is
         *     {@link Object }
         *
         */
        public void setMemberOtherId2(Object value) {
            this.memberOtherId2 = value;
        }

        /**
         * Gets the value of the memberOtherId3Type property.
         *
         * @return
         *     possible object is
         *     {@link Object }
         *
         */
        public Object getMemberOtherId3Type() {
            return memberOtherId3Type;
        }

        /**
         * Sets the value of the memberOtherId3Type property.
         *
         * @param value
         *     allowed object is
         *     {@link Object }
         *
         */
        public void setMemberOtherId3Type(Object value) {
            this.memberOtherId3Type = value;
        }

        /**
         * Gets the value of the memberOtherId3 property.
         *
         * @return
         *     possible object is
         *     {@link Object }
         *
         */
        public Object getMemberOtherId3() {
            return memberOtherId3;
        }

        /**
         * Sets the value of the memberOtherId3 property.
         *
         * @param value
         *     allowed object is
         *     {@link Object }
         *
         */
        public void setMemberOtherId3(Object value) {
            this.memberOtherId3 = value;
        }

        /**
         * Gets the value of the keyPersonName property.
         *
         * @return
         *     possible object is
         *     {@link Object }
         *
         */
        public Object getKeyPersonName() {
            return keyPersonName;
        }

        /**
         * Sets the value of the keyPersonName property.
         *
         * @param value
         *     allowed object is
         *     {@link Object }
         *
         */
        public void setKeyPersonName(Object value) {
            this.keyPersonName = value;
        }

        /**
         * Gets the value of the keyPersonRelation property.
         *
         * @return
         *     possible object is
         *     {@link Object }
         *
         */
        public Object getKeyPersonRelation() {
            return keyPersonRelation;
        }

        /**
         * Sets the value of the keyPersonRelation property.
         *
         * @param value
         *     allowed object is
         *     {@link Object }
         *
         */
        public void setKeyPersonRelation(Object value) {
            this.keyPersonRelation = value;
        }

        /**
         * Gets the value of the memberRelationName1 property.
         *
         * @return
         *     possible object is
         *     {@link Object }
         *
         */
        public Object getMemberRelationName1() {
            return memberRelationName1;
        }

        /**
         * Sets the value of the memberRelationName1 property.
         *
         * @param value
         *     allowed object is
         *     {@link Object }
         *
         */
        public void setMemberRelationName1(Object value) {
            this.memberRelationName1 = value;
        }

        /**
         * Gets the value of the memberRelationType1 property.
         *
         * @return
         *     possible object is
         *     {@link Object }
         *
         */
        public Object getMemberRelationType1() {
            return memberRelationType1;
        }

        /**
         * Sets the value of the memberRelationType1 property.
         *
         * @param value
         *     allowed object is
         *     {@link Object }
         *
         */
        public void setMemberRelationType1(Object value) {
            this.memberRelationType1 = value;
        }

        /**
         * Gets the value of the memberRelationName2 property.
         *
         * @return
         *     possible object is
         *     {@link Object }
         *
         */
        public Object getMemberRelationName2() {
            return memberRelationName2;
        }

        /**
         * Sets the value of the memberRelationName2 property.
         *
         * @param value
         *     allowed object is
         *     {@link Object }
         *
         */
        public void setMemberRelationName2(Object value) {
            this.memberRelationName2 = value;
        }

        /**
         * Gets the value of the memberRelationType2 property.
         *
         * @return
         *     possible object is
         *     {@link Object }
         *
         */
        public Object getMemberRelationType2() {
            return memberRelationType2;
        }

        /**
         * Sets the value of the memberRelationType2 property.
         *
         * @param value
         *     allowed object is
         *     {@link Object }
         *
         */
        public void setMemberRelationType2(Object value) {
            this.memberRelationType2 = value;
        }

        /**
         * Gets the value of the memberRelationName3 property.
         *
         * @return
         *     possible object is
         *     {@link Object }
         *
         */
        public Object getMemberRelationName3() {
            return memberRelationName3;
        }

        /**
         * Sets the value of the memberRelationName3 property.
         *
         * @param value
         *     allowed object is
         *     {@link Object }
         *
         */
        public void setMemberRelationName3(Object value) {
            this.memberRelationName3 = value;
        }

        /**
         * Gets the value of the memberRelationType3 property.
         *
         * @return
         *     possible object is
         *     {@link Object }
         *
         */
        public Object getMemberRelationType3() {
            return memberRelationType3;
        }

        /**
         * Sets the value of the memberRelationType3 property.
         *
         * @param value
         *     allowed object is
         *     {@link Object }
         *
         */
        public void setMemberRelationType3(Object value) {
            this.memberRelationType3 = value;
        }

        /**
         * Gets the value of the memberRelationName4 property.
         *
         * @return
         *     possible object is
         *     {@link Object }
         *
         */
        public Object getMemberRelationName4() {
            return memberRelationName4;
        }

        /**
         * Sets the value of the memberRelationName4 property.
         *
         * @param value
         *     allowed object is
         *     {@link Object }
         *
         */
        public void setMemberRelationName4(Object value) {
            this.memberRelationName4 = value;
        }

        /**
         * Gets the value of the memberRelationType4 property.
         *
         * @return
         *     possible object is
         *     {@link Object }
         *
         */
        public Object getMemberRelationType4() {
            return memberRelationType4;
        }

        /**
         * Sets the value of the memberRelationType4 property.
         *
         * @param value
         *     allowed object is
         *     {@link Object }
         *
         */
        public void setMemberRelationType4(Object value) {
            this.memberRelationType4 = value;
        }

        /**
         * Gets the value of the nomineeName property.
         *
         * @return
         *     possible object is
         *     {@link Object }
         *
         */
        public Object getNomineeName() {
            return nomineeName;
        }

        /**
         * Sets the value of the nomineeName property.
         *
         * @param value
         *     allowed object is
         *     {@link Object }
         *
         */
        public void setNomineeName(Object value) {
            this.nomineeName = value;
        }

        /**
         * Gets the value of the nomineeRelation property.
         *
         * @return
         *     possible object is
         *     {@link Object }
         *
         */
        public Object getNomineeRelation() {
            return nomineeRelation;
        }

        /**
         * Sets the value of the nomineeRelation property.
         *
         * @param value
         *     allowed object is
         *     {@link Object }
         *
         */
        public void setNomineeRelation(Object value) {
            this.nomineeRelation = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence maxOccurs="2">
         *         &lt;element name="Address">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="AddressLine1" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="AddressLine2" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="AddressLine3" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="AddressLine4" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="AddressLine5" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="AddressType" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="PinCode" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="ResidenceType" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="StateCode" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "address"
        })
        public static class Addresses {

            @XmlElement(name = "Address", required = true)
            protected List<Address> address;

            /**
             * Gets the value of the address property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the address property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAddress().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Applicants.Applicant.Addresses.Address }
             *
             *
             */
            public List<Address> getAddress() {
                if (address == null) {
                    address = new ArrayList<Address>();
                }
                return this.address;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="AddressLine1" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="AddressLine2" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="AddressLine3" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="AddressLine4" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="AddressLine5" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="AddressType" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="PinCode" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="ResidenceType" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="StateCode" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "addressLine1",
                "addressLine2",
                "addressLine3",
                "addressLine4",
                "addressLine5",
                "addressType",
                "city",
                "pinCode",
                "residenceType",
                "stateCode"
            })
            public static class Address {

                @XmlElement(name = "AddressLine1", required = true)
                protected Object addressLine1;
                @XmlElement(name = "AddressLine2", required = true)
                protected Object addressLine2;
                @XmlElement(name = "AddressLine3", required = true)
                protected Object addressLine3;
                @XmlElement(name = "AddressLine4", required = true)
                protected Object addressLine4;
                @XmlElement(name = "AddressLine5", required = true)
                protected Object addressLine5;
                @XmlElement(name = "AddressType", required = true)
                protected Object addressType;
                @XmlElement(name = "City", required = true)
                protected Object city;
                @XmlElement(name = "PinCode", required = true)
                protected Object pinCode;
                @XmlElement(name = "ResidenceType", required = true)
                protected Object residenceType;
                @XmlElement(name = "StateCode", required = true)
                protected Object stateCode;

                /**
                 * Gets the value of the addressLine1 property.
                 *
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *
                 */
                public Object getAddressLine1() {
                    return addressLine1;
                }

                /**
                 * Sets the value of the addressLine1 property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *
                 */
                public void setAddressLine1(Object value) {
                    this.addressLine1 = value;
                }

                /**
                 * Gets the value of the addressLine2 property.
                 *
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *
                 */
                public Object getAddressLine2() {
                    return addressLine2;
                }

                /**
                 * Sets the value of the addressLine2 property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *
                 */
                public void setAddressLine2(Object value) {
                    this.addressLine2 = value;
                }

                /**
                 * Gets the value of the addressLine3 property.
                 *
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *
                 */
                public Object getAddressLine3() {
                    return addressLine3;
                }

                /**
                 * Sets the value of the addressLine3 property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *
                 */
                public void setAddressLine3(Object value) {
                    this.addressLine3 = value;
                }

                /**
                 * Gets the value of the addressLine4 property.
                 *
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *
                 */
                public Object getAddressLine4() {
                    return addressLine4;
                }

                /**
                 * Sets the value of the addressLine4 property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *
                 */
                public void setAddressLine4(Object value) {
                    this.addressLine4 = value;
                }

                /**
                 * Gets the value of the addressLine5 property.
                 *
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *
                 */
                public Object getAddressLine5() {
                    return addressLine5;
                }

                /**
                 * Sets the value of the addressLine5 property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *
                 */
                public void setAddressLine5(Object value) {
                    this.addressLine5 = value;
                }

                /**
                 * Gets the value of the addressType property.
                 *
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *
                 */
                public Object getAddressType() {
                    return addressType;
                }

                /**
                 * Sets the value of the addressType property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *
                 */
                public void setAddressType(Object value) {
                    this.addressType = value;
                }

                /**
                 * Gets the value of the city property.
                 *
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *
                 */
                public Object getCity() {
                    return city;
                }

                /**
                 * Sets the value of the city property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *
                 */
                public void setCity(Object value) {
                    this.city = value;
                }

                /**
                 * Gets the value of the pinCode property.
                 *
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *
                 */
                public Object getPinCode() {
                    return pinCode;
                }

                /**
                 * Sets the value of the pinCode property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *
                 */
                public void setPinCode(Object value) {
                    this.pinCode = value;
                }

                /**
                 * Gets the value of the residenceType property.
                 *
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *
                 */
                public Object getResidenceType() {
                    return residenceType;
                }

                /**
                 * Sets the value of the residenceType property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *
                 */
                public void setResidenceType(Object value) {
                    this.residenceType = value;
                }

                /**
                 * Gets the value of the stateCode property.
                 *
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *
                 */
                public Object getStateCode() {
                    return stateCode;
                }

                /**
                 * Sets the value of the stateCode property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *
                 */
                public void setStateCode(Object value) {
                    this.stateCode = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence maxOccurs="4">
         *         &lt;element name="Identifier">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="IdNumber" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="IdType" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "identifier"
        })
        public static class Identifiers {

            @XmlElement(name = "Identifier", required = true)
            protected List<Identifier> identifier;

            /**
             * Gets the value of the identifier property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the identifier property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getIdentifier().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Applicants.Applicant.Identifiers.Identifier }
             *
             *
             */
            public List<Identifier> getIdentifier() {
                if (identifier == null) {
                    identifier = new ArrayList<Identifier>();
                }
                return this.identifier;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="IdNumber" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="IdType" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "idNumber",
                "idType"
            })
            public static class Identifier {

                @XmlElement(name = "IdNumber", required = true)
                protected Object idNumber;
                @XmlElement(name = "IdType", required = true)
                protected Object idType;

                /**
                 * Gets the value of the idNumber property.
                 *
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *
                 */
                public Object getIdNumber() {
                    return idNumber;
                }

                /**
                 * Sets the value of the idNumber property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *
                 */
                public void setIdNumber(Object value) {
                    this.idNumber = value;
                }

                /**
                 * Gets the value of the idType property.
                 *
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *
                 */
                public Object getIdType() {
                    return idType;
                }

                /**
                 * Sets the value of the idType property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *
                 */
                public void setIdType(Object value) {
                    this.idType = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence maxOccurs="4">
         *         &lt;element name="Telephone">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="TelephoneExtension" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="TelephoneNumber" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="TelephoneType" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "telephone"
        })
        public static class Telephones {

            @XmlElement(name = "Telephone", required = true)
            protected List<Telephone> telephone;

            /**
             * Gets the value of the telephone property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the telephone property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTelephone().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Applicants.Applicant.Telephones.Telephone }
             *
             *
             */
            public List<Telephone> getTelephone() {
                if (telephone == null) {
                    telephone = new ArrayList<Telephone>();
                }
                return this.telephone;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="TelephoneExtension" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="TelephoneNumber" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="TelephoneType" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "telephoneExtension",
                "telephoneNumber",
                "telephoneType"
            })
            public static class Telephone {

                @XmlElement(name = "TelephoneExtension", required = true)
                protected Object telephoneExtension;
                @XmlElement(name = "TelephoneNumber", required = true)
                protected Object telephoneNumber;
                @XmlElement(name = "TelephoneType", required = true)
                protected Object telephoneType;

                /**
                 * Gets the value of the telephoneExtension property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getTelephoneExtension() {
                    return telephoneExtension;
                }

                /**
                 * Sets the value of the telephoneExtension property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setTelephoneExtension(Object value) {
                    this.telephoneExtension = value;
                }

                /**
                 * Gets the value of the telephoneNumber property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getTelephoneNumber() {
                    return telephoneNumber;
                }

                /**
                 * Sets the value of the telephoneNumber property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setTelephoneNumber(Object value) {
                    this.telephoneNumber = value;
                }

                /**
                 * Gets the value of the telephoneType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getTelephoneType() {
                    return telephoneType;
                }

                /**
                 * Sets the value of the telephoneType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setTelephoneType(Object value) {
                    this.telephoneType = value;
                }

            }

        }

    }

}
