//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.19 at 12:55:51 PM IST 
//


package com.opl.mudra.api.cibil_integration.msme.request.applicant;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {// Do nothing because of X and Y.
    }

    /**
     * Create an instance of {@link Applicants }
     * 
     */
    public Applicants createApplicants() {
        return new Applicants();
    }

    /**
     * Create an instance of {@link Applicants.Applicant }
     * 
     */
    public Applicants.Applicant createApplicantsApplicant() {
        return new Applicants.Applicant();
    }

    /**
     * Create an instance of {@link Applicants.Applicant.Addresses }
     * 
     */
    public Applicants.Applicant.Addresses createApplicantsApplicantAddresses() {
        return new Applicants.Applicant.Addresses();
    }

    /**
     * Create an instance of {@link Applicants.Applicant.Telephones }
     * 
     */
    public Applicants.Applicant.Telephones createApplicantsApplicantTelephones() {
        return new Applicants.Applicant.Telephones();
    }

    /**
     * Create an instance of {@link Applicants.Applicant.Identifiers }
     * 
     */
    public Applicants.Applicant.Identifiers createApplicantsApplicantIdentifiers() {
        return new Applicants.Applicant.Identifiers();
    }

    /**
     * Create an instance of {@link Applicants.Applicant.Addresses.Address }
     * 
     */
    public Applicants.Applicant.Addresses.Address createApplicantsApplicantAddressesAddress() {
        return new Applicants.Applicant.Addresses.Address();
    }

    /**
     * Create an instance of {@link Applicants.Applicant.Telephones.Telephone }
     * 
     */
    public Applicants.Applicant.Telephones.Telephone createApplicantsApplicantTelephonesTelephone() {
        return new Applicants.Applicant.Telephones.Telephone();
    }

    /**
     * Create an instance of {@link Applicants.Applicant.Identifiers.Identifier }
     * 
     */
    public Applicants.Applicant.Identifiers.Identifier createApplicantsApplicantIdentifiersIdentifier() {
        return new Applicants.Applicant.Identifiers.Identifier();
    }

}
