package com.opl.mudra.api.oneform.utils;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class CommonUtils {
	
	public static final Long LONG_TERM_CREDIT_RATING = 1L;
	public static final Long SHORT_TERM_CREDIT_RATING = 2L;
	public static final Long SME_TERM_CREDIT_RATING = 3L;
	public static final Long CCR_TERM_CREDIT_RATING = 4L;

	public static final String EXCEPTION = "Exception :: ";
	public static final String DATA_FOUND = "Data Found.";
	public static final String SOMETHING_WENT_WRONG = "Something went wrong!";
	public static final String REQUESTED_DATA_CAN_NOT_BE_EMPTY = "Requested data can not be empty.";
	public static final String GIVEN_DETAIL_RECORD_IS_NOT_EXISTS_IN_DB = "Given Detail Record is Not Exists in DB";
	public static final String ERROR_WHILE_GETTING_MASTER_DATA = "Error while getting master data : {}";
	public static final String NAME_CAN_NOT_BE_NULL = "Name can not be null : ";
	public static final String START_SAVE = "Start save";
	public static final String END_SAVE = "End save";
	public static final String CENTRAL_GOVERNMENT_SALARY_ACCOUNT_NOT_WITH_BANK = "Central Government - Salary Account not with Bank";
	public static final String STATE_GOVERNMENT_SALARY_ACCOUNT_NOT_WITH_BANK = "State Government - Salary Account not with Bank";
	public static final String PSU_SALARY_ACCOUNT_NOT_WITH_BANK = "PSU - Salary Account not with Bank";
	public static final String CORPORATE_SALARY_ACCOUNT_NOT_WITH_BANK = "Corporate – Salary Account not with Bank (Small Sector - Pvt Ltd Companies)";
	public static final String CORPORATE_SALARY_ACCOUNT_WITH_BANK = "Corporate – Salary Account with Bank (Small Sector - Pvt Ltd Companies)";
	public static final String PUBLIC_LIMITED_COMPANY = "Public Limited Company";
	public static final String QUASI_GOVERNMENT_NOT_WITH_BANK = "Quasi Government - Salary Account not with Bank";
	public static final String QUASI_GOVERNMENT_WITH_BANK = "Quasi Government - Salary Account with Bank";
	public static final String BANK = "Bank";
	public static final String INSURANCE_COMPANY = "Insurance Company";

	private static final String ALGORITHM = "AES";
	private static final String CHAR_ENCODING = "UTF-8";
	private static final String SECRET = "26f1ac75f77c22ebc66e2359c13ea9955ebd5e2bd7fbe50e5b3ac2977a772302";


	private static final List<EnumsClassName> MASTER_DATA =  new ArrayList<EnumsClassName>();

	public static List<EnumsClassName> getMasterData(){
		return MASTER_DATA;
	}
	static{
		MASTER_DATA.addAll(Arrays.asList(CommonUtils.EnumsClassName.values()));
	}
	
	public enum EnumsClassName{
		AccountingSystem,
		AlliedActivity,
		ApplicantType,
		AssetType,
		BrandAmbassador,
		CarPurchaseType,
		CampaignCode,
		CarType,
		CampaignType,
		Competence,
		Constitution,
		ComplianceConditions,
		Country,
		CreditRatingAvialable,
		CreditRatingFund,
		CreditRatingTerm,
		Currency,
		DateInDigit,
		Denomination,
		DistributionMarketingTieUp,
		Desbursement,
		DesbursementMode,
		EmployeeWith,
		EnvironmentCertification,
		EstablishmentMonth,
		EstablishmentYear,
		ExpiryYear,
		ExistingShareholder,
		FinanceCategory,
		FpDebtType,
		FpTenureMonth,
		FpTenureYear,
		FundproviderSubType,
		FundproviderType,
		FundseekerType,
		FundType,
		Gender,
		IncomeDetail,
		IndiaDistributionNetwork,
		IndustryType,
		InternalAudit,
		KotakSubParameter,
		LandSize,
		LenderType,
		LoanPurpose,
		MaritalStatus,
		MarketingPositioningNew,
		MarketPosition,
		MarketPositioningTop,
		MarketShareTurnover,
		NatureFacility,
		Occupation,
		OccupationHL,
		OccupationStatus,
		OccupationNature,
		NewOccupationNature,
		Option,
		OverseasNetwork,
		Particular,
		ParticularOfSecurity,
		PersonalLoanPurpose,
		HomeLoanPurpose,
		LoanPurposeQuestion,
		ProductServicesPerse,
		PropertySubType,
		PropertyType,
		PropertyTypeLap,
		PropertyUsedSubType,
		PropertyUsedType,
		Rating,
		RatingAgency,
		RatingAgencyParameter,
		ReferencesList,
		RelationshipType,
		RelationshipTypeHL,
		RepairType,
		SalaryModeMst,
		SecurityType,
		ServiceproviderType,
		ShareHoldingCategory,
		TechnologyPatented,
		TechnologyRequiresUpgradation,
		Title,
		TypeTechnology,
		YearsInWord,
		Industry,
		OrganisationsSpecialisation,
		CastCategory,
		EducationStatusRetailMst,
		EmploymentStatusRetailMst,
		InterestRateRetailMst,
		OfficeTypeRetailMst,
		OwnershipTypeRetailMst,
		ReligionRetailMst,
		RepaymentCycleRetailMst,
		RepaymentModeRetailMst,
		ResidenceStatusRetailMst,
		HomeLoanType,
		CreditCardTypesRetail,
		TechnologyRisk,
		CustomerQuality,
		SupplierQuality,
		SustainabilityProduct,
		OrderBook,
		IndustrialRelations,
		ProductSeasonality,
		OperatingMargins,
		EnvironmentalImpact,
		AccountingQuality,
		FinancialRestructuring,
		Integrity,
		BusinessCommitment,
		ManagementCompetence,
		BusinessExperience,
		SuccessionPlanning,
		FinancialSupport,
		AbilityRaiseFunds,
		CompanyConflicts,
		InternalControl,
		CreditRecord,
		StatusClearances,
		StatusFinancialClosure,
		InfrastructureAvailability,
		ConstructionContract,
		ChequesReturned,
		LimitOverdrawn,
		CumulativeOverdrawn,
		SubmissionReports,
		DelayInstalments,
		DelaySubmission,
		BorrowerInvoked,
		UnhedgedCurrency,
		ProjectedRatio,
		InternalReturn,
		SensititivityAnalysis,
		VarianceSales,
		ModeOfRecipt,
		PurposeOfLoan,
		HaveCollateralSecurity,
		FinancialStrength,
		AssessmentMethods,
		OccupationNatureNTB,
		EmploymentWithNTB,
		EmploymentCategory,
		EmploymentStatusNTB,
		ProposedDetailOfUnitNTB,
		ProposedConstitutionOfUnitNTB,
		EducationQualificationNTB,
		DirectorRelationshipType,
		MsmeFundingMasterFP,
		AssessmentOptionForFS,
		CompetitionMst_SBI,
		EducationalStatusMst,
		FactoryPremiseMst,
		KnowHowMst,
		LCBG_Status_SBI,
		MaritalStatusMst,
		ResidentStatusMst,
		ResidentStatusMstHomeLoan,
		ResidenceTypeHomeLoan,
		SpouseDetailMst,
		CGTMSEParameterFP,
		OwningHouseMst,
		ODOPResidenceStatus,
		AssessedForITMst,
		VisuallyImpairedMst,
		HaveLIMst,
		CreditType,
		DisabilityType,
		LoanPurposePL,
		EmploymentWithPL,
		Religion,
		CentralGovernment,
		StateGovernment,
		Psu,
		HomeLoanBank,
		HomeLoanInsurance,
		Corporate,
		EducationalInstitute,
		Environment,
		ResidentialStatus,
		AccountType,
		WcRenewalType,
		WcFinancialType,
		BankList,
		SpouseEmploymentType,
		DesignationList,
		YesNo,
		BorrowerSalaryAccount,
		CollateralType,
		EmploymentWithRetail,
		AccountTypeEnum,
		AccountTypeRetailEnum,
		TypeOfOwnership,
		MeansOfFinanceParticulars,
		ProjectCostParticulars,
		RepaymentModeRetail,
		CorporateGovernanceCompliance,
		SidbiConstitution,
		SidbiCurrencyRate,
		AcademicQualification,
		AnnualIncome,
		OwnershipOfHouse,
		PurposeOfLoanMFI,
		AddressProofType,
		FrequencyPaymentMstMFI,
		RelationMstMFI,
		AccountTypeMfi,
		HouseTypeMfi,
		FamilyMembersMfi,
		BusinessTypeMfi,
		HouseOwnershipMfi,
		HeadFamilyEduMfi,
		AssetsLiabilityTypeMfi,
		ParticularsMfi,
		ClientTypeMfi,
		MarketReportMfi,
		CompetitionMfi,
		RePaymentTrackRecordMfi,
		AreaTypeMfi,
		BankListMfi,
		PpiPersonDetailMFI,
		BusinessInBriefMstMFI,
		VehicleType, 
		VehicleCategory, 
		VehicleAge,
		VehicleEngineVolume, 
		VehicleSegment, 
		RepaymentMode , 
		VechicleUse,
		AutoLoanPurposeType,
		AutoDetailPurposeofLoan,
		AutoPurposeofLoan,
		IdProofMst,
		CertificationCourse,
		MinorityCastCatergory,
		GovSchemesMst,
		MrktArrFinishedGoodsList,
		RegistrationWithGovernmentAuthoritiesList,
		EducationalStatusMudraMst,
		AccessToInputs,
		BusinessProspects,
		MudraOwningHouseMst,
		MudraCastCategory,
		ODOPCastCategory,
		CertificationCourseMst,
		OngoingMudraLoan,
		LoanOwnerShip,
		ODOPSkillCertificate,
		QualificationODOP,
		NoOfEmployees,
		ConstitutionForGST,
		ITRType,
		ITRRequestType,
		SourceMasterMsme,
		NumberofYear
	}
}
