//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.19 at 01:08:15 PM IST 
//


package com.opl.mudra.api.cibil_integration.msme.response.dcbureao;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DsCibilBureauData">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Request" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DsCibilBureauStatus">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Trail" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Response">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CibilBureauResponse">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="BureauResponseRaw" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="BureauResponseXml" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="SecondaryReportXml" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="IsSucess" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dsCibilBureauData",
    "dsCibilBureauStatus",
    "response"
})
@XmlRootElement(name = "DsCibilBureau")
public class DsCibilBureau {

    @XmlElement(name = "DsCibilBureauData", required = true)
    protected DsCibilBureau.DsCibilBureauData dsCibilBureauData;
    @XmlElement(name = "DsCibilBureauStatus", required = true)
    protected DsCibilBureau.DsCibilBureauStatus dsCibilBureauStatus;
    @XmlElement(name = "Response", required = true)
    protected DsCibilBureau.Response response;

    /**
     * Gets the value of the dsCibilBureauData property.
     *
     * @return
     *     possible object is
     *     {@link DsCibilBureau.DsCibilBureauData }
     *
     */
    public DsCibilBureau.DsCibilBureauData getDsCibilBureauData() {
        return dsCibilBureauData;
    }

    /**
     * Sets the value of the dsCibilBureauData property.
     *
     * @param value
     *     allowed object is
     *     {@link DsCibilBureau.DsCibilBureauData }
     *
     */
    public void setDsCibilBureauData(DsCibilBureau.DsCibilBureauData value) {
        this.dsCibilBureauData = value;
    }

    /**
     * Gets the value of the dsCibilBureauStatus property.
     *
     * @return
     *     possible object is
     *     {@link DsCibilBureau.DsCibilBureauStatus }
     *
     */
    public DsCibilBureau.DsCibilBureauStatus getDsCibilBureauStatus() {
        return dsCibilBureauStatus;
    }

    /**
     * Sets the value of the dsCibilBureauStatus property.
     *
     * @param value
     *     allowed object is
     *     {@link DsCibilBureau.DsCibilBureauStatus }
     *
     */
    public void setDsCibilBureauStatus(DsCibilBureau.DsCibilBureauStatus value) {
        this.dsCibilBureauStatus = value;
    }

    /**
     * Gets the value of the response property.
     *
     * @return
     *     possible object is
     *     {@link DsCibilBureau.Response }
     *
     */
    public DsCibilBureau.Response getResponse() {
        return response;
    }

    /**
     * Sets the value of the response property.
     *
     * @param value
     *     allowed object is
     *     {@link DsCibilBureau.Response }
     *
     */
    public void setResponse(DsCibilBureau.Response value) {
        this.response = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Request" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "request"
    })
    public static class DsCibilBureauData {

        @XmlElement(name = "Request", required = true)
        protected Object request;

        /**
         * Gets the value of the request property.
         *
         * @return
         *     possible object is
         *     {@link Object }
         *
         */
        public Object getRequest() {
            return request;
        }

        /**
         * Sets the value of the request property.
         *
         * @param value
         *     allowed object is
         *     {@link Object }
         *
         */
        public void setRequest(Object value) {
            this.request = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Trail" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "trail"
    })
    public static class DsCibilBureauStatus {

        @XmlElement(name = "Trail", required = true)
        protected Object trail;

        /**
         * Gets the value of the trail property.
         *
         * @return
         *     possible object is
         *     {@link Object }
         *
         */
        public Object getTrail() {
            return trail;
        }

        /**
         * Sets the value of the trail property.
         *
         * @param value
         *     allowed object is
         *     {@link Object }
         *
         */
        public void setTrail(Object value) {
            this.trail = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CibilBureauResponse">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="BureauResponseRaw" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                   &lt;element name="BureauResponseXml" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                   &lt;element name="SecondaryReportXml" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                   &lt;element name="IsSucess" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cibilBureauResponse"
    })
    public static class Response {

        @XmlElement(name = "CibilBureauResponse", required = true)
        protected DsCibilBureau.Response.CibilBureauResponse cibilBureauResponse;

        /**
         * Gets the value of the cibilBureauResponse property.
         *
         * @return
         *     possible object is
         *     {@link DsCibilBureau.Response.CibilBureauResponse }
         *
         */
        public DsCibilBureau.Response.CibilBureauResponse getCibilBureauResponse() {
            return cibilBureauResponse;
        }

        /**
         * Sets the value of the cibilBureauResponse property.
         *
         * @param value
         *     allowed object is
         *     {@link DsCibilBureau.Response.CibilBureauResponse }
         *
         */
        public void setCibilBureauResponse(DsCibilBureau.Response.CibilBureauResponse value) {
            this.cibilBureauResponse = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="BureauResponseRaw" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *         &lt;element name="BureauResponseXml" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *         &lt;element name="SecondaryReportXml" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *         &lt;element name="IsSucess" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "bureauResponseRaw",
            "bureauResponseXml",
            "secondaryReportXml",
            "isSucess"
        })
        public static class CibilBureauResponse {

            @XmlElement(name = "BureauResponseRaw", required = true)
            protected Object bureauResponseRaw;
            @XmlElement(name = "BureauResponseXml", required = true)
            protected Object bureauResponseXml;
            @XmlElement(name = "SecondaryReportXml", required = true)
            protected Object secondaryReportXml;
            @XmlElement(name = "IsSucess", required = true)
            protected String isSucess;

            /**
             * Gets the value of the bureauResponseRaw property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getBureauResponseRaw() {
                return bureauResponseRaw;
            }

            /**
             * Sets the value of the bureauResponseRaw property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setBureauResponseRaw(Object value) {
                this.bureauResponseRaw = value;
            }

            /**
             * Gets the value of the bureauResponseXml property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getBureauResponseXml() {
                return bureauResponseXml;
            }

            /**
             * Sets the value of the bureauResponseXml property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setBureauResponseXml(Object value) {
                this.bureauResponseXml = value;
            }

            /**
             * Gets the value of the secondaryReportXml property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getSecondaryReportXml() {
                return secondaryReportXml;
            }

            /**
             * Sets the value of the secondaryReportXml property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setSecondaryReportXml(Object value) {
                this.secondaryReportXml = value;
            }

            /**
             * Gets the value of the isSucess property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIsSucess() {
                return isSucess;
            }

            /**
             * Sets the value of the isSucess property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIsSucess(String value) {
                this.isSucess = value;
            }

        }

    }

}
