//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.19 at 01:08:15 PM IST 
//


package com.opl.mudra.api.cibil_integration.msme.response.dcbureao;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {// Do nothing because of X and Y.
    }

    /**
     * Create an instance of {@link DsCibilBureau }
     * 
     */
    public DsCibilBureau createDsCibilBureau() {
        return new DsCibilBureau();
    }

    /**
     * Create an instance of {@link DsCibilBureau.Response }
     * 
     */
    public DsCibilBureau.Response createDsCibilBureauResponse() {
        return new DsCibilBureau.Response();
    }

    /**
     * Create an instance of {@link DsCibilBureau.DsCibilBureauData }
     * 
     */
    public DsCibilBureau.DsCibilBureauData createDsCibilBureauDsCibilBureauData() {
        return new DsCibilBureau.DsCibilBureauData();
    }

    /**
     * Create an instance of {@link DsCibilBureau.DsCibilBureauStatus }
     * 
     */
    public DsCibilBureau.DsCibilBureauStatus createDsCibilBureauDsCibilBureauStatus() {
        return new DsCibilBureau.DsCibilBureauStatus();
    }

    /**
     * Create an instance of {@link DsCibilBureau.Response.CibilBureauResponse }
     * 
     */
    public DsCibilBureau.Response.CibilBureauResponse createDsCibilBureauResponseCibilBureauResponse() {
        return new DsCibilBureau.Response.CibilBureauResponse();
    }

}
