//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.19 at 01:03:34 PM IST 
//


package com.opl.mudra.api.cibil_integration.msme.response.applicant;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ApplicantsApplicantAddresses_QNAME = new QName("", "Addresses");
    private final static QName _ApplicantsApplicantDateOfBirth_QNAME = new QName("", "DateOfBirth");
    private final static QName _ApplicantsApplicantApplicantFirstName_QNAME = new QName("", "ApplicantFirstName");
    private final static QName _ApplicantsApplicantDsCibilBureau_QNAME = new QName("", "DsCibilBureau");
    private final static QName _ApplicantsApplicantApplicantType_QNAME = new QName("", "ApplicantType");
    private final static QName _ApplicantsApplicantTelephones_QNAME = new QName("", "Telephones");
    private final static QName _ApplicantsApplicantApplicantLastName_QNAME = new QName("", "ApplicantLastName");
    private final static QName _ApplicantsApplicantDsIDVision_QNAME = new QName("", "DsIDVision");
    private final static QName _ApplicantsApplicantGender_QNAME = new QName("", "Gender");
    private final static QName _ApplicantsApplicantIdentifiers_QNAME = new QName("", "Identifiers");
    private final static QName _ApplicantsApplicantApplicantMiddleName_QNAME = new QName("", "ApplicantMiddleName");
    private final static QName _ApplicantsApplicantIdentifiersIdentifierIdNumber_QNAME = new QName("", "IdNumber");
    private final static QName _ApplicantsApplicantIdentifiersIdentifierIdType_QNAME = new QName("", "IdType");
    private final static QName _ApplicantsApplicantTelephonesTelephoneTelephoneType_QNAME = new QName("", "TelephoneType");
    private final static QName _ApplicantsApplicantTelephonesTelephoneTelephoneNumber_QNAME = new QName("", "TelephoneNumber");
    private final static QName _ApplicantsApplicantTelephonesTelephoneTelephoneExtension_QNAME = new QName("", "TelephoneExtension");
    private final static QName _ApplicantsApplicantAddressesAddressResidenceType_QNAME = new QName("", "ResidenceType");
    private final static QName _ApplicantsApplicantAddressesAddressAddressLine3_QNAME = new QName("", "AddressLine3");
    private final static QName _ApplicantsApplicantAddressesAddressAddressLine2_QNAME = new QName("", "AddressLine2");
    private final static QName _ApplicantsApplicantAddressesAddressAddressLine1_QNAME = new QName("", "AddressLine1");
    private final static QName _ApplicantsApplicantAddressesAddressAddressLine5_QNAME = new QName("", "AddressLine5");
    private final static QName _ApplicantsApplicantAddressesAddressAddressLine4_QNAME = new QName("", "AddressLine4");
    private final static QName _ApplicantsApplicantAddressesAddressStateCode_QNAME = new QName("", "StateCode");
    private final static QName _ApplicantsApplicantAddressesAddressCity_QNAME = new QName("", "City");
    private final static QName _ApplicantsApplicantAddressesAddressAddressType_QNAME = new QName("", "AddressType");
    private final static QName _ApplicantsApplicantAddressesAddressPinCode_QNAME = new QName("", "PinCode");
    private final static QName _ApplicantsApplicantDsIDVisionCPVAttributes_QNAME = new QName("", "CPVAttributes");
    private final static QName _ApplicantsApplicantDsIDVisionReturnMessage_QNAME = new QName("", "ReturnMessage");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {// Do nothing because of X and Y.
    }

    /**
     * Create an instance of {@link Applicants }
     * 
     */
    public Applicants createApplicants() {
        return new Applicants();
    }

    /**
     * Create an instance of {@link Applicants.Applicant }
     * 
     */
    public Applicants.Applicant createApplicantsApplicant() {
        return new Applicants.Applicant();
    }

    /**
     * Create an instance of {@link Applicants.Applicant.DsCibilBureau }
     * 
     */
    public Applicants.Applicant.DsCibilBureau createApplicantsApplicantDsCibilBureau() {
        return new Applicants.Applicant.DsCibilBureau();
    }

    /**
     * Create an instance of {@link Applicants.Applicant.DsCibilBureau.Response }
     * 
     */
    public Applicants.Applicant.DsCibilBureau.Response createApplicantsApplicantDsCibilBureauResponse() {
        return new Applicants.Applicant.DsCibilBureau.Response();
    }

    /**
     * Create an instance of {@link Applicants.Applicant.Identifiers }
     * 
     */
    public Applicants.Applicant.Identifiers createApplicantsApplicantIdentifiers() {
        return new Applicants.Applicant.Identifiers();
    }

    /**
     * Create an instance of {@link Applicants.Applicant.Telephones }
     * 
     */
    public Applicants.Applicant.Telephones createApplicantsApplicantTelephones() {
        return new Applicants.Applicant.Telephones();
    }

    /**
     * Create an instance of {@link Applicants.Applicant.Addresses }
     * 
     */
    public Applicants.Applicant.Addresses createApplicantsApplicantAddresses() {
        return new Applicants.Applicant.Addresses();
    }

    /**
     * Create an instance of {@link Applicants.Applicant.DsIDVision }
     * 
     */
    public Applicants.Applicant.DsIDVision createApplicantsApplicantDsIDVision() {
        return new Applicants.Applicant.DsIDVision();
    }

    /**
     * Create an instance of {@link Applicants.Applicant.DsCibilBureau.DsCibilBureauData }
     * 
     */
    public Applicants.Applicant.DsCibilBureau.DsCibilBureauData createApplicantsApplicantDsCibilBureauDsCibilBureauData() {
        return new Applicants.Applicant.DsCibilBureau.DsCibilBureauData();
    }

    /**
     * Create an instance of {@link Applicants.Applicant.DsCibilBureau.DsCibilBureauStatus }
     * 
     */
    public Applicants.Applicant.DsCibilBureau.DsCibilBureauStatus createApplicantsApplicantDsCibilBureauDsCibilBureauStatus() {
        return new Applicants.Applicant.DsCibilBureau.DsCibilBureauStatus();
    }

    /**
     * Create an instance of {@link Applicants.Applicant.DsCibilBureau.Response.CibilBureauResponse }
     * 
     */
    public Applicants.Applicant.DsCibilBureau.Response.CibilBureauResponse createApplicantsApplicantDsCibilBureauResponseCibilBureauResponse() {
        return new Applicants.Applicant.DsCibilBureau.Response.CibilBureauResponse();
    }

    /**
     * Create an instance of {@link Applicants.Applicant.Identifiers.Identifier }
     * 
     */
    public Applicants.Applicant.Identifiers.Identifier createApplicantsApplicantIdentifiersIdentifier() {
        return new Applicants.Applicant.Identifiers.Identifier();
    }

    /**
     * Create an instance of {@link Applicants.Applicant.Telephones.Telephone }
     * 
     */
    public Applicants.Applicant.Telephones.Telephone createApplicantsApplicantTelephonesTelephone() {
        return new Applicants.Applicant.Telephones.Telephone();
    }

    /**
     * Create an instance of {@link Applicants.Applicant.Addresses.Address }
     * 
     */
    public Applicants.Applicant.Addresses.Address createApplicantsApplicantAddressesAddress() {
        return new Applicants.Applicant.Addresses.Address();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Applicants.Applicant.Addresses }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Addresses", scope = Applicants.Applicant.class)
    public JAXBElement<Applicants.Applicant.Addresses> createApplicantsApplicantAddresses(Applicants.Applicant.Addresses value) {
        return new JAXBElement<Applicants.Applicant.Addresses>(_ApplicantsApplicantAddresses_QNAME, Applicants.Applicant.Addresses.class, Applicants.Applicant.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DateOfBirth", scope = Applicants.Applicant.class)
    public JAXBElement<Object> createApplicantsApplicantDateOfBirth(Object value) {
        return new JAXBElement<Object>(_ApplicantsApplicantDateOfBirth_QNAME, Object.class, Applicants.Applicant.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ApplicantFirstName", scope = Applicants.Applicant.class)
    public JAXBElement<Object> createApplicantsApplicantApplicantFirstName(Object value) {
        return new JAXBElement<Object>(_ApplicantsApplicantApplicantFirstName_QNAME, Object.class, Applicants.Applicant.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Applicants.Applicant.DsCibilBureau }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DsCibilBureau", scope = Applicants.Applicant.class)
    public JAXBElement<Applicants.Applicant.DsCibilBureau> createApplicantsApplicantDsCibilBureau(Applicants.Applicant.DsCibilBureau value) {
        return new JAXBElement<Applicants.Applicant.DsCibilBureau>(_ApplicantsApplicantDsCibilBureau_QNAME, Applicants.Applicant.DsCibilBureau.class, Applicants.Applicant.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ApplicantType", scope = Applicants.Applicant.class)
    public JAXBElement<Object> createApplicantsApplicantApplicantType(Object value) {
        return new JAXBElement<Object>(_ApplicantsApplicantApplicantType_QNAME, Object.class, Applicants.Applicant.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Applicants.Applicant.Telephones }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Telephones", scope = Applicants.Applicant.class)
    public JAXBElement<Applicants.Applicant.Telephones> createApplicantsApplicantTelephones(Applicants.Applicant.Telephones value) {
        return new JAXBElement<Applicants.Applicant.Telephones>(_ApplicantsApplicantTelephones_QNAME, Applicants.Applicant.Telephones.class, Applicants.Applicant.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ApplicantLastName", scope = Applicants.Applicant.class)
    public JAXBElement<Object> createApplicantsApplicantApplicantLastName(Object value) {
        return new JAXBElement<Object>(_ApplicantsApplicantApplicantLastName_QNAME, Object.class, Applicants.Applicant.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Applicants.Applicant.DsIDVision }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DsIDVision", scope = Applicants.Applicant.class)
    public JAXBElement<Applicants.Applicant.DsIDVision> createApplicantsApplicantDsIDVision(Applicants.Applicant.DsIDVision value) {
        return new JAXBElement<Applicants.Applicant.DsIDVision>(_ApplicantsApplicantDsIDVision_QNAME, Applicants.Applicant.DsIDVision.class, Applicants.Applicant.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Gender", scope = Applicants.Applicant.class)
    public JAXBElement<Object> createApplicantsApplicantGender(Object value) {
        return new JAXBElement<Object>(_ApplicantsApplicantGender_QNAME, Object.class, Applicants.Applicant.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Applicants.Applicant.Identifiers }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Identifiers", scope = Applicants.Applicant.class)
    public JAXBElement<Applicants.Applicant.Identifiers> createApplicantsApplicantIdentifiers(Applicants.Applicant.Identifiers value) {
        return new JAXBElement<Applicants.Applicant.Identifiers>(_ApplicantsApplicantIdentifiers_QNAME, Applicants.Applicant.Identifiers.class, Applicants.Applicant.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ApplicantMiddleName", scope = Applicants.Applicant.class)
    public JAXBElement<Object> createApplicantsApplicantApplicantMiddleName(Object value) {
        return new JAXBElement<Object>(_ApplicantsApplicantApplicantMiddleName_QNAME, Object.class, Applicants.Applicant.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IdNumber", scope = Applicants.Applicant.Identifiers.Identifier.class)
    public JAXBElement<Object> createApplicantsApplicantIdentifiersIdentifierIdNumber(Object value) {
        return new JAXBElement<Object>(_ApplicantsApplicantIdentifiersIdentifierIdNumber_QNAME, Object.class, Applicants.Applicant.Identifiers.Identifier.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IdType", scope = Applicants.Applicant.Identifiers.Identifier.class)
    public JAXBElement<Object> createApplicantsApplicantIdentifiersIdentifierIdType(Object value) {
        return new JAXBElement<Object>(_ApplicantsApplicantIdentifiersIdentifierIdType_QNAME, Object.class, Applicants.Applicant.Identifiers.Identifier.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TelephoneType", scope = Applicants.Applicant.Telephones.Telephone.class)
    public JAXBElement<Object> createApplicantsApplicantTelephonesTelephoneTelephoneType(Object value) {
        return new JAXBElement<Object>(_ApplicantsApplicantTelephonesTelephoneTelephoneType_QNAME, Object.class, Applicants.Applicant.Telephones.Telephone.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TelephoneNumber", scope = Applicants.Applicant.Telephones.Telephone.class)
    public JAXBElement<Object> createApplicantsApplicantTelephonesTelephoneTelephoneNumber(Object value) {
        return new JAXBElement<Object>(_ApplicantsApplicantTelephonesTelephoneTelephoneNumber_QNAME, Object.class, Applicants.Applicant.Telephones.Telephone.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TelephoneExtension", scope = Applicants.Applicant.Telephones.Telephone.class)
    public JAXBElement<String> createApplicantsApplicantTelephonesTelephoneTelephoneExtension(String value) {
        return new JAXBElement<String>(_ApplicantsApplicantTelephonesTelephoneTelephoneExtension_QNAME, String.class, Applicants.Applicant.Telephones.Telephone.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ResidenceType", scope = Applicants.Applicant.Addresses.Address.class)
    public JAXBElement<Object> createApplicantsApplicantAddressesAddressResidenceType(Object value) {
        return new JAXBElement<Object>(_ApplicantsApplicantAddressesAddressResidenceType_QNAME, Object.class, Applicants.Applicant.Addresses.Address.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AddressLine3", scope = Applicants.Applicant.Addresses.Address.class)
    public JAXBElement<Object> createApplicantsApplicantAddressesAddressAddressLine3(Object value) {
        return new JAXBElement<Object>(_ApplicantsApplicantAddressesAddressAddressLine3_QNAME, Object.class, Applicants.Applicant.Addresses.Address.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AddressLine2", scope = Applicants.Applicant.Addresses.Address.class)
    public JAXBElement<Object> createApplicantsApplicantAddressesAddressAddressLine2(Object value) {
        return new JAXBElement<Object>(_ApplicantsApplicantAddressesAddressAddressLine2_QNAME, Object.class, Applicants.Applicant.Addresses.Address.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AddressLine1", scope = Applicants.Applicant.Addresses.Address.class)
    public JAXBElement<Object> createApplicantsApplicantAddressesAddressAddressLine1(Object value) {
        return new JAXBElement<Object>(_ApplicantsApplicantAddressesAddressAddressLine1_QNAME, Object.class, Applicants.Applicant.Addresses.Address.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AddressLine5", scope = Applicants.Applicant.Addresses.Address.class)
    public JAXBElement<Object> createApplicantsApplicantAddressesAddressAddressLine5(Object value) {
        return new JAXBElement<Object>(_ApplicantsApplicantAddressesAddressAddressLine5_QNAME, Object.class, Applicants.Applicant.Addresses.Address.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AddressLine4", scope = Applicants.Applicant.Addresses.Address.class)
    public JAXBElement<Object> createApplicantsApplicantAddressesAddressAddressLine4(Object value) {
        return new JAXBElement<Object>(_ApplicantsApplicantAddressesAddressAddressLine4_QNAME, Object.class, Applicants.Applicant.Addresses.Address.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "StateCode", scope = Applicants.Applicant.Addresses.Address.class)
    public JAXBElement<Object> createApplicantsApplicantAddressesAddressStateCode(Object value) {
        return new JAXBElement<Object>(_ApplicantsApplicantAddressesAddressStateCode_QNAME, Object.class, Applicants.Applicant.Addresses.Address.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "City", scope = Applicants.Applicant.Addresses.Address.class)
    public JAXBElement<Object> createApplicantsApplicantAddressesAddressCity(Object value) {
        return new JAXBElement<Object>(_ApplicantsApplicantAddressesAddressCity_QNAME, Object.class, Applicants.Applicant.Addresses.Address.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AddressType", scope = Applicants.Applicant.Addresses.Address.class)
    public JAXBElement<Object> createApplicantsApplicantAddressesAddressAddressType(Object value) {
        return new JAXBElement<Object>(_ApplicantsApplicantAddressesAddressAddressType_QNAME, Object.class, Applicants.Applicant.Addresses.Address.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PinCode", scope = Applicants.Applicant.Addresses.Address.class)
    public JAXBElement<Object> createApplicantsApplicantAddressesAddressPinCode(Object value) {
        return new JAXBElement<Object>(_ApplicantsApplicantAddressesAddressPinCode_QNAME, Object.class, Applicants.Applicant.Addresses.Address.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CPVAttributes", scope = Applicants.Applicant.DsIDVision.class)
    public JAXBElement<Object> createApplicantsApplicantDsIDVisionCPVAttributes(Object value) {
        return new JAXBElement<Object>(_ApplicantsApplicantDsIDVisionCPVAttributes_QNAME, Object.class, Applicants.Applicant.DsIDVision.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ReturnMessage", scope = Applicants.Applicant.DsIDVision.class)
    public JAXBElement<Object> createApplicantsApplicantDsIDVisionReturnMessage(Object value) {
        return new JAXBElement<Object>(_ApplicantsApplicantDsIDVisionReturnMessage_QNAME, Object.class, Applicants.Applicant.DsIDVision.class, value);
    }

}
