//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.01 at 12:33:58 PM IST 
//


package com.opl.mudra.api.cibil.model.highmark.retail;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="INQURIES-IN-LAST-SIX-MONTHS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LENGTH-OF-CREDIT-HISTORY-YEAR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LENGTH-OF-CREDIT-HISTORY-MONTH" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AVERAGE-ACCOUNT-AGE-YEAR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AVERAGE-ACCOUNT-AGE-MONTH" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NEW-ACCOUNTS-IN-LAST-SIX-MONTHS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NEW-DELINQ-ACCOUNT-IN-LAST-SIX-MONTHS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DER_ATTRIBUTE1_REMARKS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DER_ATTRIBUTE2_REMARKS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DER_ATTRIBUTE3_REMARKS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "DERIVED-ATTRIBUTES")
public class DERIVEDATTRIBUTES {

    @XmlElement(name = "INQURIES-IN-LAST-SIX-MONTHS")
    protected String inquriesinlastsixmonths;
    @XmlElement(name = "LENGTH-OF-CREDIT-HISTORY-YEAR")
    protected String lengthofcredithistoryyear;
    @XmlElement(name = "LENGTH-OF-CREDIT-HISTORY-MONTH")
    protected String lengthofcredithistorymonth;
    @XmlElement(name = "AVERAGE-ACCOUNT-AGE-YEAR")
    protected String averageaccountageyear;
    @XmlElement(name = "AVERAGE-ACCOUNT-AGE-MONTH")
    protected String averageaccountagemonth;
    @XmlElement(name = "NEW-ACCOUNTS-IN-LAST-SIX-MONTHS")
    protected String newaccountsinlastsixmonths;
    @XmlElement(name = "NEW-DELINQ-ACCOUNT-IN-LAST-SIX-MONTHS")
    protected String newdelinqaccountinlastsixmonths;
    @XmlElement(name = "DER_ATTRIBUTE1_REMARKS")
    protected String derattribute1REMARKS;
    @XmlElement(name = "DER_ATTRIBUTE2_REMARKS")
    protected String derattribute2REMARKS;
    @XmlElement(name = "DER_ATTRIBUTE3_REMARKS")
    protected String derattribute3REMARKS;

    /**
     * Gets the value of the inquriesinlastsixmonths property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINQURIESINLASTSIXMONTHS() {
        return inquriesinlastsixmonths;
    }

    /**
     * Sets the value of the inquriesinlastsixmonths property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINQURIESINLASTSIXMONTHS(String value) {
        this.inquriesinlastsixmonths = value;
    }

    /**
     * Gets the value of the lengthofcredithistoryyear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLENGTHOFCREDITHISTORYYEAR() {
        return lengthofcredithistoryyear;
    }

    /**
     * Sets the value of the lengthofcredithistoryyear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLENGTHOFCREDITHISTORYYEAR(String value) {
        this.lengthofcredithistoryyear = value;
    }

    /**
     * Gets the value of the lengthofcredithistorymonth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLENGTHOFCREDITHISTORYMONTH() {
        return lengthofcredithistorymonth;
    }

    /**
     * Sets the value of the lengthofcredithistorymonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLENGTHOFCREDITHISTORYMONTH(String value) {
        this.lengthofcredithistorymonth = value;
    }

    /**
     * Gets the value of the averageaccountageyear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVERAGEACCOUNTAGEYEAR() {
        return averageaccountageyear;
    }

    /**
     * Sets the value of the averageaccountageyear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVERAGEACCOUNTAGEYEAR(String value) {
        this.averageaccountageyear = value;
    }

    /**
     * Gets the value of the averageaccountagemonth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVERAGEACCOUNTAGEMONTH() {
        return averageaccountagemonth;
    }

    /**
     * Sets the value of the averageaccountagemonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVERAGEACCOUNTAGEMONTH(String value) {
        this.averageaccountagemonth = value;
    }

    /**
     * Gets the value of the newaccountsinlastsixmonths property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNEWACCOUNTSINLASTSIXMONTHS() {
        return newaccountsinlastsixmonths;
    }

    /**
     * Sets the value of the newaccountsinlastsixmonths property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNEWACCOUNTSINLASTSIXMONTHS(String value) {
        this.newaccountsinlastsixmonths = value;
    }

    /**
     * Gets the value of the newdelinqaccountinlastsixmonths property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNEWDELINQACCOUNTINLASTSIXMONTHS() {
        return newdelinqaccountinlastsixmonths;
    }

    /**
     * Sets the value of the newdelinqaccountinlastsixmonths property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNEWDELINQACCOUNTINLASTSIXMONTHS(String value) {
        this.newdelinqaccountinlastsixmonths = value;
    }

    /**
     * Gets the value of the derattribute1REMARKS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDERATTRIBUTE1REMARKS() {
        return derattribute1REMARKS;
    }

    /**
     * Sets the value of the derattribute1REMARKS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDERATTRIBUTE1REMARKS(String value) {
        this.derattribute1REMARKS = value;
    }

    /**
     * Gets the value of the derattribute2REMARKS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDERATTRIBUTE2REMARKS() {
        return derattribute2REMARKS;
    }

    /**
     * Sets the value of the derattribute2REMARKS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDERATTRIBUTE2REMARKS(String value) {
        this.derattribute2REMARKS = value;
    }

    /**
     * Gets the value of the derattribute3REMARKS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDERATTRIBUTE3REMARKS() {
        return derattribute3REMARKS;
    }

    /**
     * Sets the value of the derattribute3REMARKS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDERATTRIBUTE3REMARKS(String value) {
        this.derattribute3REMARKS = value;
    }

}
