//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.01 at 12:33:58 PM IST 
//


package com.opl.mudra.api.cibil.model.highmark.retail;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="ACCT-TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DATE-REPORTED" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OCCUPATION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="INCOME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="INCOME-FREQUENCY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="INCOME-INDICATOR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "EMPLOYMENT-DETAIL")
public class EMPLOYMENTDETAIL {

    @XmlElement(name = "ACCT-TYPE", required = true)
    protected String accttype;
    @XmlElement(name = "DATE-REPORTED", required = true)
    protected String datereported;
    @XmlElement(name = "OCCUPATION")
    protected String occupation;
    @XmlElement(name = "INCOME")
    protected String income;
    @XmlElement(name = "INCOME-FREQUENCY")
    protected String incomefrequency;
    @XmlElement(name = "INCOME-INDICATOR")
    protected String incomeindicator;

    /**
     * Gets the value of the accttype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACCTTYPE() {
        return accttype;
    }

    /**
     * Sets the value of the accttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACCTTYPE(String value) {
        this.accttype = value;
    }

    /**
     * Gets the value of the datereported property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDATEREPORTED() {
        return datereported;
    }

    /**
     * Sets the value of the datereported property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDATEREPORTED(String value) {
        this.datereported = value;
    }

    /**
     * Gets the value of the occupation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOCCUPATION() {
        return occupation;
    }

    /**
     * Sets the value of the occupation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOCCUPATION(String value) {
        this.occupation = value;
    }

    /**
     * Gets the value of the income property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINCOME() {
        return income;
    }

    /**
     * Sets the value of the income property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINCOME(String value) {
        this.income = value;
    }

    /**
     * Gets the value of the incomefrequency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINCOMEFREQUENCY() {
        return incomefrequency;
    }

    /**
     * Sets the value of the incomefrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINCOMEFREQUENCY(String value) {
        this.incomefrequency = value;
    }

    /**
     * Gets the value of the incomeindicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINCOMEINDICATOR() {
        return incomeindicator;
    }

    /**
     * Sets the value of the incomeindicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINCOMEINDICATOR(String value) {
        this.incomeindicator = value;
    }

}
