//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.01 at 12:33:58 PM IST 
//


package com.opl.mudra.api.cibil.model.highmark.retail;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AKA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SPOUSE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FATHER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MOTHER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DOB" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AGE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AGE-AS-ON" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RATION-CARD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PASSPORT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VOTERS-ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DRIVING-LICENCE-NO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PAN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GENDER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OWNERSHIP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ADDRESS-1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ADDRESS-2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ADDRESS-3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PHONE-1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PHONE-2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PHONE-3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EMAIL-1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EMAIL-2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BRANCH" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="KENDRA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MBR-ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LOS-APP-ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CREDT-INQ-PURPS-TYP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CREDT-INQ-PURPS-TYP-DESC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CREDIT-INQUIRY-STAGE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CREDT-RPT-ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CREDT-REQ-TYP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CREDT-RPT-TRN-DT-TM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AC-OPEN-DT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LOAN-AMOUNT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ENTITY-ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "REQUEST")
public class REQUEST {

    @XmlElement(name = "NAME")
    protected String name;
    @XmlElement(name = "AKA")
    protected String aka;
    @XmlElement(name = "SPOUSE")
    protected String spouse;
    @XmlElement(name = "FATHER")
    protected String father;
    @XmlElement(name = "MOTHER")
    protected String mother;
    @XmlElement(name = "DOB")
    protected String dob;
    @XmlElement(name = "AGE")
    protected String age;
    @XmlElement(name = "AGE-AS-ON")
    protected String ageason;
    @XmlElement(name = "RATION-CARD")
    protected String rationcard;
    @XmlElement(name = "PASSPORT")
    protected String passport;
    @XmlElement(name = "VOTERS-ID")
    protected String votersid;
    @XmlElement(name = "DRIVING-LICENCE-NO")
    protected String drivinglicenceno;
    @XmlElement(name = "PAN")
    protected String pan;
    @XmlElement(name = "GENDER")
    protected String gender;
    @XmlElement(name = "OWNERSHIP")
    protected String ownership;
    @XmlElement(name = "ADDRESS-1")
    protected String address1;
    @XmlElement(name = "ADDRESS-2")
    protected String address2;
    @XmlElement(name = "ADDRESS-3")
    protected String address3;
    @XmlElement(name = "PHONE-1")
    protected String phone1;
    @XmlElement(name = "PHONE-2")
    protected String phone2;
    @XmlElement(name = "PHONE-3")
    protected String phone3;
    @XmlElement(name = "EMAIL-1")
    protected String email1;
    @XmlElement(name = "EMAIL-2")
    protected String email2;
    @XmlElement(name = "BRANCH")
    protected String branch;
    @XmlElement(name = "KENDRA")
    protected String kendra;
    @XmlElement(name = "MBR-ID")
    protected String mbrid;
    @XmlElement(name = "LOS-APP-ID")
    protected String losappid;
    @XmlElement(name = "CREDT-INQ-PURPS-TYP")
    protected String credtinqpurpstyp;
    @XmlElement(name = "CREDT-INQ-PURPS-TYP-DESC")
    protected String credtinqpurpstypdesc;
    @XmlElement(name = "CREDIT-INQUIRY-STAGE")
    protected String creditinquirystage;
    @XmlElement(name = "CREDT-RPT-ID")
    protected String credtrptid;
    @XmlElement(name = "CREDT-REQ-TYP")
    protected String credtreqtyp;
    @XmlElement(name = "CREDT-RPT-TRN-DT-TM")
    protected String credtrpttrndttm;
    @XmlElement(name = "AC-OPEN-DT")
    protected String acopendt;
    @XmlElement(name = "LOAN-AMOUNT")
    protected String loanamount;
    @XmlElement(name = "ENTITY-ID")
    protected String entityid;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the aka property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAKA() {
        return aka;
    }

    /**
     * Sets the value of the aka property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAKA(String value) {
        this.aka = value;
    }

    /**
     * Gets the value of the spouse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPOUSE() {
        return spouse;
    }

    /**
     * Sets the value of the spouse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPOUSE(String value) {
        this.spouse = value;
    }

    /**
     * Gets the value of the father property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFATHER() {
        return father;
    }

    /**
     * Sets the value of the father property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFATHER(String value) {
        this.father = value;
    }

    /**
     * Gets the value of the mother property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMOTHER() {
        return mother;
    }

    /**
     * Sets the value of the mother property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMOTHER(String value) {
        this.mother = value;
    }

    /**
     * Gets the value of the dob property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDOB() {
        return dob;
    }

    /**
     * Sets the value of the dob property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDOB(String value) {
        this.dob = value;
    }

    /**
     * Gets the value of the age property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAGE() {
        return age;
    }

    /**
     * Sets the value of the age property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAGE(String value) {
        this.age = value;
    }

    /**
     * Gets the value of the ageason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAGEASON() {
        return ageason;
    }

    /**
     * Sets the value of the ageason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAGEASON(String value) {
        this.ageason = value;
    }

    /**
     * Gets the value of the rationcard property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRATIONCARD() {
        return rationcard;
    }

    /**
     * Sets the value of the rationcard property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRATIONCARD(String value) {
        this.rationcard = value;
    }

    /**
     * Gets the value of the passport property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPASSPORT() {
        return passport;
    }

    /**
     * Sets the value of the passport property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPASSPORT(String value) {
        this.passport = value;
    }

    /**
     * Gets the value of the votersid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVOTERSID() {
        return votersid;
    }

    /**
     * Sets the value of the votersid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVOTERSID(String value) {
        this.votersid = value;
    }

    /**
     * Gets the value of the drivinglicenceno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDRIVINGLICENCENO() {
        return drivinglicenceno;
    }

    /**
     * Sets the value of the drivinglicenceno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDRIVINGLICENCENO(String value) {
        this.drivinglicenceno = value;
    }

    /**
     * Gets the value of the pan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAN() {
        return pan;
    }

    /**
     * Sets the value of the pan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAN(String value) {
        this.pan = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGENDER() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGENDER(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the ownership property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOWNERSHIP() {
        return ownership;
    }

    /**
     * Sets the value of the ownership property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOWNERSHIP(String value) {
        this.ownership = value;
    }

    /**
     * Gets the value of the address1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADDRESS1() {
        return address1;
    }

    /**
     * Sets the value of the address1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADDRESS1(String value) {
        this.address1 = value;
    }

    /**
     * Gets the value of the address2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADDRESS2() {
        return address2;
    }

    /**
     * Sets the value of the address2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADDRESS2(String value) {
        this.address2 = value;
    }

    /**
     * Gets the value of the address3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADDRESS3() {
        return address3;
    }

    /**
     * Sets the value of the address3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADDRESS3(String value) {
        this.address3 = value;
    }

    /**
     * Gets the value of the phone1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPHONE1() {
        return phone1;
    }

    /**
     * Sets the value of the phone1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPHONE1(String value) {
        this.phone1 = value;
    }

    /**
     * Gets the value of the phone2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPHONE2() {
        return phone2;
    }

    /**
     * Sets the value of the phone2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPHONE2(String value) {
        this.phone2 = value;
    }

    /**
     * Gets the value of the phone3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPHONE3() {
        return phone3;
    }

    /**
     * Sets the value of the phone3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPHONE3(String value) {
        this.phone3 = value;
    }

    /**
     * Gets the value of the email1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEMAIL1() {
        return email1;
    }

    /**
     * Sets the value of the email1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEMAIL1(String value) {
        this.email1 = value;
    }

    /**
     * Gets the value of the email2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEMAIL2() {
        return email2;
    }

    /**
     * Sets the value of the email2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEMAIL2(String value) {
        this.email2 = value;
    }

    /**
     * Gets the value of the branch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBRANCH() {
        return branch;
    }

    /**
     * Sets the value of the branch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBRANCH(String value) {
        this.branch = value;
    }

    /**
     * Gets the value of the kendra property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKENDRA() {
        return kendra;
    }

    /**
     * Sets the value of the kendra property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKENDRA(String value) {
        this.kendra = value;
    }

    /**
     * Gets the value of the mbrid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMBRID() {
        return mbrid;
    }

    /**
     * Sets the value of the mbrid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMBRID(String value) {
        this.mbrid = value;
    }

    /**
     * Gets the value of the losappid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLOSAPPID() {
        return losappid;
    }

    /**
     * Sets the value of the losappid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLOSAPPID(String value) {
        this.losappid = value;
    }

    /**
     * Gets the value of the credtinqpurpstyp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCREDTINQPURPSTYP() {
        return credtinqpurpstyp;
    }

    /**
     * Sets the value of the credtinqpurpstyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCREDTINQPURPSTYP(String value) {
        this.credtinqpurpstyp = value;
    }

    /**
     * Gets the value of the credtinqpurpstypdesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCREDTINQPURPSTYPDESC() {
        return credtinqpurpstypdesc;
    }

    /**
     * Sets the value of the credtinqpurpstypdesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCREDTINQPURPSTYPDESC(String value) {
        this.credtinqpurpstypdesc = value;
    }

    /**
     * Gets the value of the creditinquirystage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCREDITINQUIRYSTAGE() {
        return creditinquirystage;
    }

    /**
     * Sets the value of the creditinquirystage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCREDITINQUIRYSTAGE(String value) {
        this.creditinquirystage = value;
    }

    /**
     * Gets the value of the credtrptid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCREDTRPTID() {
        return credtrptid;
    }

    /**
     * Sets the value of the credtrptid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCREDTRPTID(String value) {
        this.credtrptid = value;
    }

    /**
     * Gets the value of the credtreqtyp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCREDTREQTYP() {
        return credtreqtyp;
    }

    /**
     * Sets the value of the credtreqtyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCREDTREQTYP(String value) {
        this.credtreqtyp = value;
    }

    /**
     * Gets the value of the credtrpttrndttm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCREDTRPTTRNDTTM() {
        return credtrpttrndttm;
    }

    /**
     * Sets the value of the credtrpttrndttm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCREDTRPTTRNDTTM(String value) {
        this.credtrpttrndttm = value;
    }

    /**
     * Gets the value of the acopendt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACOPENDT() {
        return acopendt;
    }

    /**
     * Sets the value of the acopendt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACOPENDT(String value) {
        this.acopendt = value;
    }

    /**
     * Gets the value of the loanamount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLOANAMOUNT() {
        return loanamount;
    }

    /**
     * Sets the value of the loanamount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLOANAMOUNT(String value) {
        this.loanamount = value;
    }

    /**
     * Gets the value of the entityid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getENTITYID() {
        return entityid;
    }

    /**
     * Sets the value of the entityid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setENTITYID(String value) {
        this.entityid = value;
    }

}
