//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.01 at 12:33:58 PM IST 
//


package com.opl.mudra.api.cibil.model.highmark.retail;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SECONDARY-MATCH" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="ADDRESS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="DOB" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="PHONE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="PAN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="PASSPORT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="DRIVING-LICENSE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="VOTER-ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="E-MAIL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="RATION-CARD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element ref="{}LOAN-DETAILS" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "secondarymatch"
})
@XmlRootElement(name = "SECONDARY-MATCHES")
public class SECONDARYMATCHES {

    @XmlElement(name = "SECONDARY-MATCH")
    protected List<SECONDARYMATCH> secondarymatch;

    /**
     * Gets the value of the secondarymatch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the secondarymatch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSECONDARYMATCH().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SECONDARYMATCH }
     * 
     * 
     */
    public List<SECONDARYMATCH> getSECONDARYMATCH() {
        if (secondarymatch == null) {
            secondarymatch = new ArrayList<SECONDARYMATCH>();
        }
        return this.secondarymatch;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="ADDRESS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="DOB" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="PHONE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="PAN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="PASSPORT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="DRIVING-LICENSE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="VOTER-ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="E-MAIL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="RATION-CARD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element ref="{}LOAN-DETAILS" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class SECONDARYMATCH {

        @XmlElement(name = "NAME")
        protected String name;
        @XmlElement(name = "ADDRESS")
        protected String address;
        @XmlElement(name = "DOB")
        protected String dob;
        @XmlElement(name = "PHONE")
        protected String phone;
        @XmlElement(name = "PAN")
        protected String pan;
        @XmlElement(name = "PASSPORT")
        protected String passport;
        @XmlElement(name = "DRIVING-LICENSE")
        protected String drivinglicense;
        @XmlElement(name = "VOTER-ID")
        protected String voterid;
        @XmlElement(name = "E-MAIL")
        protected String email;
        @XmlElement(name = "RATION-CARD")
        protected String rationcard;
        @XmlElement(name = "LOAN-DETAILS")
        protected LOANDETAILS loandetails;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNAME() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNAME(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the address property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getADDRESS() {
            return address;
        }

        /**
         * Sets the value of the address property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setADDRESS(String value) {
            this.address = value;
        }

        /**
         * Gets the value of the dob property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDOB() {
            return dob;
        }

        /**
         * Sets the value of the dob property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDOB(String value) {
            this.dob = value;
        }

        /**
         * Gets the value of the phone property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPHONE() {
            return phone;
        }

        /**
         * Sets the value of the phone property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPHONE(String value) {
            this.phone = value;
        }

        /**
         * Gets the value of the pan property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPAN() {
            return pan;
        }

        /**
         * Sets the value of the pan property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPAN(String value) {
            this.pan = value;
        }

        /**
         * Gets the value of the passport property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPASSPORT() {
            return passport;
        }

        /**
         * Sets the value of the passport property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPASSPORT(String value) {
            this.passport = value;
        }

        /**
         * Gets the value of the drivinglicense property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDRIVINGLICENSE() {
            return drivinglicense;
        }

        /**
         * Sets the value of the drivinglicense property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDRIVINGLICENSE(String value) {
            this.drivinglicense = value;
        }

        /**
         * Gets the value of the voterid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVOTERID() {
            return voterid;
        }

        /**
         * Sets the value of the voterid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVOTERID(String value) {
            this.voterid = value;
        }

        /**
         * Gets the value of the email property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEMAIL() {
            return email;
        }

        /**
         * Sets the value of the email property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEMAIL(String value) {
            this.email = value;
        }

        /**
         * Gets the value of the rationcard property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRATIONCARD() {
            return rationcard;
        }

        /**
         * Sets the value of the rationcard property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRATIONCARD(String value) {
            this.rationcard = value;
        }

        /**
         * Gets the value of the loandetails property.
         * 
         * @return
         *     possible object is
         *     {@link LOANDETAILS }
         *     
         */
        public LOANDETAILS getLOANDETAILS() {
            return loandetails;
        }

        /**
         * Sets the value of the loandetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link LOANDETAILS }
         *     
         */
        public void setLOANDETAILS(LOANDETAILS value) {
            this.loandetails = value;
        }

    }

}
