package com.opl.mudra.api.enums.oneform;

/**
 * Created by ravina.panchal on 09-10-2018.
 */
public enum BankList {
    AbasahebPatilRendal("Abasaheb Patil Rendal Sahakari Bank Ltd","AbasahebPatilRendal","625","","","-"),
    AbhinandanUrbanCoOpBankLtd("Abhinandan Urban Co-Op Bank Ltd","AbhinandanUrbanCoOpBankLtd","612","","","ABHIURB"),
    AbhudayaCoOpp("Abhudaya Co-Op bank Ltd","Abhudaya Co-Op bank Ltd","151","","","-"),
    AbhyudayaCoOpBank("Abhyudaya CoOp Bank","","","ABHYUDAYA_CO_OP_BANK","","ABHYUDAYA CO"),
    AcmeBankLtd("Acme Bank Ltd","Acme Bank Ltd","998","","","-"),
    AdarshBank("Adarsh Bank, India","Adarsh Bank, India","161","","","-"),
    AdarshCoOperativeBankLtd("Adarsh Co Operative Bank Ltd","AdarshCoOperativeBankLtd","","Adarsh_Co_Operative_Bank_Ltd","","ADARSHBANK"),
    ADCB("ADCB", "ADCB, India","3","","","-"),
    AdinathCoOpBank ("Adinath Co Op Bank","AdinathCoOpBank","","AdinathCoOpBank","","ADINATH COOP"),
    AgrasenCoop ("Agrasen Co-op Urban Bank","AgrasenCoopUrbanBank","541","","","AGRASENCB"),
    AhmedabadDistrictCoOpBank("Ahmedabad District Co Op Bank","AhmedabadDistrictCoOpBank","","AHMEDABAD_DISTRICT_CO_OP_BANK","","AHMEDADCB"),
    AhmedabadDistrictCoOpBankLtd("Ahmedabad District Co-Op. Bank Ltd","Ahmedabad District Co-Op. Bank Ltd","414","","","AHMEDADCB"),
    AhmedabadMercantileCoOpp("Ahmedabad Mercantile Co-op Bank Ltd","Ahmedabad Mercantile Co-op Bank Ltd","79","","","AMCOBANKLIMITED"),
    AhmednagarShaharSahakariBank("Ahmednagar Shahar Sahakari Bank","AhmednagarShaharSahakariBank","709","","","SAHAR MARYADIT"),
    AirtelPaymentsBankIndia ("Airtel Payments Bank India","AirtelPaymentsBankIndia","267","AIRTEL_BANK","","-"),
    AkhandAnandCoOperativeBankLtdIndia  ("Akhand Anand CoOperative Bank Ltd India","AkhandAnandCoOperativeBankLtdIndia","247","AKHAND_ANAND","","AKHANDACBL"),
    AkolaDistrict  ("Akola District Central Co-Op. Bank Ltd","Akola District Central Co-Op. Bank Ltd","472","TJSB","","AKOLADCCB"),
    AkolaJantaCommercial("Akola Janata Commercial Co-Op. Bank Ltd, India","Akola Janata Commercial Co-Op. Bank Ltd, India","342","","","AKOLA"),
    AllahabadBankIndia  ("Allahabad Bank India","AllahabadBankIndia","4","ALLAHABAD","23","ALLAHABAD BANK"),
    AmarnathCoOpp("Amarnath Co-Op. Bank Ltd, India","Amarnath Co-Op. Bank Ltd, India","516","","","AMARCOOP"),
    AmbernathJaiHindCoOpBankLtdIndia ("Ambernath JaiHind CoOpBank Ltd India","AmbernathJaiHindCoOpBankLtdIndia","248","AMBERNATH_JAI_HIND_CO_OP_BANK","","AMBERNATH COOP"),
    AmericanExpressBankIndia ("American Express Bank India","AmericanExpressBankIndia","5","","","AMEX "),
    AndhraBankIndia ("Andhra Bank India","Andhra Bank India","6","ANDHRA_BANK","26","ANDHRA BANK"),
    AndhraPradeshGrameenaVikasBankIndia ("AndhraPradesh Grameena Vikas Bank India","AndhraPradeshGrameenaVikasBankIndia","193","","","APGM"),
    AndhraPragathiGrameena("Andhra Pragathi Grameena Bank","Andhra Pragathi Grameena Bank","499","","","APGM"),
    AnnasahabMagarSahakariBank ("Annasahab Magar Sahakari Bank","AnnasahabMagarSahakariBank","","ANNASAHAB_MAGAR_SAHAKARI_BANK","","ANNASAHEBMSB"),
    ApnaSahakariBank ("Apna Sahakari Bank","","","APNA_SAHAKARI_BANK","","APNA SAHA"),
    ArihantCoOpp("Arihant Co-operative Bank Ltd","Arihant Co-operative Bank Ltd","468","","","ARIHANTCOOP"),
    ArvindSahakariBank("Arvind Sahakari Bank","ArvindSahakariBank","182","","","ARVIND SAHAKARI"),
    AssamGraminVikashBankLtd("Assam Gramin Vikash Bank Ltd","AssamGraminVikashBankLtd","767","","","ASSAM GRAMEEN"),
    AssociateCoOpBank("Associate CoOpBank","","","ASSOCIATE_CO_OP_BANK","","ASSOCIATECO"),
    AUSmallFinanceBank("AU Small Finance Bank","AU Small Finance Bank, India","196", "AU_SMALL_FINANCE_BANK","","AU SFB"),
    AxisBankIndia("Axis Bank India","AxisBankIndia","2","AXIS","3","AXIS BANK"),
    BandhanBankIndia ("Bandhan Bank India","BandhanBankIndia","156","BANDHAN","","BANDHAN BANK"),
    BankOfAmerica ("BANK_OF_AMERICA","BankOfAmerica","","BANK_OF_AMERICA","","BANK OF AMERICA"),
    BankofBarodaIndia("Bank of Baroda India","BankofBarodaIndia","8","BANK_OF_BARODA","17","BOB"),
    BankofIndiaIndia ("Bank of India India","BankofIndiaIndia","9","BANK_OF_INDIA","14","BOI"),
    BankofMaharashtraIndia  ("Bank of Maharashtra India","BankofMaharashtraIndia","10","BANK_OF_MAHARASHTRA","27","BOM"),
    BankuraDistrictCentralCoOpBank("Bankura District Central Co-Op Bank","BankuraDistrictCentralCoOpBank","645","","","BANKURADCCB"),
    BaramatiCooperativeBank ("Baramati Co-operative Bank","BaramatiCooperativeBank","567","","","BARAMATI"),
    BarclaysBankIndia("Barclays Bank India","BarclaysBankIndia","73","","","BARCLAYS BANK"),
    BarodaRajasthanKshetriyaGraminBank ("BARODA RAJASTHAN KSHETRIYA GRAMIN BANK","BankofBarodaIndia","","BARODA_RAJASTHAN_KSHETRIYA_GRAMIN_BANK","","BARODARAJKGB"),
    BasseinCatholic ("Bassein Catholic","Bassein Catholic Co-Op. Bank Ltd","387","BASSEIN_CATHOLIC","","BASSEIN"),
    BhaginiNiveditaSahakariBankLtd("Bhagini Nivedita Sahakari Bank Ltd","BhaginiNiveditaSahakariBankLtd","694","","","BHAGININIVEDITA"),
    BhagyodayaCoOp("Bhagyodaya Co-Op. Bank Ltd","Bhagyodaya Co-Op. Bank Ltd","531","","","TBHAGCBL"),
    BhagyodayaCoOpBank ("Bhagyodaya Co Op Bank","BhagyodayaCoOpBank","","Bhagyodaya Co Op Bank","","TBHAGCBL"),
    Bharat  ("Bharat","","","BHARAT","","-"),
    BharatiSahakariBank("Bharati Sahakari Bank","BharatiSahakariBank","641","","","BHARTI"),
    BhartiyaMahilaBank  ("Bhartiya Mahila Bank","","","BHARTIYA_MAHILA_BANK","","BMBL"),
    BicholimUrbanCoOpBank("Bicholim Urban Co-Op Bank","BicholimUrbanCoOpBank","646","","","BICHOLIMCOP"),
    BiharGraminBank("Bihar Gramin Bank Ltd, India","Bihar Gramin Bank Ltd, India","536","","","BIHARGB"),
    BNPParibasIndia ("BNP Paribas India","BNPParibasIndia","7","","","BNP PARIBAS"),
    BombayMercantileCoOperativeBankLtdIndia ("Bombay Mercantile CoOperative Bank Ltd.India","BombayMercantileCoOperativeBankLtd.India","183","","","BOMMER"),
    BuldanaUrbanCoOpCreditSociety("Buldana Urban Co-Op Credit Society","BuldanaUrbanCoOpCreditSociety","695","","","BULDANACEN"),
    CanaraBankIndia ("Canara Bank India","CanaraBankIndia","11","CANARA","12","CANARA BANK"),
    CapitalLocalAreaBank("Capital Local Area Bank","Capital Local Area Bank","118","","","-"),
    CapitalSmallFinanceBankIndia ("Capital Small Finance Bank India","CapitalSmallFinanceBankIndia","222","CAPITAL_SMALL_FINANCE_BANK_LTD","","CAPITAL"),
    CatholicSyrianBankIndia ("Catholic Syrian Bank India","CatholicSyrianBankIndia","111","CATHOLIC_SYRIAN","","CATHOLIC SYRIAN"),
    CentralBankofIndiaIndia ("Central Bank of India India","CentralBankofIndiaIndia","12","CENTRAL_BANK","25","CENTRAL BANK"),
    CentralCoOperativeBank  ("Central CoOperative Bank","","","CENTRAL_CO_OPERATIVE_BANK","","CENTRALARA"),
    ChhattisgarhRajyaGraminBank("Chhattisgarh Rajya Gramin Bank","ChhattisgarhRajyaGraminBank","626","","","CHHATTISGARH RGB"),
    CitibankIndia("Citibank India","CitibankIndia","14","CITY","","CITIBANK"),
    CitizenCreditCoOpp("Citizen Credit Co-Op. Bank Ltd","Citizen Credit Co-Op. Bank Ltd","385","","","CITIZENCREDIT"),
    CitizensCoOpBankLtd("Citizens Co-Op. Bank Ltd","Citizens Co-Op. Bank Ltd","413","","","CITIZN RAJKOT"),
    CityUnionBankIndia  ("City Union Bank India","CityUnionBankIndia","57","CITY_UNION","","CITY UNION"),
    CorporationBankIndia ("Corporation Bank India","CorporationBankIndia","15","CORPORATION","24","CORP BANK"),
    CosmosBank  ("Cosmos Bank","","","COSMOS_BANK","","-"),
    CosmosCoOpp("Cosmos Co-op. Bank Ltd.","Cosmos Co-op. Bank Ltd.","83","","","COSMOS"),
    DBSBankIndia ("DBS Bank India","DBSBankIndia","16","DBS","","DBS"),
    DCBIndia ("DCB India","DCBIndia","18","DCB","","DCB"),
    DeccanMerchantsCoOpBank("Deccan Merchants Co Op Bank","Deccan Merchants Co Op Bank","","Deccan_Merchants_Co_Op_Bank","","DECCANMCOOP"),
    DeccanMerchantsCoOpp("Deccan Merchants Co-op Bank Ltd,","Deccan Merchants Co-op Bank Ltd,","120","","","DECCANMCOOP"),
    DeendayalNagariSahakari("Deendayal Nagari Sahakari","DeendayalNagariSahakari","542","","","DEENDAYAL"),
    DeepakSahakariBankLtdIndia  ("Deepak Sahakari Bank Ltd India","DeepakSahakariBankLtdIndia","249","","","DEEPAKSAH"),
    DenaBankIndia("Dena Bank India","DenaBankIndia","17","DENA_BANK","9","DENA BANK"),
    DeogiriNagariSahakariBank("Deogiri Nagari Sahakari Bank Ltd","DeogiriNagariSahakariBank","635","","","DEOGIRI"),
    DeutscheBankIndia("Deutsche Bank India","DeutscheBankIndia","49","DEUTSCHE_BANK","","DEUTSCHE BANK"),
    DhanalakshmiBankLtdIndia ("Dhanalakshmi Bank Ltd.India","DhanalakshmiBankLtd.India","71","DHANLAXMI","","DHANLAXMI BANK"),
    DMKJaoliBank("DMK Jaoli Bank","DMKJaoliBank","596","","","DATTATRAYA"),
    DNB ("DNB","","","DNB","","DNB"),
    DNS ("DNS","","","DNS","","DNS"),
    DombivliNagariSahakariBankIndia ("Dombivli Nagari Sahakari Bank India","DombivliNagariSahakariBankIndia","192","","","DOMBIVLI"),
    DrAnnasahebChougule("Dr. Annasaheb Chougule Urban Co-Op. Bank Ltd","Dr. Annasaheb Chougule Urban Co-Op. Bank Ltd","200","","","ANNASAHEB"),
    DrBabasahebAmbedkarMultistateCoOpBank("Dr Babasaheb Ambedkar Multistate Co Op Bank","DrBabasahebAmbedkarMultistateCoOpBank","","DR_BABASAHEB_AMBEDKAR_MULTISTATE_CO_OP_BANK","","DRSAHEB"),
    EquitasBankIndia ("Equitas Bank India","EquitasBankIndia","224","EQUITAS_SMALL_FINANCE_BANK","","-"),
    ESAFSmallFinanceBank("ESAF Small Finance Bank","ESAFSmallFinanceBank","589","","","ESAFSFB"),
    FederalBankIndia ("Federal Bank India","FederalBankIndia","19","FEDERAL","","FEDERAL BANK"),
    FincareSmallFinanceBank("Fincare Small Finance Bank","FincareSmallFinanceBank","592","","","FINCARESFB"),
    FinGrowthCoOpbankLtdIndia("FinGrowth CoOpbank Ltd.India","FinGrowthCoOpbankLtd.India","152","","","URBAN JAIPUR"),
    FinoPaymentBank("Fino Payment Bank ","Fino Payment Bank ","388","","","-"),
    GandhibagSahakariBankLtd("Gandhibag Sahakari Bank Ltd","GandhibagSahakariBankLtd","543","","","GANDHINAG"),
    GPParsikBankIndia("GPParsik Bank India","GPParsikBankIndia","173","GP_PARSIK_BANK","","GPPARSIK"),
    GreaterBombayCoopBankLtdIndia("Greater Bombay CoopBank Ltd India","GreaterBombayCoopBankLtdIndia","265","GREATER_BOMBAY","","TGBCBL"),
    GujaratAmbujaCoOpBankLtdIndia("Gujarat Ambuja CoOpBank Ltd.India","GujaratAmbujaCoOpBankLtd.India","186","","","GUJARAT AMBUJA"),
    GujaratStateCoOpBank("Gujarat State Co Op Bank","GujaratStateCoOpBank","","Gujarat_State_Co_Op_Bank","","GUJSTATECOOP"),
    GujaratStateCoOpBankLtd("Gujarat State Co-Op. Bank Ltd","GujaratStateCo-Op.BankLtd","530","","","GUJSTATECOOP"),
    HastiCoOpBank  ("Hasti Co-Op Bank","HastiCoOpBank","637","","","HASTICBL"),
    HDFCBankIndia("HDFC Bank India","HDFCBankIndia","20","HDFC","","HDFC BANK"),
    HimatnagarNagarikSahakari("Himatnagar Nagarik Sahakari Bank Ltd","Himatnagar Nagarik Sahakari Bank Ltd","508","","","HIMATNAG"),
    HindusthanCoOpBankLtdIndia  ("Hindusthan CoOpBank Ltd India","HindusthanCoOpBankLtdIndia","260","","","HINDUCB"),
    HPStateCoOpBankLtd ("HP State Co-Op Bank Ltd","HPStateCo-OpBankLtd","554","","","HP STATE COOP"),
    HSBCIndia("HSBC India","HSBCIndia","21","HSBC","","HSBC"),
    ICICIBankIndia  ("ICICI Bank India","ICICIBankIndia","22","ICICI","4","ICICI BANK"),
    IDBIIndia("IDBI India","IDBIIndia","23","IDBI","5","IDBI LTD"),
    IDFCBankIndia("IDFC Bank India","IDFCBankIndia","140","IDFC","8","IDFC FIRST BANK"),
    ImphalUrbanCooperative("Imphal Urban Co-operative Bank Ltd","Imphal Urban Co-operative Bank Ltd","469","","","IMPHALUCBL"),
    IndianBankIndia ("Indian Bank India","IndianBankIndia","24","INDIAN_BANK","13","INDIAN BANK"),
    IndianOverseasBankIndia ("Indian Overseas Bank India","IndianOverseasBankIndia","25","INDIAN_OVERSEAS","28","IOB"),
    IndoreParasparSahakariBank ("Indore Paraspar Sahakari Bank","IndoreParasparSahakariBank","642","","","INDORE PARASPAR"),
    IndraprasthaSehkariBank ("Indraprastha Sehkari Bank","","","INDRAPRASTHA_SEHKARI_BANK","","INDRAPRASTHA"),
    IndrayaniCoOpBank  ("Indrayani Co-Op Bank","IndrayaniCoOpBank","638","","","INDRAYANI"),
    IndusIndBankIndia("IndusInd Bank India","IndusIndBankIndia","26","INDUSIND","","INDUSIND BANK"),
    IrinjalakudaTownCoOpBankLtd ("Irinjalakuda Town Co-Op Bank Ltd","IrinjalakudaTownCoOpBankLtd","692","","","IRINJALAKUDA"),
    J_and_K_BankIndia("J&K Bank India","J&KBankIndia","27","JAMMU_KASHMIR","","J&K BANK"),
    JaiTuljabhavaniUrban("Jai Tuljabhavani Urban Co-Op Bank","Jai Tuljabhavani Urban Co-Op Bank","479","","","JAITULJA"),
    JaiTuljabhavaniUrbanCoOpBank("Jai Tuljabhavani Urban Co Op Bank","JaiTuljabhavaniUrbanCoOpBank","252","Jai_Tuljabhavani_Urban_Co_Op_Bank","","JAITULJA"),
    JalgaonJantaBank("Jalgaon Janata Bank","Jalgaon Janata Bank","115","","","-"),
    JalgaonPeoplesCoOpBank("Jalgaon Peoples Co-Op Bank Ltd","Jalgaon Peoples Co-Op Bank Ltd","509","","","JALGAON PCBL"),
    JaloreNagrikSahBankLtdIndia ("Jalore Nagrik Sah Bank Ltd India","JaloreNagrikSahBankLtdIndia","250","","","JALORENAG"),
    JamiaCoOpBankLtd("Jamia Co-Op Bank Ltd","JamiaCoOpBankLtd","705","","","JAMIACOOP"),
    JamshedpurUrbanCoOpBankLtd("Jamshedpur Urban Co-Op Bank Ltd","JamshedpurUrbanCoOpBankLtd","706","","","JAMSHEDPUR COOP"),
    JanakalyanSahakariBank  ("Janakalyan Sahakari Bank","","","JANAKALYAN_SAHAKARI_BANK","","JANAKALYAN SAH"),
    JanasevaSahakariBankLtdIndia ("Janaseva Sahakari Bank Ltd India","JanasevaSahakariBankLtdIndia","251","JANASEVA_SAHAKARI_BANK","","JANASEVA "),
    JanaSmallFinanceBank("Jana Small Finance Bank","Jana Small Finance Bank","538","","","-"),
    JanataSahakariBankIndia ("Janata Sahakari Bank India","JanataSahakariBankIndia","158","JANATA_SAHAKARI_BANK","","JANATA SATARA"),
    JanathaSevaCoOpp("Janatha Seva Co-Op. Bank Ltd,","Janatha Seva Co-Op. Bank Ltd,","394","","","JANATHASEV"),
    JankalyanSahakariBank("Jankalyan Sahakari Bank","Jankalyan Sahakari Bank","466","","","JANKALYANCBL"),
    JayPrakashNarayanNagariSahakariBankLtdIndia ("Jay Prakash Narayan Nagari Sahakari Bank LtdIndia","JayPrakashNarayanNagariSahakariBankLtdIndia","252","","","-"),
    JharkhandRajyaGraminBank("Jharkhand Rajya Gramin Bank","JharkhandRajyaGraminBank","651","","","JHARKHAND"),
    JijamataMahilaSahakariBank("Jijamata Mahila Sahakari Bank","JijamataMahilaSahakariBank","644","","","JIJAMATA "),
    JivanCommercialCoOpBankLtd("Jivan Commercial Co-Op Bank Ltd","JivanCommercialCoOpBankLtd","708","","","JIVAN"),
    KallappannaAwadeBank("Kallappanna Awade Bank","KallappannaAwadeBank","","Kallappanna_Awade_Bank","","KALLAPPANNA"),
    KallappannaAwadeIchalkaranjiJanataSahakariBank("Kallappanna Awade Ichalkaranji Janata Sahakari Bank","Kallappanna Awade Ichalkaranji Janata Sahakari Bank","412","","","KALLAPPANNA"),
    KalyanJanataSahakariBankLtdIndia ("Kalyan Janata Sahakari Bank Ltd India","KalyanJanataSahakariBankLtdIndia","343","KALYAN_JANATA_SAHAKARI_BANK","","KALYANJAN"),
    KangraCoopBankLtdIndia  ("Kangra CoopBank Ltd India","KangraCoopBankLtdIndia","225","KANGRA_CO_OP_BANK","","KANGRACBL"),
    KankariaaManinagarNagSahBankLtd("Kankariaa Maninagar NAG.SAH.BANK LTD","KankariaaManinagarNag.Sah.BankLtd","693","KANKARIAA_MANINAGAR_NAG_SAH_BANK_LTD","","KANKARIA"),
    KarnalaNagariSahakariBank("Karnala Nagari Sahakari Bank","KarnalaNagariSahakariBank","647","","","-"),
    KarnatakaBankIndia  ("Karnataka Bank India","KarnatakaBankIndia","51","KARNATAKA","","KARNATAKA BANK"),
    KarnatakaCentralCoOpBankLtd("Karnataka Central Co-Op Bank Ltd","KarnatakaCentralCoOpBankLtd","768","","","KARNCENTCO"),
    KarnatakaVikasGrameenaBank("Karnataka Vikas Grameena Bank Ltd","Karnataka Vikas Grameena Bank Ltd","533","","","KARNATAKA GRAMEEN"),
    KarurVysyaBankIndia ("KarurVysya Bank India","KarurVysyaBankIndia","50","KARUR_VYASA","","-"),
    KashipurUrbanCoOpBankLtdIndia("Kashipur Urban CoOp Bank Ltd.India","KashipurUrbanCoOpBankLtd.India","164","","","KASHIPURUCBL"),
    KaveriGrameenaBank("Kaveri Grameena Bank","Kaveri Grameena Bank","501","","","KAVERIGB"),
    KEBHanaBank("KEB Hana Bank","KEBHanaBank","754","","","KEBHANA"),
    KeralaGraminBankLtd("Kerala Gramin Bank Ltd","KeralaGraminBankLtd","539","","","KERALAGB"),
    KhamgaonUrbankCoopBankLtdIndia  ("Khamgaon Urbank CoopBank Ltd India","KhamgaonUrbankCoopBankLtdIndia","227","","","TKHAMUCBL"),
    KhardahCoOpBankLtd("Khardah Co-Op Bank Ltd","KhardahCoOpBankLtd","756","","","KHARDAHCO"),
    KokanMercantileCoOp("Kokan Mercantile Co-Op","Kokan Mercantile Co-Op","513","","","KOKAN MER"),
    KolhapurDistrictCentralCoOperativeBankLtd("Kolhapur District Central Co-Operative Bank Ltd","KolhapurDistrictCentralCo-OperativeBankLtd","578","","","-"),
    KolhapurMahilaSahakariBankLtd("Kolhapur Mahila Sahakari Bank Ltd","KolhapurMahilaSahakariBankLtd","607","","","Kolhapur Mahila"),
    KolhapurUrbanCoOpBank("Kolhapur Urban Co-Op Bank","KolhapurUrbanCoOpBank","613","","","KOLHABAN"),
    KopargaonPeoplesCoOpBank("Kopargaon Peoples Co-Op Bank","KopargaonPeoplesCoOpBank","639","","","KOPARBANK"),
    KotakMahindra_IngVysyaBankIndia ("Kotak Mahindra/Ing Vysya Bank India","KotakMahindra/IngVysyaBankIndia","28","KOTAK","30","KOTAK BANK"),
    KukarwadaNagrik("Kukarwada Nagrik Sahakari Bank","Kukarwada Nagrik Sahakari Bank","399","","","KUKARWADA"),
    KurmanchalBank("Kurmanchal Bank","KurmanchalBank","","KURMANCHAL_BANK","","KURMAN"),
    KurmanchalBankIndia ("Kurmanchal Bank India","KurmanchalBankIndia","165","","","KURMAN"),
    LakshmiVilasBankIndia("Lakshmi Vilas Bank India","LakshmiVilasBankIndia","77","LAKSHMI_VILAS","","LAKSHMI VILAS"),
    LangpiDehangiRuralBank("Langpi Dehangi Rural Bank","Langpi Dehangi Rural Bank","503","","","LANGPIDRB"),
    LaturUrbanCoOp("Latur Urban Co-Op","Latur Urban Co-Op","476","","","LATUR URBAN"),
    LokmangalCoOpBank("Lokmangal Co-Op Bank","Lokmangal Co-Op Bank","510","","","LOKMANGAL"),
    MahanagarCoOpp("Mahanagar Co-Op. Bank Ltd","Mahanagar Co-Op. Bank Ltd","400","","","-"),
    MaharashtraGraminBank("Maharashtra Gramin Bank","MaharashtraGraminBank","511","Maharashtra_Gramin_Bank","","MGB"),
    MaharastraGraminBankIndia("Maharastra GraminBank India","MaharastraGraminBankIndia","175","","","MGB"),
    MahaveerCoOpUrbanBankLtd("Mahaveer Co-Op Urban Bank Ltd","MahaveerCoOpUrbanBankLtd","710","","","MAHAVEERBANK"),
    MaheshBankIndia ("Mahesh Bank India","MaheshBankIndia","174","MAHESH_BANK","","-"),
    MaheshSahakariBankLTD("Mahesh Sahakari Bank LTD","","","MAHESH_SAHAKARI_BANK_LTD","","MAHESH SAH"),
    MaheshUrbanCoOperativeBankLtd("Mahesh Urban Co-Operative Bank Ltd","MaheshUrbanCo-OperativeBankLtd","577","","","MAHESHURB"),
    MahilaVikashCoOpBankLtdIndia ("Mahila Vikash CoOp Bank Ltd India","MahilaVikashCoOpBankLtdIndia","261","","","MAHILAVIKAS"),
    ManinagarCoOpp("Maninagar Co-Op. Bank Ltd","Maninagar Co-Op. Bank Ltd","384","","","MANINAGARCP"),
    ManoramaCoOpBankLtd("Manorama Co-Op. Bank Ltd","ManoramaCo-Op.BankLtd","529","","","-"),
    ManoramaCoOpBankSolapur("Manorama Co Op Bank Solapur","Manorama Co Op Bank Solapur","","Manorama_Co_op_Bank_Solapur","","-"),
    ManviPattanaSouharadaSahakariBank("Manvi Pattana Souharada Sahakari Bank","","","MANVI_PATTANA_SOUHARADA_SAHAKARI_BANK","","MANVI PATTANA"),
    MehsanaUrbanCoOpBank ("Mehsana Urban CoOp Bank","Mehsana Urban CoOp Bank","91","MEHSANA_URBAN_CO_OP_BANK","","MEHASANA"),
    MercantileCoOpBank("Mercantile Co-Op Bank","Mercantile Co-Op Bank","511","","","-"),
    MjalgaonJalgaonJanataSahakariBank("Mjalgaon Jalgaon Janata Sahakari Bank","","","MJALGAON_JANATA_SAHAKARI_BANK","","-"),
    ModelCoOperativeBank ("Model CoOperative Bank","","","MODEL_CO_OPERATIVE_BANK","","MODEL"),
    MsantSopankakaSahakariBankLtdIndia  ("Msant Sopankaka Sahakari Bank Ltd India","MsantSopankakaSahakariBankLtdIndia","369","","","-"),
    MSCoOpBankLtd("M S Co-Op. Bank Ltd","M S Co-Op. Bank Ltd","460","","","MSCOOPBANK"),
    NagarikSamabayBankLtd("Nagarik Samabay Bank Ltd","NagarikSamabayBankLtd","605","","","NAGARIK"),
    NagarUrbanCoOpp("Nagar Urban Co-Op. Bank Ltd","Nagar Urban Co-Op. Bank Ltd","392","","","NAGAR AHMED"),
    NagpurNagarikSahakariBank("Nagpur Nagarik Sahakari Bank","Nagpur Nagarik Sahakari Bank","147","NAGPUR_NAGARIK_SAHAKARI_BANK","","NAGPURNAG"),
    NainitalBankIndia("Nainital Bank India","NainitalBankIndia","166","NAINITAL","","NAINITAL BANK"),
    NandedMerchantsCoOpBankLtd("Nanded Merchants Co-Op Bank Ltd","NandedMerchantsCo-OpBankLtd","555","","","TNANDMCBL"),
    NationalBank("National Bank","NationalBank","623","","","-"),
    NavapurMercantileCoOpBankLtdIndia("Navapur Mercantile CoOp Bank Ltd India","NavapurMercantileCoOpBankLtdIndia","253","","","NAVAPURCOOP"),
    NavjeevanCoOpBankLtd("Navjeevan Co-Op Bank Ltd","NavjeevanCo-OpBankLtd","572","","","TNAVCBL"),
    NavnirmanCoopBankLtdIndia("Navnirman CoopBank Ltd India","NavnirmanCoopBankLtdIndia","197","","","NAVNIRMAN"),
    NavsarjanIndustrialCoOpBankLtd("Navsarjan Industrial Co-Op. Bank Ltd","Navsarjan Industrial Co-Op. Bank Ltd","458","","","NAVSARJAN"),
    NawanagarCoopBankLtdIndia("Nawanagar CoopBank Ltd India","NawanagarCoopBankLtdIndia","199","","","NAWCBL"),
    NeelkantCoOpBank("Neelkant Co-Op. Bank","NeelkantCo-Op.Bank","","NEELKANT_CO_OP_BANK","","NEELKAPUR"),
    NeelkanthCoOpBank("Neelkanth Co-Op. Bank","Neelkanth Co-Op. Bank","474","","","NEELKAPUR"),
    NewIndiaCoOpBankLtdIndia ("NewIndia CoOpBank Ltd.India","NewIndiaCoOpBankLtd.India","178","NEW_INDIA_CO_OP_BANK","","NEW INDIA"),
    NidhiCoOpBankLtd("Nidhi Co-Op. Bank Ltd","Nidhi Co-Op. Bank Ltd","459","","","NIDHI"),
    NKGSB("NKGSB Bank","NKGSB Bank","139","","","-"),
    NkgsbCoOpBank("NKGSB Co Op Bank","NkgsbCoOpBank","","NKGSB_CO_OP_BANK","","NKGSB"),
    NoidaCommercialCoOp("Noida Commercial Co-Op","Noida Commercial Co-Op","477","Noida_Commercial_Co_Op_Bank","","NOIDA COOP"),
    NutanNagaikSahakariBank ("Nutan Nagaik Sahakari Bank","Nutan Nagaik Sahakari Bank","376","NUTAN_NAGARIK_SAHAKARI_BANK","","NUTANSAHAKARI"),
    OceanFirst  ("Ocean First","","","OCEAN_FIRST","","-"),
    OmkarNagreeyaSahakariBank  ("Omkar Nagreeya Sahakari Bank","OmkarNagreeyaSahakariBank","502","","","ONSBL"),
    OmprakashDeoraPeoplesCoOpBankLtdIndia("Omprakash Deora Peoples CoOpBank Ltd India","OmprakashDeoraPeoplesCoOpBankLtdIndia","254","","","PEOPLECOOP"),
    OrientalBankofCommerceIndia ("Oriental Bank of Commerce India","OrientalBankofCommerceIndia","29","ORIENTAL_BANK","21","OBC"),
    OsmanabadJanataSahakariBankLtdIndia ("Osmanabad Janata Sahakari Bank Ltd India","OsmanabadJanataSahakariBankLtdIndia","266","","","OSMANJAN"),
    PadmavathiCoOpUrbanBank("Padmavathi Co Op Urban Bank","PadmavathiCoOpUrbanBank","","PADMAVATHI_CO_OP_URBAN_BANK","","PADMAVATHI"),
    PalusSahakariBankLtd("Palus Sahakari Bank Ltd","PalusSahakariBankLtd","772","","","PSBL"),
    PandharpurUrbanCoopBankLtdIndia ("Pandharpur Urban CoopBank Ltd India","PandharpurUrbanCoopBankLtdIndia","194","","","PANDHARPUR URB"),
    PanipatUrbanCoOpBankLtd("Panipat Urban Co-Op. Bank Ltd","Panipat Urban Co-Op. Bank Ltd","456","","","PANIPATURBAN"),
    ParshwanathCoOpBankLtdIndia ("Parshwanath CoOp.BankLtd.India","ParshwanathCoOp.BankLtd.India","177","","","PARSHWANATH"),
    PatanNagrikBank("Patan Nagarik Sahakari Bank Ltd","PatanNagrikBank","462","","","PATANNAG"),
    PavanaSahakariBankLtd("Pavana Sahakari Bank Ltd","PavanaSahakariBankLtd","597","","","PAVANA PUNE"),
    PaytmPaymentsBankIndia  ("Paytm Payments Bank India","PaytmPaymentsBankIndia","268","","","-"),
    PeoplesCoOpBankLtdIndia ("Peoples CoOpBank Ltd India","PeoplesCoOpBankLtdIndia","255","","","PEOPLESCOOPKANPUR"),
    PimpriChinchwadSahakariBank("Pimpri Chinchwad Sahakari Bank","Pimpri Chinchwad Sahakari Bank","505","","","PIMPRI "),
    PochampallyBank("Pochampally Bank","Pochampally Bank","659","","","POCHAMCOB"),
    PostOfficeSavingBank("Post Office Saving Bank","PostOfficeSavingBank","598","","","-"),
    PragathiCoOperativeBankLtd("Pragathi Co Operative Bank Ltd","PragathiCoOperativeBankLtd","576","","","PRAGATHI"),
    PragatiSahakariBank("Pragati Sahakari Bank","Pragati Sahakari Bank","480","","","PRAGATISAH"),
    PrathamaBank("Prathama Bank","Prathama Bank","396","","","PRATHAMA"),
    PreranaCoOpBank("Prerana Co-Op. Bank","Prerana Co-Op. Bank","525","","","PRERANA"),
    PrimeCoOpBank("Prime Co-Op. Bank","Prime Co-Op. Bank","520","PRIME_BANK","","PRIMECO"),
    PriyadarshiniUrbanCoOpBankLtd("Priyadarshini Urban Co-Op Bank Ltd","PriyadarshiniUrbanCoOpBankLtd","704","","","PRIYABANK"),
    ProgressiveMercCoOp("Progressive Merc. Co-Op","Progressive Merc. Co-Op","475","","","PROGMER"),
    PuduppadiServiceCoOperativeBankLtd("Puduppadi Service Co-Operative Bank Ltd","PuduppadiServiceCo-OperativeBankLtd","587","","","-"),
    PuneDistrictCentralCoOperativeBankLtd("Pune District Central Co-Operative Bank Ltd","PuneDistrictCentralCo-OperativeBankLtd","599","","","PUNEDCCB"),
    PunePeoplesCoOpBankIndia ("Pune Peoples CoOpBank India","PunePeoplesCoOpBankIndia","189","PUNE_PEOPLES_CO_OP_BANK","","-"),
    PuneUrbanCoOpBankLtdIndia("Pune Urban CoOpBank Ltd India","PuneUrbanCoOpBankLtdIndia","324","","","PUNE URBAN"),
    PunjabandSindBankIndia  ("Punjaband Sind Bank India","PunjabandSindBankIndia","31","PUNJAB_SIND","20","PUNJAB & SIND "),
    PunjabMaharashtaraCoOpBank  ("Punjab Maharashtara CoOp Bank","Punjab Maharashtara CoOp Bank","78","PUNJAB_MAHARASHTRA_CO_OP_BANK","","PMCBANK"),
    PunjabNationalBankIndia ("Punjab National Bank India","PunjabNationalBankIndia","30","PNB","18","PNB"),
    PurvanchalBank("Purvanchal Bank","PurvanchalBank","","PURVANCHAL BANK","","PURVANCHALB"),
    PurvanchalBankLtd("Purvanchal Bank Ltd","Purvanchal Bank Ltd","471","","","PURVANCHALB"),
    PusadUrbanCoOpBankLtdIndia  ("Pusad Urban CoOpBank Ltd India","PusadUrbanCoOpBankLtdIndia","257","","","PUSADURBCO"),
    RaboBank ("Rabo Bank","RaboBank","557","","","-"),
    RaigadDistrictCentralCoOpBankLtd ("Raigad District Central Co-Op Bank Ltd","RaigadDistrictCentralCo-OpBankLtd","553","","","RAIGADDCCB"),
    RajarambapuSahakariBankLtd ("Rajarambapu Sahakari Bank Ltd","RajarambapuSahakariBankLtd","585","","","RAJARAM"),
    RajarshiShahuSahakariBankLtd ("Rajarshi Shahu Sahakari Bank Ltd","RajarshiShahuSahakariBankLtd","573","","","RAJSHAU"),
    RajasthanMarudharaGraminBank("Rajasthan Marudhara Gramin Bank","Rajasthan Marudhara Gramin Bank","390","","","RAJMARGB"),
    RajgurunagarSahakariBankLtd ("Rajgurunagar Sahakari Bank Ltd","RajgurunagarSahakariBankLtd","707","","","RAJGURUNAGAR"),
    RajkotCommercialCoOp("Rajkot Commercial Co-Op","Rajkot Commercial Co-Op","517","","","RAJCOOP"),
    RajkotNagarikSahakariBankLtd ("Rajkot Nagarik Sahakari Bank Ltd","RajkotNagarikSahakariBankLtd","608","","","RAJKOT SAHA"),
    RajkotPeoplesCoOpBankLtdIndia("Rajkot Peoples CoOpBank Ltd.India","RajkotPeoplesCoOpBankLtd.India","195","","","RAJKOTPCBL"),
    RamgarhiaCoOpBank("Ramgarhia Co-Op. Bank ","Ramgarhia Co-Op. Bank ","527","","","RAMGARHIA COOP"),
    RBL_Ratnakar_BankIndia  ("RBL(Ratnakar)BankIndia","RBL(Ratnakar)BankIndia","81","RBL","6","RBL"),
    RBS_ABNAMRO_India("RBS(ABNAMRO)India","RBS(ABNAMRO)India","48","RBS","","RBS"),
    Rmgb("Rmgb","RMGB","527","RMGB","","RAJMARGB"),
    RoyalBankOfScotland ("Royal Bank of Scotland","RoyalBankOfScotland","","RBS","","-"),
    SadhanaSahakariBankLtd("Sadhana Sahakari Bank Ltd","SadhanaSahakariBankLtd","537","","","SADHANA"),
    SahebraoDeshmukhCoOperativeBankLtd("Sahebrao Deshmukh Co-Operative Bank Ltd","SahebraoDeshmukhCo-OperativeBankLtd","600","","","SAHEBRAODES"),
    SahydriSahakariBank("Sahydri Sahakari Bank","SahydriSahakariBank","","SAHYDRI_SAHAKARI_BANK","","SAHYADRI"),
    SaibabaNagariSahakariBankLtd("Saibaba Nagari Sahakari Bank Ltd","SaibabaNagariSahakariBankLtd","728","","","SAIBABA"),
    SamarthSahakariBankIndia ("Samarth Sahakari Bank India","SamarthSahakariBankIndia","159","","","SAMARTHA NAG"),
    SamataSahkariBankLtd("Samata Sahkari Bank Ltd","SamataSahkariBankLtd","535","","","SAMATA"),
    SangliDistrictCentralCoOpBankLtd("Sangli District Central Co-Op Bank Ltd","SangliDistrictCentralCoOpBankLtd","769","","","-"),
    SangliUrbanCoOpBankLtd("Sangli Urban Co-Op. Bank Ltd","Sangli Urban Co-Op. Bank Ltd","455","","","SANGLIURBAN"),
    SangolaUrbanCoOp("Sangola Urban Co-Op","Sangola Urban Co-Op","523","","","-"),
    SangolaUrbanCoOperativeBankLtd("Sangola Urban Co Operative Bank Ltd","Sangola Urban Co Operative Bank Ltd","","SANGOLA_URBAN_CO_OPERATIVE_BANK_LTD","","SANGOLACO"),
    SanmathiSahakariBank("Sanmathi Sahakari Bank","Seva Vikas Co Op Bank","","Sanmathi_Sahakari_Bank","","-"),
    SanmatiSahakariBankLtd("Sanmati Sahakari Bank Ltd","SanmatiSahakariBankLtd","528","","","SANMATI"),
    SarangpurCoOpBankLtdIndia("Sarangpur CoOp.Bank Ltd India","SarangpurCoOp.BankLtdIndia","344","","","THSARCBL"),
    SaraspurNagarikCoOpBankLtdIndia ("Saraspur Nagarik CoOpBank Ltd.India","SaraspurNagarikCoOpBankLtd.India","185","SARASPUR_NAGARIK_CO_OP_BANK","","SARASCOOP"),
    SaraswatBankIndia("Saraswat Bank India","SaraswatBankIndia","72","SARASWAT_BANK","2","-"),
    SardarBhiladwalaPardiPeoplesCoOpBank ("Sardar Bhiladwala Pardi Peoples CoOpBank","","","SARDAR_BHILADWALA_PARDI_PEOPLES_CO _OP_BANK","","-"),
    SardarBhiladwalaPardiPeoplesCoOperativeBankLtd("Sardar Bhiladwala Pardi People's Co-Operative Bank Ltd","SardarBhiladwalaPardiPeople'sCo-OperativeBankLtd","591","","","-"),
    SarvaUPGraminBankLtd("Sarva UP Gramin Bank Ltd","SarvaUPGraminBankLtd","540","","","-"),
    SarvodayaCommercialCoOperativeBankLtd("Sarvodaya Commercial Co-Operative Bank Ltd","SarvodayaCommercialCo-OperativeBankLtd","580","","","SARVODAYA"),
    SarvodayaSahakariBank("Sarvodaya Sahakari Bank","Sarvodaya Sahakari Bank","393","SARVODAYA_SAHAKARI_BANK","","SARVMODASA"),
    SaurashtraGraminBank ("Saurashtra Gramin Bank","Saurashtra Gramin Bank","386","SAURASHTRA_GRAMIN_BANK","","SAURAUSTRAGRA"),
    SDC ("SDC","","","SDC","","-"),
    SevaVikasCoOpBank("Seva Vikas Co Op Bank","Seva Vikas Co Op Bank","","Seva_Vikas_Co_Op_Bank","","SEVAVIKAS"),
    ShaliniSahkariBankLtd("Shalini Sahkari Bank Ltd","ShaliniSahkariBankLtd","606","","","SHALINIBANK"),
    ShamraoVittalCoOpp("Shamrao Vittal Co-Operative Bank Ltd","Shamrao Vittal Co-Operative Bank Ltd","76","","","-"),
    SharadaSahkariBank("Sharada Sahkari Bank","Sharada Sahkari Bank","532","","","SHARDA PUNE"),
    ShinhanBank("Shinhan Bank","ShinhanBank","711","","","SHINHAN"),
    ShirpurPeopleCoOp("Shirpur People Co-Op","Shirpur People Co-Op","506","","","SHIRPEO"),
    ShivajiraoBhosaleSahakariBankLtdIndia("Shivajirao Bhosale Sahakari Bank Ltd India","ShivajiraoBhosaleSahakariBankLtdIndia","258","","","SHIVAJIRAOPUNE"),
    ShivalikMercantileBank("Shivalik Mercantile Bank","ShivalikMercantileBank","","SHIVALIK_MERCANTILE_BANK","","SHIVALIK"),
    ShivalikMercantileCoOp("Shivalik Mercantile Co-Op. Bank Ltd","Shivalik Mercantile Co-Op. Bank Ltd","389","","","SHIVALIK"),
    ShreeCoOpBankLtd(" Shree Co Op Bank LTD","ShreeCoOpBankLtd","","SHREE_CO_OP_BANK_LTD","","-"),
    ShreeCoOpBankLtdIndia("ShreeCoOp.Bank Ltd India","ShreeCoOp.BankLtdIndia","375","","","-"),
    ShreeDharatiCoOpBankLtd("Shree Dharati Co-Op Bank Ltd","ShreeDharatiCoOpBankLtd","660","","","-"),
    ShreeKadiNagarikSahakariBankLtdIndia ("Shree Kadi Nagarik Sahakari Bank Ltd India","ShreeKadiNagarikSahakariBankLtdIndia","349","SHREE_KADI_NAGARIK_SAHAKARI_BANK","","SKADINSBL"),
    ShreeMaheshCoOpBankLtd("Shree Mahesh Co-Op. Bank Ltd","Shree Mahesh Co-Op. Bank Ltd","524","","","MAHESHNASHIK"),
    ShreeMaheshCoOpBankNashik("Shree Mahesh Co Op Bank Nashik","Shree Mahesh Co Op Bank Nashik","","Shree_Mahesh_Co_op_Bank_Nashik","","MAHESHNASHIK"),
    ShriAnandCoOpBank("Shri Anand Co-Op. Bank","Shri Anand Co-Op. Bank","522","","","SHRI ANANDCOOP"),
    ShriArihantCooperativeBank("Shri Arihant Cooperative Bank","ShriArihantCooperativeBank","","SHRI_ARIHANT_COOP_BANK","","ARIHANTCOOP"),
    ShriChhatrapatiRajarshiShahuUrbanCoOpBankLtdIndia("Shri Chhatrapati Rajarshi Shahu Urban CoOpBank Ltd India","ShriChhatrapatiRajarshiShahuUrbanCoOpBankLtdIndia","259","","","RAJA SHAHU"),
    ShriMahalaxmiCoOpBank  ("Shri Mahalaxmi Co-OpBank","ShriMahalaxmiCoOpBank","632","","","SHRIMAHALAXMI"),
    ShriPanchgangaNagariSahakariBankLtd("Shri Panchganga Nagari Sahakari BankLtd","ShriPanchgangaNagariSahakariBankLtd","726","","","-"),
    ShriRajkotDistrictCoOpBank("Shri Rajkot District Co Op Bank","ShriRajkotDistrictCoOpBank","","SHRI_RAJKOT_DISTRICT_CO_OP_BANK","","RAJKOTDCCB "),
    ShriShiveshwarNagariSahakariBankLtd("Shri Shiveshwar Nagari Sahakari Bank Ltd","ShriShiveshwarNagariSahakariBankLtd","611","","","SHIVESHNAGAR"),
    ShriVeershaivCoOpBank("Shri Veershaiv Co-Op. Bank","Shri Veershaiv Co-Op. Bank","518","","","VEERSHAIV"),
    Sidbi("Sidbi","Sidbi","","","10","SIDBI"),
    SmritiNagrikSahakariBank("Smriti Nagrik Sahakari Bank","Smriti Nagrik Sahakari Bank","478","Smriti Nagrik Sahakari Bank","","SMRITI NAGRIK"),
    SolapurJanataSahakariBank("Solapur Janata Sahakari Bank","","391","SOLAPUR_JANATA_SAHAKARI_BANK","","SOLAPUR JANATA"),
    SouthIndianBankIndia ("South Indian Bank India","SouthIndianBankIndia","52","SOUTH_INDIAN","","SOUTH INDIAN BK"),
    SreeMahayogiLakshmammaCoOp("Sree Mahayogi Lakshmamma Co-Op. Bank","Sree Mahayogi Lakshmamma Co-Op. Bank","397","","","-"),
    SreeMahayogiLakshmammaCoOpBank("Sree Mahayogi Lakshmamma Co op bank","ShriArihantCooperativeBank","","SREE_MAHAYOGI_LAKSHMAMMA_CO_OP_BANK_LTD","","SREEMAHAYOGI"),
    SreenidhiSouhardaSahakariBank("Sreenidhi Souharda Sahakari Bank","","","SREENIDHI_SOUHARDA_SAHAKARI_BANK","","SREENIDHISA"),
    SreenidhiSouhardaSahakariBankNiyamitha("Sreenidhi Souharda Sahakari Bank Niyamitha","SreenidhiSouhardaSahakariBankNiyamitha","604","","","SREENIDHISA"),
    SriBasaveshwarSahakariBank("Sri Basaveshwar Sahakari Bank","SriBasaveshwarSahakariBank","653","","","SBPSBANK"),
    StandardCharteredBankIndia  ("Standard Chartered Bank India","StandardCharteredBankIndia","32","STANDARD_CHARTERED","","SCB"),
    StateBankBikanerJaipur  ("State Bank Bikaner Jaipur","","","STATE_BANK_BIKANER_JAIPUR","","STATE BANK OF BIKANER AND JAIPUR"),
    StateBankHyderabad  ("State Bank Hyderabad","","","STATE_BANK_HYDERABAD","","SBH"),
    StateBankMysore ("State Bank Mysore","","","STATE_BANK_MYSORE","","SBM"),
    StateBankofIndiaIndia("State Bank of India","StateBankofIndiaIndia","35","SBI","16","SBI"),
    StateBankPatiala ("State Bank Patiala","","","STATE_BANK_PATIALA","","SBP"),
    StateBankTravancore ("State Bank Travancore","","","STATE_BANK_TRAVANCORE","","SBT"),
    SterlingUrbanCoOpBank("Sterling Urban Co-Op Bank","Sterling Urban Co-Op Bank","481","Sterling_Urban_Co_Op_Bank","","STERLING"),
    SUCOBank("SUCO Bank","SUCO Bank","467","","","SUCOSAHA"),
    SundarlalSawjiUrbanCoOpBankLtd("Sundarlal Sawji Urban Co-Op. Bank Ltd","Sundarlal Sawji Urban Co-Op. Bank Ltd","461","","","SUNDARLAL"),
    SuratDistrictCoOpBank("Surat District Co-Op. Bank","Surat District Co-Op. Bank","473","","","SURATDCCB"),
    SuratNationalCoOpBankLtd("Surat National Co-Op. Bank Ltd","Surat National Co-Op. Bank Ltd","464","","","SURATNAT"),
    SuratPeoplesCoopBankLtdIndia ("Surat Peoples CoopBank Ltd India","SuratPeoplesCoopBankLtdIndia","244","","","SURATPEO"),
    SuryodaySmallFinanceBank("Suryoday Small Finance Bank","Suryoday Small Finance Bank","507","","","SURYOFIN"),
    SuryodaySmallFinanceBankLtd("Suryoday Small Finance Bank Ltd.","SuryodaySmallFinanceBankLtd","","SURYODAY_SMALL_FINANCE_BANK_LTD","","SURYOFIN"),
    SutexCoopBankLtd("Sutex Co-op Bank Ltd","Sutex Co-op Bank Ltd","92","","","SUTEXCBL"),
    SuvarnayugSahakariBank("Suvarnayug Sahakari Bank","SuvarnayugSahakariBank","574","","","SUVARNAYUG"),
    SVCBank ("SVC Bank","","","SVC_BANK","","-"),
    SyndicateBankIndia  ("Syndicate Bank India","SyndicateBankIndia","41","SYNDICATE","22","SYNDICATE BANK"),
    TamilnadMercantileBankLtdIndia  ("Tamilnad Mercantile Bank Ltd.India","TamilnadMercantileBankLtd.India","75","TAMILNAD_MERCANTILE","","TN MERCANTILE"),
    TelanganaGrameenaBank("Telangana Grameena Bank","Telangana Grameena Bank","500","","","DECCAN"),
    TexcoCoOpBankLtd("Texco Co-Op. Bank Ltd","Texco Co-Op. Bank Ltd","415","","","-"),
    TextileCoOperativeBank  ("Textile CoOperative Bank","","","TEXTILE_CO_OPERATIVE_BANK","","TEXTCO"),
    TextileTradersCoOpBankLtd("Textile Traders Co-Op. Bank Ltd","Textile Traders Co-Op. Bank Ltd","401","","","TEXTILE TRADERS"),
    TgmcBankLtd("TGMC Bank Ltd","TgmcBankLtd","","TGMC_BANK ","","-"),
    ThaneBharatSahakariBank("Thane Bharat Sahakari Bank","ThaneBharatSahakariBank","","THANE_BHARAT_SAHAKARI_BANK_LTD","","THANEBSBL"),
    ThaneBharatSahakariBankLtdIndia ("Thane Bharat Sahakari Bank Ltd India","ThaneBharatSahakariBankLtdIndia","226","","","-"),
    TheAbhinavSahakariBankLtd("The Abhinav Sahakari Bank Ltd","TheAbhinavSahakariBankLtd","658","","","ABHINAV"),
    TheAceCooperativeBankLtd("The Ace Co-operative Bank Ltd","TheAceCo-operativeBankLtd","569","","","-"),
    TheAdinathCoOperativeBankLtdIndia("The Adinath CoOperative Bank Ltd.India","TheAdinathCoOperativeBankLtd.India","180","","","ADINATHSURAT"),
    TheAhmedabadMercantileCoOpBank("The Ahmedabad Mercantile Co Op Bank","TheAhmedabadMercantileCoOpBank","","The_Ahmedabad_Mercantile_Co_Op_Bank","","AMCOBANKLIMITED"),
    TheAhmednagarMerchantCoOpBankLtd("The Ahmednagar Merchant Co Op Bank Ltd","TheAhmednagarMerchantCoOpBankLtd","395","The_Ahmednagar_Merchant_Co_Op_Bank_Ltd","","-"),
    TheAkolaDistrictCentralCoOpBank("The Akola District Central Co Op Bank","TheAkolaDistrictCentralCoOpBank","187","The_Akola_District_Central_Co_Op_Bank","","AKOLADCCB"),
    TheBagatUrbanCoOperativeBankLtd("The Bagat Urban Co-Operative Bank Ltd","TheBagatUrbanCoOperativeBankLtd","691","","","BAGHATUCB"),
    TheBanaskanthaMercantileCoOperativeBankLtdIndia ("The Banaskantha MercantileCo.Operative Bank Ltd India","TheBanaskanthaMercantileCo.OperativeBankLtdIndia","167","","","TBMCBL"),
    TheBardoliNagarikSahakariBank("The Bardoli Nagarik Sahakari Bank","TheBardoliNagarikSahakariBank","649","","","BARDOLINAG"),
    TheBhagyalashmiMahilaSahakariBankLtd("The Bhagyalashmi Mahila Sahakari Bank Ltd","TheBhagyalashmiMahilaSahakariBankLtd","595","","","TBHAGYAMSBL"),
    TheBharatCoOperativeBank("The Bharat Co-Operative Bank","The Bharat Co-Operative Bank","122","","","BHARAT CO"),
    TheBhujMercantileCoopBankLtdIndia("The Bhuj Mercantile Coop.BankLtd.India","TheBhujMercantileCoop.BankLtd.India","168","","","BHUJ"),
    TheBurdwanCentralCoOpBank("The Burdwan Central Co-Op Bank","TheBurdwanCentralCoOpBank","633","","","BURDWANCCB"),
    TheChanasmaNagrikSahakari("The Chanasma Nagrik Sahakari Bank","TheChanasmaNagrikSahakari","609","","","CHANASMA"),
    TheCoOperativeBankofRajkotIndia ("The CoOperative Bankof Rajkot India","TheCoOperativeBankofRajkotIndia","162","","","COOP RAJKOT"),
    TheDahodUrbanCoOpBankLtd("The Dahod Urban-Co-Op.Bank Ltd","TheDahodUrban-Co-Op.BankLtd","558","","","DAHODCOOP"),
    TheEenaduCoOpUrbanBank("The Eenadu Co Op Urban Bank","TheEenaduCoOpUrbanBank","","The_Eenadu_Co_Op_Urban_Bank","","EENADUBANK"),
    TheFinancialCoOpBankLtdIndia ("The Financial CoOpBank Ltd.India","TheFinancialCoOpBankLtd.India","188","","","TFCBL"),
    TheGandeviPeoplesCoOpBank("The Gandevi People's Co-Op Bank","TheGandeviPeoplesCoOpBank","627","","","GANDEVI PEO"),
    TheGandhidhamCooperativeBankLtd("The Gandhidham Cooperative Bank Ltd","TheGandhidhamCooperativeBankLtd","","The_Gandhidham_CoOperative_Bank_Ltd","","TGCBLA"),
    TheGandhidhamMercantileCooperativeBankLtdIndia  ("The Gandhidham Mercantile Cooperative BankLtd.India","TheGandhidhamMercantileCooperativeBankLtd.India","169","TGMC_BANK","","GANDHIDHAM MER"),
    TheGayatriCoOperativeUrbanBankLtdIndia  ("The Gayatri CoOperative Urban Bank Ltd.India","TheGayatriCoOperativeUrbanBankLtd.India","170","","","GAYATRICUBL"),
    TheHindustanCoOpBankLtd("The Hindusthan Co Op Bank Ltd","TheHindustanCoOpBankLtd","","The_Hindusthan_Co_Op_Bank_Ltd","","HINDUCB"),
    TheIncomeTaxDepartmentCoOpBank("The Income-Tax Department Co-Op Bank","TheIncomeTaxDepartmentCoOpBank","654","","","INCOMETAX"),
    TheJainSahakariBank("The Jain Sahakari Bank","TheJainSahakariBank","624","","","JAINSAH"),
    TheJalgaonPeoplesCoOpBank("The Jalgaon Peoples Co Op Bank","TheJalgaonPeoplesCoOpBank","","The_Jalgaon_Peoples_CoOp_Bank","","JALGAON PCBL"),
    TheKairaDistrictCentralCoOpBank("The Kaira District Central Co-Op Bank","TheKairaDistrictCentralCoOpBank","621","","","KAIRACENTRAL"),
    TheKalupurCommercialCoopBankLtdIndia ("The Kalupur Commercial Co.op. Bank Ltd.India","TheKalupurCommercialCo.op.BankLtd.India","154","KALUPUR_COMMERCIAL_CO_OP_BANK","","KALUPUR"),
    TheKanakamahalakshmiCoOpBankLtd("The Kanakamahalakshmi Co Op Bank Ltd","TheKanakamahalakshmiCoOpBankLtd","","THE_KANAKAMAHALAKSHMI_CO_OP_BANK_LTD","","KANAKAMAHA"),
    TheKanakamahalakshmiCoOperativeBankLtd("The Kanakamahalakshmi Co-Operative Bank Ltd","TheKanakamahalakshmiCo-OperativeBankLtd","586","","","KANAKAMAHA"),
    TheKaradUrbanCoopBankIndia  ("The Karad Urban CoopBank India","TheKaradUrbanCoopBankIndia","176","","","KARAD"),
    TheKaradUrbanCoOpBankLtd("The Karad Urban Co Op Bank LTD","TheKaradUrbanCoOpBankLtd","","THE_KARAD_URBAN_CO_OP_BANK_LTD","","KARAD"),
    TheKarnatakaStateCoOperativeApexBankLtd("The Karnataka State Co-Operative Apex Bank Ltd","TheKarnatakaStateCo-OperativeApexBankLtd","568","","","KARSCAB"),
    TheKarnavatiCoOpBankLtd("The Karnavati Co-Op Bank Ltd","TheKarnavatiCoOpBankLtd","724","","","KARNAVATI"),
    TheKhattriCoOpUrbanBankLtd("The Khattri Co-Op Urban Bank Ltd","TheKhattriCoOpUrbanBankLtd","622","","","KHATTRI"),
    TheKunbiSahakariBankLtd("The Kunbi Sahakari Bank Ltd","TheKunbiSahakariBankLtd","725","","","KUNBI"),
    TheKurlaNagrikSahakariBankLtd("The Kurla Nagrik Sahakari Bank Ltd","TheKurlaNagrikSahakariBankLtd","703","","","TKNSBL"),
    TheMogaveeraCoOpBankLtd("The Mogaveera Co Op Bank LTD","TheMogaveeraCoOpBankLtd","755","MOGAVEERA_CO_OP_BANK_LTD","","MOGAVEERAOP"),
    TheMunicipalCoOpBankLtd("The Municipal Co-Op Bank Ltd","TheMunicipalCo-OpBankLtd","575","","","MUNIC COOP"),
    TheNarodaNagrikCoOpBank ("The Naroda Nagrik CoOp Bank","","","THE_NARODA_NAGRIK_CO_OP_BANK","","NARODANAG"),
    TheNashikRoadDeolaliVyapariSahakariBank("The Nashik Road Deolali Vyapari Sahakari Bank","TheNashikRoadDeolaliVyapariSahakariBank","650","","","NASIKVYAPAR"),
    TheNasikMerchantsCoOperativeBankLtd("The Nasik Merchants Co-Operative Bank Ltd","TheNasikMerchantsCo-OperativeBankLtd","581","","","NASHIKMCOOP"),
    ThePanchsheelMercantileCoOpBank("The Panchsheel Mercantile Co-Op Bank","ThePanchsheelMercantileCoOpBank","610","","","PANCHMER"),
    ThePanchsheelMercantileCoOpBankLtd("The Panchsheel Mercantile Co Op Bank LTD","ThePanchsheelMercantileCoOpBankLtd","","THE_PANCHSHEEL_MERCANTILE_CO_OP_BANK_LTD","","PANCHMER"),
    ThePanipatUrbanCoOpBank("The Panipat Urban Co Op Bank","ThePanipatUrbanCoOpBank","","The_Panipat_Urban_Co_Op_Bank","","PANIPATURBAN"),
    TheRajkotCommercialCoOpBank("The Rajkot Commercial Co Op Bank","TheRajkotCommercialCoOpBank","","THE RAJKOT COMMERCIAL COOP BANK","","RAJCOOP"),
    TheSabarkanthaDistrictCentralCoOpBankLtdIndia("The Sabarkantha District Central CoOp Bank Ltd.India","TheSabarkanthaDistrictCentralCoOpBankLtd.India","190","","","SABARKANTHA"),
    TheSataraSahakariBankLtdIndia("The Satara Sahakari Bank Ltd.India","TheSataraSahakariBankLtd.India","181","","","SATARA SAHAKARI"),
    TheSevaVikasCoOperativeBankLtdIndia ("The Seva Vikas CoOperative Bank Ltd.India","TheSevaVikasCoOperativeBankLtd.India","179","","","SEVAVIKAS"),
    TheSuratMercantileCoOpBankLtd("The Surat Mercantile Co-Op. Bank Ltd","TheSuratMercantileCo-Op.BankLtd","565","","","SURATMERC"),
    TheSuratPeopleCoOpBankLtd("The Surat People CO OP Bank LTD","TheSuratPeopleCoOpBankLtd","","THE_SURAT_PEOPLE_CO_OP_BANK_LTD","","SURATPEO"),
    TheSutexCoOpBankLtd("The Sutex Co Op Bank LTD","TheSutexCoOpBankLtd","","THE_SUTEX_CO_OP_BANK","","SUTEXCBL"),
    TheTamilnaduStateApexCoOperativeBank("The Tamilnadu State Apex Co-Operative Bank","TheTamilnaduStateApexCo-OperativeBank","594","","","TSACBL"),
    TheUdaipurMahilaSamridhiUrbanCoOperativeBankLtd("The Udaipur Mahila Samridhi Urban Co-Operative Bank Ltd","TheUdaipurMahilaSamridhiUrbanCo-OperativeBankLtd","582","","","UDAIPUR MAHILA"),
    TheUdaipurUrbanCoOpBankLtd("The Udaipur Urban Co-Op Bank Ltd","TheUdaipurUrbanCoOpBankLtd","758","","","UDAIPUR"),
    TheUnionCoOpBankLtd("The Union Co Op Bank Ltd","TheUnionCoOpBankLtd","643","UNION_CO_OP_BANK_LTD","","UNIONCOP"),
    TheUrbanCoOperativeBankLtd("The Urban Co-Operative Bank Ltd","TheUrbanCo-OperativeBankLtd","584","","","URBAN CO"),
    TheVallabhVidyanagarCommercialCoOperativeBankLtd("The Vallabh VidyaNagar Commercial Co-Operative Bank Ltd","TheVallabhVidyanagarCommercialCo-OperativeBankLtd","","The_Vallabh_VidyaNagar_Commercial_Co_Operative_Bank_Ltd","","VALLABH"),
    TheVarachhaCoOpBankLtd("The Varachha Co Op Bank LTD","TheVarachhaCoOpBankLtd","","THE_VARACHHA_CO_OP_BANK_LTD","","VARACHHACOOP"),
    TheVijayCoOpBankLimited("The Vijay Co Op Bank Limited","TheVijayCoOpBankLimited","","THE_VIJAY_CO_OP_BANK","","VIJAY COOP"),
    TheVishweshwarSahakariBankLtd("The Vishweshwar Sahakari Bank Ltd","TheVishweshwarSahakariBankLtd","","The_Vishweshwar_Sahakari_Bank_Ltd","","VISHWESH SAH"),
    TheVyankateshwaraSahakariBankLtd("The Vyankateshwara Sahakari Bank Ltd","TheVyankateshwaraSahakariBankLtd","588","","","VYANKATESHWARA"),
    TheWaiUrbanCoOperativeBankLimited("The Wai Urban Co-Operative Bank Limited","TheWaiUrbanCoOperativeBankLimited","","The_Wai_Urban_Co_Operative_Bank_Limited","","WAI URBAN"),
    TJSB ("TJSB","TJSB","90","TJSB","","-"),
    TumkurGrainMerchantsCreditCoOpBank("Tumkur Grain Merchants Credit Co-Op. Bank","Tumkur Grain Merchants Credit Co-Op. Bank","512","","","TUMKURGRAIN"),
    TumkurMerchantsCreditCoOp("Tumkur Merchants Credit Co-Op","Tumkur Merchants Credit Co-Op","416","","","-"),
    UCOBankIndia ("UCO Bank India","UCOBankIndia","42","UCO","19","UCO BANK"),
    UjjivanBankIndia ("Ujjivan Bank India","UjjivanBankIndia","191","","","-"),
    UjjivanSmallFinanceBank("Ujjivan Small Finance Bank","UjjivanSmallFinanceBank","","UJJIVAN_SMALL_FINANCE_BANK","","UJJIVANSFB"),
    UmaCoOpBank("Uma Co-Op. Bank","Uma Co-Op. Bank","514","","","UMACOOP"),
    UmiyaUrbanCoOpBank("Umiya Urban Co-Op Bank","UmiyaUrbanCoOpBank","766","","","UMIYABAN"),
    UnionBankofIndiaIndia("Union Bankof India India","UnionBankofIndiaIndia","43","UNION_BANK","1","UNION BANK"),
    UnitedBankofIndiaIndia  ("United Bankof India India","UnitedBankofIndiaIndia","44","UNITED_BANK","29","UNITED BANK"),
    UnitedCoOpBank("United Co-Op. Bank","United Co-Op. Bank","470","","","THEUCBLA"),
    UtkarshSmallFinanceBank("Utkarsh Small Finance Bank","Utkarsh Small Finance Bank","465","","","UTKARFIN"),
    UttarakhandGraminBank("Uttarakhand Gramin Bank","Uttarakhand Gramin Bank","341","","","UTTAR GRAMIN"),
    VaidyanathUrbanCoopBankLtdIndia ("Vaidyanath Urban CoopBank Ltd India","VaidyanathUrbanCoopBankLtdIndia","262","","","VAIDYACO"),
    VaijapurMarchantsCoOpBank("Vaijapur Marchants Co Op Bank","VaijapurMarchantsCoOpBank","","VAIJAPUR_MARCHANTS_CO_OP_BANK","","TVAIMCBL"),
    VaijapurMerchantsCoOp("Vaijapur Merchants Co-Op","Vaijapur Merchants Co-Op","454","","","-"),
    VaishyaNagariSahakariBank("Vaishya Nagari Sahakari Bank","VaishyaNagariSahakariBank","","Vaishya_Nagari_Sahakari_Bank","","VAISHYANAGARI"),
    VaishyaNagariSahakariBankIndia  ("Vaishya Nagari Sahakari Bank India","VaishyaNagariSahakariBankIndia","163","","","VAISHYANAGARI"),
    VananchalGraminBank("Vananchal Gramin Bank","VananchalGraminBank","","Vananchal_Gramin_Bank","","VANACHALBR"),
    VarachhaCoopBankLtdIndia ("Varachha Coop Bank Ltd.India","VarachhaCoopBankLtd.India","157","","","VARACHHACOOP"),
    VasaiJanataSahakariBankLtd("Vasai Janata Sahakari Bank Ltd","VasaiJanataSahakariBankLtd","590","","","VASAIJSBL"),
    VasaiVikasSahakariBankLtdIndia  ("Vasai Vikas Sahakari Bank Ltd India","VasaiVikasSahakariBankLtdIndia","302","VASAI_VIKAS_SAH_BANK_LTD","","VASAI"),
    VeerashaivaSahakariBankLtd("Veerashaiva Sahakari Bank Ltd","Veerashaiva Sahakari Bank Ltd","418","","","VEERASHAIV"),
    VidarbhaMerchantsUrbanCoOp("Vidarbha Merchants Urban Co-Op Bank","Vidarbha Merchants Urban Co-Op Bank","398","","","-"),
    VidarbhaMerchantsUrbanCoOpBankLtd("Vidarbha Merchants Urban Co Op Bank Ltd","VidarbhaMerchantsUrbanCoOpBankLtd","","VIDARBHA_MERCHANTS_URBAN_CO_OP_BANK_LTD","","VIDARBHAURB"),
    VidyaSahkariBank("Vidya Sahkari Bank","Vidya Sahkari Bank","534","","","VIDYA PUNE"),
    VijayaBankIndia ("Vijaya Bank India","VijayaBankIndia","45","VIJAYA","15","VijayCopBank"),
    VijayCopBank("VijayCopBank","Vijay Co-Op. Bank","519","","","VIJAY COOP"),
    VikasSahakariBankLtd("Vikas Sahakari Bank Ltd","VikasSahakariBankLtd","566","","","VIKASAHA"),
    VikasSouhardaCoOpBank("Vikas Souharda Co-Op Bank","VikasSouhardaCoOpBank","648","","","VIKASSCBL"),
    VikramadityaNagrikSahakariBankIndia ("Vikramaditya Nagrik Sahakari Bank India","VikramadityaNagrikSahakariBankIndia","171","","","VIKRAMNAGARIK"),
    VinayakSahakariBank("Shri Vinayak Sahakari Bank Ltd","Shri Vinayak Sahakari Bank Ltd","579","","","VINAYAK"),
    VishweshwarSahakariBankLtd("Vishweshwar Sahakari Bank Ltd","Vishweshwar Sahakari Bank Ltd","457","","","VISHWESH SAH"),
    VitaMerchantsCoOpBankLtdIndia("Vita Merchants CoOp Bank Ltd India","VitaMerchantsCoOpBankLtdIndia","263","","","TVMCBL"),
    VyaparikAudyogikSahkariBank("Vyaparik Audyogik Sahkari Bank","VyaparikAudyogikSahkariBank","636","","","VYAPAAUD"),
    VyapariSahakariBankMaryadit("Vyapari Sahakari Bank Maryadit","VyapariSahakariBankMaryadit","564","","","VYAPARIBANK"),
    VysyaCoopBankLtdIndia("VysyaCoopBankLtdIndia","VysyaCoopBankLtdIndia","198","","","VYCBLT"),
    WaiUrbanCoOperativeBankIndia ("Wai Urban CoOperative Bank India","WaiUrbanCoOperativeBankIndia","160","","","WAI URBAN"),
    WardhaNagariSahakariAdhikoshBankLtd("Wardha Nagari Sahakari Adhikosh Bank Ltd","WardhaNagariSahakariAdhikoshBankLtd","544","","","WARDHANAG"),
    YesBankIndia ("Yes Bank India","YesBankIndia","46","YES","","YES BANK"),
    YeshwantUrbanCoOpBankLtdIndia("Yeshwant Urban CoOpBank Ltd.India","YeshwantUrbanCoOpBankLtd.India","184","","","YESHCOOP"),
    ZoroastrianBankIndia ("Zoroastrian Bank India","ZoroastrianBankIndia","172","","","-"),
    ZoroastrianCoOpBankLimited("Zoroastrian Co Op Bank Limited","ZoroastrianCoOpBankLimited","","ZOROASTRIAN_CO_OP_BANK","","ZOROASTRIAN"),

    //--> add on 15/11/2019
	BelagaviShreeBasaveshwarCoOpBankLtd("Belagavi Shree Basaveshwar Co-Op Bank Ltd","BelagaviShreeBasaveshwarCoOpBankLtd","774","","","-"),
	CalicutCityServiceCoOpBank("Calicut City Service Co-Op Bank","CalicutCityServiceCoOpBank","777","","","-"),
	CoastalBank("Coastal Bank","CoastalBank","782","","","-"),
	JaiBhavaniSahakariBank("Jai Bhavani Sahakari Bank","JaiBhavaniSahakariBank","781","","","-"),
	MadheshwariUrbanDevelopmentCo("Madheshwari Urban Development Co-Op Bank","MadheshwariUrbanDevelopmentCoOpBank","771","","","-"),
	NorthEastSmallFinanceBankLtd("North East Small Finance Bank Ltd","NorthEastSmallFinanceBankLtd","775","","","-"),
	SBTABankLtd("SBTA Bank Ltd","SBTABankLtd","727","","","-"),
	SarvodayaCoOpBank("Sarvodaya Co-Op Bank","SarvodayaCoOpBank","778","","","-"),
	TheMalkapurUrbanCoOpBankLtd("The Malkapur Urban Co-Op Bank Ltd","TheMalkapurUrbanCoOpBankLtd","783","","","-"),
	UtkalGrameenBank("Utkal Grameen Bank","UtkalGrameenBank","763","","","-"),
	WardhamanUrbanCoOpbankLtd("Wardhaman Urban Co-Op bank Ltd","WardhamanUrbanCoOpbankLtd","770","","","-"),
	BhadradriCoOpUrbanBank("Bhadradri Co-Op Urban Bank","BhadradriCoOpUrbanBank","789","","","-"),
	GulshanMercantileUrbanCoOpBankIndia("Gulshan Mercantile Urban Co-Op Bank, India","GulshanMercantileUrbanCoOpBankIndia","788","","","-"),
	JainCoOpBankLtdIndia("Jain Co-Op Bank Ltd, India","JainCoOpBankLtdIndia","793","","","-"),
	MangalCoOpBankLtdIndia("Mangal Co-Op Bank Ltd, India","MangalCoOpBankLtdIndia","792","","","-"),
	ShreeWaranaSahakariBankLtdIndia("Shree Warana Sahakari Bank Ltd, India","ShreeWaranaSahakariBankLtdIndia","791","","","-"),
	TheChemburNagrikSahkariBankIndia("The Chembur Nagrik Sahkari Bank, India","TheChemburNagrikSahkariBankIndia","794","","","-"),
	TheGoaUrbanCoOpBankLtdIndia("The Goa Urban Co-Op Bank Ltd, India","TheGoaUrbanCoOpBankLtdIndia","790","","","-"),
	
	
	//add 29-11-2019::
	TheDelhiStateCoOpBankLtdIndia("The Delhi State Co-Op Bank Ltd, India","TheDelhiStateCoOpBankLtdIndia","805","","","-"),
    MumbaiDistrictCentralCoOpBankLtdIndia("Mumbai District Central Co-Op Bank Ltd, India","MumbaiDistrictCentralCoOpBankLtdIndia","801","","","-"),
    ShreeGaneshSahakariBankLtdIndia("Shree Ganesh Sahakari Bank Ltd, India","ShreeGaneshSahakariBankLtdIndia"," 795","","","-"),
    MahanagarNagrikSahakariBankIndia("Mahanagar Nagrik Sahakari Bank, India","MahanagarNagrikSahakariBankIndia","797","","","-"),
    KrishnaGrameenaBankIndia("Krishna Grameena Bank, India","KrishnaGrameenaBankIndia","800","","","-"),
    KamalaCoOpBankLtdIndia("Kamala Co-Op Bank Ltd, India","KamalaCoOpBankLtdIndia","803","","","-"),
    TamilNaduGramaBankIndia("Tamil Nadu Grama Bank, India","TamilNaduGramaBankIndia","804","","","-"),
    TheBangaloreCityCoOpBankLtdIndia("The Bangalore City Co-Op Bank Ltd, India","TheBangaloreCityCoOpBankLtdIndia","796","","","-"),
    TheBavlaNagrikSahkariBankLtdIndia("The Bavla Nagrik Sahkari Bank Ltd, India","TheBavlaNagrikSahkariBankLtdIndia","806","","","-"),
    HutatmaSahakariBankLtdIndia("Hutatma Sahakari Bank Ltd, India","HutatmaSahakariBankLtdIndia","798","","","-"),
    IndiaPostPaymentsBankIndia("India Post Payments Bank, India","IndiaPostPaymentsBankIndia","807","","","-"),
    TheThaneDistrictCentralCoOpBankIndia("The Thane District Central Co-Op Bank, India","TheThaneDistrictCentralCoOpBankIndia","752","","","-"),
    VardhamanMahilaCoOpUrbanBankLtdIndia("Vardhaman Mahila Co-Op Urban Bank Ltd, India","VardhamanMahilaCoOpUrbanBankLtdIndia","802","","","-"),
    
    //add on 16/12/2019
    DrJaiprakashMundadaUrbanCoOpBankLtdIndia("Dr Jaiprakash Mundada Urban Co Op Bank Ltd, India","DrJaiprakashMundadaUrbanCoOpBankLtdIndia","816","","","-"),
    GoaStateCoOpBankLtdIndia("Goa State Co-Op Bank Ltd, India","GoaStateCoOpBankLtdIndia","823","","","-"),
    JalnaMerchantsCoOpBankLtdIndia("Jalna Merchants Co-Op Bank Ltd, India","JalnaMerchantsCoOpBankLtdIndia","812","","","-"),
    ManipalCoOpBankIndia("Manipal Co Op Bank, India","ManipalCoOpBankIndia","819","","","-"),
    MerchantsLiberalCoOpBankLtdIndia("Merchants Liberal Co-Op Bank Ltd, India","MerchantsLiberalCoOpBankLtdIndia","818","","","-"),
    OttapalamCoOpUrbanBankLtdIndia("Ottapalam Co-Op Urban Bank Ltd, India","OttapalamCoOpUrbanBankLtdIndia","811","","","-"),
    SarvaHaryanaGraminBankIndia("Sarva Haryana Gramin Bank, India","SarvaHaryanaGraminBankIndia","810","","","-"),
    TheBhavanaRishiCoOpUrbanBankLtdIndia("The Bhavana Rishi Co-Op Urban Bank Ltd, India","TheBhavanaRishiCoOpUrbanBankLtdIndia","809","","","-"),
    TheMaladSahakariBankLtdIndia("The Malad Sahakari Bank Ltd, India","TheMaladSahakariBankLtdIndia","814","","","-"),
    TheYashwantCoOpLtdIndia("The Yashwant Co-Op Ltd, India","TheYashwantCoOpLtdIndia","808","","","-"),
    ThrissurDistrictCitizensCoOpSocietyLtdIndia("Thrissur District Citizens Co-Op Society Ltd, India","ThrissurDistrictCitizensCoOpSocietyLtdIndia","821","","","-"),
    TumkurVeerashaivaCoOpBankLtdIndia("Tumkur Veerashaiva Co-Op Bank Ltd, India","TumkurVeerashaivaCoOpBankLtdIndia","820","","","-"),
    ZilaSahkariBankLtdIndia("Zila Sahkari Bank Ltd, India","ZilaSahkariBankLtdIndia","822","","","-"),
    MysoreMerchantsCoOpBankLtdIndia("Mysore Merchants Co-Op Bank Ltd, India","MysoreMerchantsCoOpBankLtdIndia","813","","","-"),
	
	
	//add on 21/12/2019
    KalolNagarikSahakariBankLtdIndia("Kalol Nagarik Sahakari Bank Ltd, India","KalolNagarikSahakariBankLtdIndia","827","","","-"),
    KeshavSehkariBankLtdIndia("Keshav Sehkari Bank Ltd, India","KeshavSehkariBankLtdIndia","825","","","-"),
    ShikshakSahakariBankLtdIndia("Shikshak Sahakari Bank Ltd, India","ShikshakSahakariBankLtdIndia","828","","","-"),
    TheMuslimCoOpBankLtdIndia("The Muslim Co-Op Bank Ltd, India","TheMuslimCoOpBankLtdIndia","824","","","-"),
    
   //add on 26/12/2019
    BankofBahrainandKuwait("Bank of Bahrain and Kuwait","BankofBahrainandKuwait","840","","","-"),
    BhujCommercialCoOpBankLtdIndia("Bhuj Commercial Co-Op Bank Ltd, India","BhujCommercialCoOpBankLtdIndia","839","","","-"),
    ThePratapCoOpBankLtdIndia("The Pratap Co-Op Bank Ltd, India","ThePratapCoOpBankLtdIndia","838","","","-"),	
	
    //add on 31/12/2019
    DharmavirSambhajiUrbanCoOpBankLtdIndia("Dharmavir Sambhaji Urban Co-Op Bank Ltd, India","DharmavirSambhajiUrbanCoOpBankLtdIndia","837","","","-"),
    MadhyaPradeshGraminBankIndia("Madhya Pradesh Gramin Bank, India","MadhyaPradeshGraminBankIndia","847","","","-"),
    NagpurMahanagarPalikaKarmachariSahakariBankLtdIndia("Nagpur Mahanagar Palika Karmachari Sahakari Bank Ltd, India","NagpurMahanagarPalikaKarmachariSahakariBankLtdIndia","843","","","-"),	
    TheSangamnerMerchantsCooperativeBankLtdIndia("The Sangamner Merchants Co-operative Bank Ltd, India","TheSangamnerMerchantsCooperativeBankLtdIndia","845","","","-"),
    UnjhaNagarikSahakariBankLtdIndia("Unjha Nagarik Sahakari Bank Ltd, India","UnjhaNagarikSahakariBankLtdIndia","826","","","-"),
    
    
  //add on 05/02/2020
    AmbajogaiPeoplesCoOpBank("Ambajogai Peoples Co-Op. Bank","AmbajogaiPeoplesCoOpBank","850","","","-"),	
    GodavariUrbanCoOpBankIndia("Godavari Urban Co-Op Bank, India","GodavariUrbanCoOpBankIndia","865","","","-"),
    IndoreClothMarketCoOpBankLtdIndia("Indore Cloth Market Co-Op Bank Ltd, India","IndoreClothMarketCoOpBankLtdIndia","858","","","-"),
    NagarikSahakariBankLtdIndia("Nagarik Sahakari Bank Ltd, India","NagarikSahakariBankLtdIndia","868","","","-"),
    PadmavathiCoOpUrbanBankIndia("Padmavathi Co-Op Urban Bank, India","PadmavathiCoOpUrbanBankIndia","855","","","-"),
    ShankarNagariSahakariBankIndia("ShankarNagariSahakariBankIndia","ShankarNagariSahakariBankIndia","854","","","-"),
    ShreeLaxmiCoOpBankIndia("Shree Laxmi Co-Op Bank, India","ShreeLaxmiCoOpBankIndia","873","","","-"),
    ShriKanyakaNagariSahakariBankLtdIndia("Shri Kanyaka Nagari Sahakari Bank Ltd, India","ShriKanyakaNagariSahakariBankLtdIndia","866","","","-"),
    ShriLaxmikrupaUrbanCoOpBankLtdIndia("Shri Laxmikrupa Urban Co-Op Bank Ltd, India","ShriLaxmikrupaUrbanCoOpBankLtdIndia","817","","","-"),
    ShriRenukamataMultistateCoOpUrbanCreditSocietyIndia("Shri Renukamata Multistate Co-Op Urban Credit Society, India","ShriRenukamataMultistateCoOpUrbanCreditSocietyIndia","857","","","-"),
    SolapurSiddheshwarSahakariBankLtdIndia("Solapur Siddheshwar Sahakari Bank Ltd, India","SolapurSiddheshwarSahakariBankLtdIndia","861","","","-"),
    SreeSubramanyeswaraCoOpBankIndia("Sree Subramanyeswara Co-Op Bank, India","SreeSubramanyeswaraCoOpBankIndia","856","","","-"),
    TelanganaStateCoOpBankLtdIndia("Telangana State Co-Op Bank Ltd, India","TelanganaStateCoOpBankLtdIndia","853","","","-"),
    TheAndhraPradeshStateCoOpBankIndia("The Andhra Pradesh State Co-Op Bank, India","TheAndhraPradeshStateCoOpBankIndia","864","","","-"),
    TheBarodaCentralCoOpBankLtdIndia("The Baroda Central Co-Op Bank Ltd, India","TheBarodaCentralCoOpBankLtdIndia","851","","","-"),
    TheDeccanCoOpUrbanBankLtdIndia("The Deccan Co-Op Urban Bank Ltd, India","TheDeccanCoOpUrbanBankLtdIndia","863","","","-"),
    TheHyderabadDistrictCoOpCentralBankLtdIndia("The Hyderabad District Co-Op Central Bank Ltd, India","TheHyderabadDistrictCoOpCentralBankLtdIndia","869","","","-"),
    TheJanathaCoOpBankIndia("The Janatha Co-Op Bank, India","TheJanathaCoOpBankIndia","860","","","-"),
    TheNavalDockyardCoOpBankLtdIndia("The Naval Dockyard Co-Op Bank Ltd, India","TheNavalDockyardCoOpBankLtdIndia","867","","","-"),
    TheSSKCoOpBankLtdIndia("The SSK Co-Op Bank Ltd, India","TheSSKCoOpBankLtdIndia","849","","","-"),
    TheVaishCoOpNewBankLtdIndia("The Vaish Co-Op New Bank Ltd, India","TheVaishCoOpNewBankLtdIndia","852","","","-");
    
	
	
    
    private BankList(String name, String perfiosName, String perfiosId, String finbitName,String orgId,String bureauName) {
        this.name = name;
        this.perfiosName = perfiosName;
        this.perfiosId = perfiosId;
        this.finbitName = finbitName;
        this.orgId = orgId;
        this.bureauName = bureauName;
    }

    private String name;
    private String perfiosName;
    private String perfiosId;
    private String finbitName;
    private String orgId;
    private String bureauName;

    public static BankList[] getAll() {
        return BankList.values();

    }

    public static BankList fromName(String v) {
        for (BankList c : BankList.values()) {
            if (c.name.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
    public static BankList fromPerfiousId(String v) {
        for (BankList c : BankList.values()) {
            if (c.perfiosId.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
    
    public static BankList fromOrgId(String v) {
        for (BankList c : BankList.values()) {
            if (c.orgId.equalsIgnoreCase(v)) {
                return c;
            }
        }
        return null;
    }
    public static BankList fromBureauName(String v) {
        for (BankList c : BankList.values()) {
            if (c.bureauName.equalsIgnoreCase(v)) {
                return c;
            }
        }
        return null;
    }



    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPerfiosName() {
        return perfiosName;
    }

    public void setPerfiosName(String perfiosName) {
        this.perfiosName = perfiosName;
    }

    public String getPerfiosId() {
        return perfiosId;
    }

    public void setPerfiosId(String perfiosId) {
        this.perfiosId = perfiosId;
    }

    public String getFinbitName() {
        return finbitName;
    }

    public void setFinbitName(String finbitName) {
        this.finbitName = finbitName;
    }

    public String getOrgId() {
        return orgId;
    }

    public String getBureauName() {
        return bureauName;
    }
}
