package com.opl.mudra.api.enums.oneform;

public enum LogDateTypeMaster {
	APPLY_LOAN(1,"APPLY_LOAN","APPLY_LOAN"),
	PROFILE_NEXT(2,"PROFILE_NEXT","PROFILE_NEXT"),
	PRIMARY_NEXT(3,"PRIMARY_NEXT","PRIMARY_NEXT"),
	TEASER_SUBMIT(4,"TEASER_SUBMIT","TEASER_SUBMIT"),
	FINAL_SUBMIT(5,"FINAL_SUBMIT","FINAL_SUBMIT"),
	FP_PRIMARY_ACCEPT(6,"FP_PRIMARY_ACCEPT","FP_PRIMARY_ACCEPT"),
	FS_PRIMARY_ACCEPT(7,"FS_PRIMARY_ACCEPT","FS_PRIMARY_ACCEPT"),
	FP_PRIMARY_HOLD(8,"FP_PRIMARY_HOLD","FP_PRIMARY_HOLD"),
	FS_PRIMARY_HOLD(9,"FS_PRIMARY_HOLD","FS_PRIMARY_HOLD"),
	FS_PRIMARY_REJECT(10,"FS_PRIMARY_REJECT","FS_PRIMARY_REJECT"),
	FP_PRIMARY_REJECT(11,"FP_PRIMARY_REJECT","FP_PRIMARY_REJECT"),
	FS_FINAL_APPROVED(12,"FS_FINAL_APPROVED","FS_FINAL_APPROVED"),
	FP_FINAL_APPROVED(13,"FP_FINAL_APPROVED","FP_FINAL_APPROVED"),
	FS_FINAL_HOLD(14,"FS_FINAL_HOLD","FS_FINAL_HOLD"),
	FP_FINAL_HOLD(15,"FP_FINAL_HOLD","FP_FINAL_HOLD"),
	FS_FINAL_REJECT(16,"FS_FINAL_REJECT","FS_FINAL_REJECT"),
	FP_FINAL_REJECT(17,"FP_FINAL_REJECT","FP_FINAL_REJECT"),
	FS_DIRECT_SENT(18,"FS_DIRECT_SENT","FS_DIRECT_SENT"),
	FP_DIRECT_SENT(19,"FP_DIRECT_SENT","FP_DIRECT_SENT"),
	FS_DIRECT_RECEIVED_HOLD_AT_PRIMARY(20,"FS_DIRECT_RECEIVED_HOLD_AT_PRIMARY","FS_DIRECT_RECEIVED_HOLD_AT_PRIMARY"),
	FP_DIRECT_RECEIVED_HOLD_AT_PRIMARY(21,"FP_DIRECT_RECEIVED_HOLD_AT_PRIMARY","FP_DIRECT_RECEIVED_HOLD_AT_PRIMARY"),
	FS_DIRECT_RECEIVED_REJECT_AT_PRIMARY(22,"FS_DIRECT_RECEIVED_REJECT_AT_PRIMARY","FS_DIRECT_RECEIVED_REJECT_AT_PRIMARY"),
	FP_DIRECT_RECEIVED_REJECT_AT_PRIMARY(23,"FP_DIRECT_RECEIVED_REJECT_AT_PRIMARY","FP_DIRECT_RECEIVED_REJECT_AT_PRIMARY"),
	FS_DIRECT_RECEIVED_APPROVED_AT_FINAL(24,"FS_DIRECT_RECEIVED_APPROVED_AT_FINAL","FS_DIRECT_RECEIVED_APPROVED_AT_FINAL"),
	FP_DIRECT_RECEIVED_APPROVED_AT_FINAL(25,"FP_DIRECT_RECEIVED_APPROVED_AT_FINAL","FP_DIRECT_RECEIVED_APPROVED_AT_FINAL"),
	FS_DIRECT_RECEIVED_HOLD_AT_FINAL(26,"FS_DIRECT_RECEIVED_HOLD_AT_FINAL","FS_DIRECT_RECEIVED_HOLD_AT_FINAL"),
	FP_DIRECT_RECEIVED_HOLD_AT_FINAL(27,"FP_DIRECT_RECEIVED_HOLD_AT_FINAL","FP_DIRECT_RECEIVED_HOLD_AT_FINAL"),
	FS_DIRECT_RECEIVED_REJECT_AT_FINAL(28,"FS_DIRECT_RECEIVED_REJECT_AT_FINAL","FS_DIRECT_RECEIVED_REJECT_AT_FINAL"),
	FP_DIRECT_RECEIVED_REJECT_AT_FINAL(29,"FP_DIRECT_RECEIVED_REJECT_AT_FINAL","FP_DIRECT_RECEIVED_REJECT_AT_FINAL"),
	FS_DIRECT_RECEIVED_ACCEPT(30,"FS_DIRECT_RECEIVED_ACCEPT","FS_DIRECT_RECEIVED_ACCEPT"),
	FP_DIRECT_RECEIVED_ACCEPT(31,"FP_DIRECT_RECEIVED_ACCEPT","FP_DIRECT_RECEIVED_ACCEPT"),
	FS_DIRECT_RECEIVED_DECLINE(32,"FS_DIRECT_RECEIVED_DECLINE","FS_DIRECT_RECEIVED_DECLINE"),
	FP_DIRECT_RECEIVED_DECLINE(33,"FP_DIRECT_RECEIVED_DECLINE","FP_DIRECT_RECEIVED_DECLINE"),
	FS_PUBLISH_FUNDED(34,"FS_PUBLISH_FUNDED","FS_PUBLISH_FUNDED"),
	FP_PUBLISH_FUNDED(35,"FP_PUBLISH_FUNDED","FP_PUBLISH_FUNDED");
	private final Integer id;
	private final String value;
	private final String description;
	LogDateTypeMaster(Integer id, String value, String description) {
	this.id = id;
	this.value = value;
	this.description = description;
}

public Integer getId() {
	return id;
}

public String getValue() {
	return value;
}

public String getDescription() {
	return description;
}
	public static LogDateTypeMaster getById(Integer id) {
	switch (id) {
	case 1:
		return APPLY_LOAN;
	case 2:
		return PROFILE_NEXT;
	case 3:
		return PRIMARY_NEXT;
	case 4:
		return TEASER_SUBMIT;
	case 5:
		return FINAL_SUBMIT;
	case 6:
		return FP_PRIMARY_ACCEPT;
	case 7:
		return FS_PRIMARY_ACCEPT;
	case 8:
		return FP_PRIMARY_HOLD;
	case 9:
		return FS_PRIMARY_HOLD;
	case 10:
		return FS_PRIMARY_REJECT;
	case 11:
		return FP_PRIMARY_REJECT;
	case 12:
		return FS_FINAL_APPROVED;
	case 13:
		return FP_FINAL_APPROVED;
	case 14:
		return FS_FINAL_HOLD;
	case 15:
		return FP_FINAL_HOLD;
	case 16:
		return FS_FINAL_REJECT;
	case 17:
		return FP_FINAL_REJECT;
	case 18:
		return FS_DIRECT_SENT;
	case 19:
		return FP_DIRECT_SENT;
	case 20:
		return FS_DIRECT_RECEIVED_HOLD_AT_PRIMARY;
	case 21:
		return FP_DIRECT_RECEIVED_HOLD_AT_PRIMARY;
	case 22:
		return FS_DIRECT_RECEIVED_REJECT_AT_PRIMARY;
	case 23:
		return FP_DIRECT_RECEIVED_REJECT_AT_PRIMARY;
	case 24:
		return FS_DIRECT_RECEIVED_APPROVED_AT_FINAL;
	case 25:
		return FP_DIRECT_RECEIVED_APPROVED_AT_FINAL;
	case 26:
		return FS_DIRECT_RECEIVED_HOLD_AT_FINAL;
	case 27:
		return FP_DIRECT_RECEIVED_HOLD_AT_FINAL;
	case 28:
		return FS_DIRECT_RECEIVED_REJECT_AT_FINAL;
	case 29:
		return FP_DIRECT_RECEIVED_REJECT_AT_FINAL;
	case 30:
		return FS_DIRECT_RECEIVED_ACCEPT;
	case 31:
		return FP_DIRECT_RECEIVED_ACCEPT;
	case 32:
		return FS_DIRECT_RECEIVED_DECLINE;
	case 33:
		return FP_DIRECT_RECEIVED_DECLINE;
	case 34:
		return FS_PUBLISH_FUNDED;
	case 35:
		return FP_PUBLISH_FUNDED;
	default:
		return null;
	}
}
	public static LogDateTypeMaster[] getAll() {
		return LogDateTypeMaster.values();

	}
}
