
CREATE TABLE `fp_auto_loan_details` (
  `fp_product_id` BIGINT(20) UNSIGNED NOT NULL,
  `currency` INT(2) DEFAULT NULL,    
  `min_age` DOUBLE DEFAULT NULL,
  `max_age` DOUBLE DEFAULT NULL,  
  `min_tenure` DOUBLE DEFAULT NULL,
  `max_tenure` DOUBLE DEFAULT NULL,      
  `is_age_display` BIT(1) DEFAULT b'0',
  `is_age_mandatory` BIT(1) DEFAULT b'0',  
  `is_tenure_display` BIT(1) DEFAULT b'0',
  `is_tenure_mandatory` BIT(1) DEFAULT b'0',
  `is_geographical_display` BIT(1) DEFAULT b'0',
  `is_geographical_mandatory` BIT(1) DEFAULT b'0',    
  `min_net_monthly_income_range` DOUBLE DEFAULT NULL,
  `max_net_monthly_income_range` DOUBLE DEFAULT NULL,
  `is_net_monthly_income_range_display` BIT(1) DEFAULT NULL,
  `is_net_monthly_income_range_mandatory` BIT(1) DEFAULT NULL,  
  `max_dpds` INT(11) DEFAULT NULL,
  `is_dpds_display` BIT(1) DEFAULT NULL,
  `is_dpds_mandatory` BIT(1) DEFAULT NULL,
  `is_current_employment_status_display` BIT(1) DEFAULT NULL,
  `is_current_employment_status_mandatory` BIT(1) DEFAULT NULL,
  `is_loan_purpose_display` BIT(1) DEFAULT NULL,
  `is_loan_purpose_mandatory` BIT(1) DEFAULT NULL,
  `is_residential_status_display` BIT(1) DEFAULT NULL,
  `is_residential_status_mandatory` BIT(1) DEFAULT NULL,
  `is_borrower_type_display` BIT(1) DEFAULT NULL,
  `is_borrower_type_mandatory` BIT(1) DEFAULT NULL,
  `min_bank_relationship` INT(11) DEFAULT NULL,
  `max_bank_relationship` INT(2) DEFAULT NULL,
  `is_bank_relationship_display` BIT(1) DEFAULT NULL,
  `is_bank_relationship_mandatory` BIT(1) DEFAULT NULL,
  `is_salary_mode_display` BIT(1) DEFAULT NULL,
  `is_salary_mode_mandatory` BIT(1) DEFAULT NULL,
  `is_borr_sal_acc_display` BIT(1) DEFAULT NULL,
  `is_borr_sal_acc_mandatory` BIT(1) DEFAULT NULL,    
  `is_current_job_experience_display` BIT(1) DEFAULT NULL,
  `is_current_job_experience_mandatory` BIT(1) DEFAULT NULL,
  `is_total_job_experience_display` BIT(1) DEFAULT NULL,
  `is_total_job_experience_mandatory` BIT(1) DEFAULT NULL,
  `min_total_job_experience` INT(2) DEFAULT NULL,
  `max_total_job_experience` INT(2) DEFAULT NULL,
  `max_current_job_experience` INT(2) DEFAULT NULL,
  `min_current_job_experience` INT(2) DEFAULT NULL,
  `min_bureau_score` INT(11) DEFAULT NULL,
  `max_bureau_score` INT(11) DEFAULT NULL,
  `is_bureau_score_display` BIT(1) DEFAULT NULL,
  `is_bureau_score_mandatory` BIT(1) DEFAULT NULL,
  `is_risk_score_model_coapp_display` BIT(1) DEFAULT NULL,
  `is_risk_score_model_coapp_mandatory` BIT(1) DEFAULT NULL,
  `is_risk_score_model_display` BIT(1) DEFAULT NULL,
  `is_risk_score_model_mandatory` BIT(1) DEFAULT NULL,
  `min_risk_score_model_co_app` DOUBLE DEFAULT NULL,
  `min_risk_score_model` DOUBLE DEFAULT NULL,
  `no_of_co_app_or_gua` INT(11) DEFAULT NULL,
  `is_consider_income_of_co_app` BIT(1) DEFAULT NULL,  
  `max_age_allowed` INT(11) DEFAULT NULL,
  `assessment_method_id` INT(11) DEFAULT NULL,
  `is_gross_net_income` BIT(1) DEFAULT NULL,
  `mon_income_type` INT(2) DEFAULT NULL,
  `foir` DOUBLE DEFAULT NULL,
  `is_times_multiplier_income` BIT(1) DEFAULT NULL,
  `mon_income_multiplier_type` INT(2) DEFAULT NULL,
  `times_multiplier` INT(1) DEFAULT NULL,
  `is_ltv` BIT(1) DEFAULT NULL,  
  `ltv_for_eligibility` INT(2) DEFAULT NULL,
  `is_purpose_loan_display` BIT(1) DEFAULT NULL,
  `is_purpose_loan_mandatory` BIT(1) DEFAULT NULL,
  `is_employment_with_display` BIT(1) DEFAULT NULL,
  `is_employment_with_mandatory` BIT(1) DEFAULT NULL,
  `is_self_employed_with_display` BIT(1) DEFAULT NULL,
  `is_self_employed_with_mandatory` BIT(1) DEFAULT NULL,
  `salary_ac_type` INT(1) DEFAULT NULL,
  `min_gross_monthly_income_range` DOUBLE DEFAULT NULL,
  `max_gross_monthly_income_range` DOUBLE DEFAULT NULL,
  `is_gross_monthly_income_range_display` BIT(1) DEFAULT NULL,
  `is_gross_monthly_income_range_mandatory` BIT(1) DEFAULT NULL,
  `min_net_take_home_salary` DOUBLE DEFAULT NULL,
  `is_min_net_take_home_salary_display` BIT(1) DEFAULT b'0',
  `is_min_net_take_home_salary_mandatory` BIT(1) DEFAULT b'0',
  `min_bureau_score_less_than6_month` DOUBLE DEFAULT NULL,
  `noBureauCreditHistory` BIT(1) DEFAULT b'1',
  `no_bureau_credit_history` BIT(1) DEFAULT b'1',
  `min_risk_score_model_oth_thn_sal` DOUBLE DEFAULT NULL,
  `min_risk_score_model_co_app_oth_thn_sal` DOUBLE DEFAULT NULL,
  `is_risk_score_model_oth_thn_sal_display` BIT(1) DEFAULT b'0',
  `is_risk_score_model_oth_thn_sal_mandatory` BIT(1) DEFAULT b'0',
  `is_risk_score_model_coapp_oth_thn_sal_display` BIT(1) DEFAULT b'0',
  `is_risk_score_model_coapp_oth_thn_sal_mandatory` BIT(1) DEFAULT b'0',
  `min_nmtlr` DOUBLE DEFAULT NULL,
  `max_nmtlr` DOUBLE DEFAULT NULL,      
  `is_nmtlr_display` BIT(1) DEFAULT b'0',
  `is_nmtlr_mandatory` BIT(1) DEFAULT b'0',
  `min_emi_mi` DOUBLE DEFAULT NULL,
  `max_emi_mi` DOUBLE DEFAULT NULL,      
  `is_emi_mi_display` BIT(1) DEFAULT b'0',
  `is_emi_mi_mandatory` BIT(1) DEFAULT b'0',
  `min_collateral_security` DOUBLE DEFAULT NULL,
  `max_collateral_security` DOUBLE DEFAULT NULL,      
  `is_collateral_security_display` BIT(1) DEFAULT b'0',
  `is_collateral_security_mandatory` BIT(1) DEFAULT b'0',
  `is_repayment_mode_display` BIT(1) DEFAULT b'0',
  `is_repayment_mode_mandatory` BIT(1) DEFAULT b'0',
  PRIMARY KEY (`fp_product_id`),
  CONSTRAINT `fp_auto_loan_details_ibfk_1` FOREIGN KEY (`fp_product_id`) REFERENCES `fp_product_master` (`fp_product_id`)
) ENGINE=INNODB DEFAULT CHARSET=latin1;





CREATE TABLE `fp_auto_loan_details_temp` (
  `fp_product_id` BIGINT(20) UNSIGNED NOT NULL,
  `currency` INT(2) DEFAULT NULL,    
  `min_age` DOUBLE DEFAULT NULL,
  `max_age` DOUBLE DEFAULT NULL,  
  `min_tenure` DOUBLE DEFAULT NULL,
  `max_tenure` DOUBLE DEFAULT NULL,      
  `is_age_display` BIT(1) DEFAULT b'0',
  `is_age_mandatory` BIT(1) DEFAULT b'0',  
  `is_tenure_display` BIT(1) DEFAULT b'0',
  `is_tenure_mandatory` BIT(1) DEFAULT b'0',
  `is_geographical_display` BIT(1) DEFAULT b'0',
  `is_geographical_mandatory` BIT(1) DEFAULT b'0',    
  `min_net_monthly_income_range` DOUBLE DEFAULT NULL,
  `max_net_monthly_income_range` DOUBLE DEFAULT NULL,
  `is_net_monthly_income_range_display` BIT(1) DEFAULT NULL,
  `is_net_monthly_income_range_mandatory` BIT(1) DEFAULT NULL,  
  `max_dpds` INT(11) DEFAULT NULL,
  `is_dpds_display` BIT(1) DEFAULT NULL,
  `is_dpds_mandatory` BIT(1) DEFAULT NULL,
  `is_current_employment_status_display` BIT(1) DEFAULT NULL,
  `is_current_employment_status_mandatory` BIT(1) DEFAULT NULL,
  `is_loan_purpose_display` BIT(1) DEFAULT NULL,
  `is_loan_purpose_mandatory` BIT(1) DEFAULT NULL,
  `is_residential_status_display` BIT(1) DEFAULT NULL,
  `is_residential_status_mandatory` BIT(1) DEFAULT NULL,
  `is_borrower_type_display` BIT(1) DEFAULT NULL,
  `is_borrower_type_mandatory` BIT(1) DEFAULT NULL,
  `min_bank_relationship` INT(11) DEFAULT NULL,
  `max_bank_relationship` INT(2) DEFAULT NULL,
  `is_bank_relationship_display` BIT(1) DEFAULT NULL,
  `is_bank_relationship_mandatory` BIT(1) DEFAULT NULL,
  `is_salary_mode_display` BIT(1) DEFAULT NULL,
  `is_salary_mode_mandatory` BIT(1) DEFAULT NULL,
  `is_borr_sal_acc_display` BIT(1) DEFAULT NULL,
  `is_borr_sal_acc_mandatory` BIT(1) DEFAULT NULL,    
  `is_current_job_experience_display` BIT(1) DEFAULT NULL,
  `is_current_job_experience_mandatory` BIT(1) DEFAULT NULL,
  `is_total_job_experience_display` BIT(1) DEFAULT NULL,
  `is_total_job_experience_mandatory` BIT(1) DEFAULT NULL,
  `min_total_job_experience` INT(2) DEFAULT NULL,
  `max_total_job_experience` INT(2) DEFAULT NULL,
  `max_current_job_experience` INT(2) DEFAULT NULL,
  `min_current_job_experience` INT(2) DEFAULT NULL,
  `min_bureau_score` INT(11) DEFAULT NULL,
  `max_bureau_score` INT(11) DEFAULT NULL,
  `is_bureau_score_display` BIT(1) DEFAULT NULL,
  `is_bureau_score_mandatory` BIT(1) DEFAULT NULL,
  `is_risk_score_model_coapp_display` BIT(1) DEFAULT NULL,
  `is_risk_score_model_coapp_mandatory` BIT(1) DEFAULT NULL,
  `is_risk_score_model_display` BIT(1) DEFAULT NULL,
  `is_risk_score_model_mandatory` BIT(1) DEFAULT NULL,
  `min_risk_score_model_co_app` DOUBLE DEFAULT NULL,
  `min_risk_score_model` DOUBLE DEFAULT NULL,
  `no_of_co_app_or_gua` INT(11) DEFAULT NULL,
  `is_consider_income_of_co_app` BIT(1) DEFAULT NULL,  
  `max_age_allowed` INT(11) DEFAULT NULL,
  `assessment_method_id` INT(11) DEFAULT NULL,
  `is_gross_net_income` BIT(1) DEFAULT NULL,
  `mon_income_type` INT(2) DEFAULT NULL,
  `foir` DOUBLE DEFAULT NULL,
  `is_times_multiplier_income` BIT(1) DEFAULT NULL,
  `mon_income_multiplier_type` INT(2) DEFAULT NULL,
  `times_multiplier` INT(1) DEFAULT NULL,
  `is_ltv` BIT(1) DEFAULT NULL,  
  `ltv_for_eligibility` INT(2) DEFAULT NULL,
  `is_purpose_loan_display` BIT(1) DEFAULT NULL,
  `is_purpose_loan_mandatory` BIT(1) DEFAULT NULL,
  `is_employment_with_display` BIT(1) DEFAULT NULL,
  `is_employment_with_mandatory` BIT(1) DEFAULT NULL,
  `is_self_employed_with_display` BIT(1) DEFAULT NULL,
  `is_self_employed_with_mandatory` BIT(1) DEFAULT NULL,
  `salary_ac_type` INT(1) DEFAULT NULL,
  `min_gross_monthly_income_range` DOUBLE DEFAULT NULL,
  `max_gross_monthly_income_range` DOUBLE DEFAULT NULL,
  `is_gross_monthly_income_range_display` BIT(1) DEFAULT NULL,
  `is_gross_monthly_income_range_mandatory` BIT(1) DEFAULT NULL,
  `min_net_take_home_salary` DOUBLE DEFAULT NULL,
  `is_min_net_take_home_salary_display` BIT(1) DEFAULT b'0',
  `is_min_net_take_home_salary_mandatory` BIT(1) DEFAULT b'0',
  `min_bureau_score_less_than6_month` DOUBLE DEFAULT NULL,
  `noBureauCreditHistory` BIT(1) DEFAULT b'1',
  `no_bureau_credit_history` BIT(1) DEFAULT b'1',
  `min_risk_score_model_oth_thn_sal` DOUBLE DEFAULT NULL,
  `min_risk_score_model_co_app_oth_thn_sal` DOUBLE DEFAULT NULL,
  `is_risk_score_model_oth_thn_sal_display` BIT(1) DEFAULT b'0',
  `is_risk_score_model_oth_thn_sal_mandatory` BIT(1) DEFAULT b'0',
  `is_risk_score_model_coapp_oth_thn_sal_display` BIT(1) DEFAULT b'0',
  `is_risk_score_model_coapp_oth_thn_sal_mandatory` BIT(1) DEFAULT b'0',
  `min_nmtlr` DOUBLE DEFAULT NULL,
  `max_nmtlr` DOUBLE DEFAULT NULL,      
  `is_nmtlr_display` BIT(1) DEFAULT b'0',
  `is_nmtlr_mandatory` BIT(1) DEFAULT b'0',
  `min_emi_mi` DOUBLE DEFAULT NULL,
  `max_emi_mi` DOUBLE DEFAULT NULL,      
  `is_emi_mi_display` BIT(1) DEFAULT b'0',
  `is_emi_mi_mandatory` BIT(1) DEFAULT b'0',
  `min_collateral_security` DOUBLE DEFAULT NULL,
  `max_collateral_security` DOUBLE DEFAULT NULL,      
  `is_collateral_security_display` BIT(1) DEFAULT b'0',
  `is_collateral_security_mandatory` BIT(1) DEFAULT b'0',
  `is_repayment_mode_display` BIT(1) DEFAULT b'0',
  `is_repayment_mode_mandatory` BIT(1) DEFAULT b'0',
  PRIMARY KEY (`fp_product_id`),
  CONSTRAINT `fp_auto_loan_details_temp_ibfk_1` FOREIGN KEY (`fp_product_id`) REFERENCES `fp_product_master_temp` (`fp_product_id`)
) ENGINE=INNODB DEFAULT CHARSET=latin1;


ALTER TABLE `loan_application`.`fp_auto_loan_details` ADD COLUMN  is_on_road_price BIT(1) DEFAULT FALSE;
ALTER TABLE `loan_application`.`fp_auto_loan_details_temp` ADD COLUMN  is_on_road_price BIT(1) DEFAULT FALSE;
ALTER TABLE `loan_application`.`fp_auto_loan_details` ADD COLUMN  is_ex_showroom_price BIT(1) DEFAULT FALSE;
ALTER TABLE `loan_application`.`fp_auto_loan_details_temp` ADD COLUMN  is_ex_showroom_price BIT(1) DEFAULT FALSE;
	

	
	

ALTER TABLE `loan_application`.`fp_auto_loan_details` ADD COLUMN min_vehicle_age DOUBLE DEFAULT NULL;
ALTER TABLE `loan_application`.`fp_auto_loan_details` ADD COLUMN max_vehicle_age DOUBLE DEFAULT NULL;
ALTER TABLE `loan_application`.`fp_auto_loan_details` ADD COLUMN is_vehicle_age_display BIT(1) DEFAULT FALSE;
ALTER TABLE `loan_application`.`fp_auto_loan_details` ADD COLUMN is_vehicle_age_mandatory BIT(1) DEFAULT FALSE;
ALTER TABLE `loan_application`.`fp_auto_loan_details_temp` ADD COLUMN min_vehicle_age DOUBLE DEFAULT NULL;
ALTER TABLE `loan_application`.`fp_auto_loan_details_temp` ADD COLUMN max_vehicle_age DOUBLE DEFAULT NULL;
ALTER TABLE `loan_application`.`fp_auto_loan_details_temp` ADD COLUMN is_vehicle_age_display BIT(1) DEFAULT FALSE;
ALTER TABLE `loan_application`.`fp_auto_loan_details_temp` ADD COLUMN is_vehicle_age_mandatory BIT(1) DEFAULT FALSE;