UPDATE `loan_application`.`fs_corporate_final_mcq_details` apm INNER JOIN `loan_application`.`proposal_details` pd ON apm.application_id=pd.application_id SET apm.proposal_mapping_id = pd.id WHERE pd.is_active=TRUE;
UPDATE `loan_application`.`fs_sector_subsector_details` apm INNER JOIN `loan_application`.`proposal_details` pd ON apm.application_id=pd.application_id SET apm.proposal_mapping_id = pd.id WHERE pd.is_active = TRUE;
UPDATE `loan_application`.`industry_sector_details` apm INNER JOIN `loan_application`.`proposal_details` pd ON apm.application_id=pd.application_id SET apm.proposal_mapping_id = pd.id WHERE pd.is_active = TRUE;
UPDATE `loan_application`.`fs_corporate_existing_product_details` apm INNER JOIN `loan_application`.`proposal_details` pd ON apm.application_id=pd.application_id SET apm.proposal_mapping_id = pd.id WHERE pd.is_active = TRUE;
UPDATE `loan_application`.`fs_corporate_associated_concern_details` apm INNER JOIN `loan_application`.`proposal_details` pd ON apm.application_id=pd.application_id SET apm.proposal_mapping_id = pd.id WHERE pd.is_active = TRUE;
UPDATE `loan_application`.`fs_corporate_security_corporate_details` apm INNER JOIN `loan_application`.`proposal_details` pd ON apm.application_id=pd.application_id SET apm.proposal_mapping_id = pd.id WHERE pd.is_active = TRUE;
UPDATE `loan_application`.`fs_corporate_credit_rating_organization_details` apm INNER JOIN `loan_application`.`proposal_details` pd ON apm.application_id=pd.application_id SET apm.proposal_mapping_id = pd.id WHERE pd.is_active = TRUE;
UPDATE `loan_application`.`fs_corporate_finance_means_details` apm INNER JOIN `loan_application`.`proposal_details` pd ON apm.application_id=pd.application_id SET apm.proposal_mapping_id = pd.id WHERE pd.is_active = TRUE;
UPDATE `loan_application`.`fs_corporate_project_cost_details` apm INNER JOIN `loan_application`.`proposal_details` pd ON apm.application_id=pd.application_id SET apm.proposal_mapping_id = pd.id WHERE pd.is_active = TRUE;
UPDATE `loan_application`.`fs_ddr_form_details` apm INNER JOIN `loan_application`.`proposal_details` pd ON apm.application_id=pd.application_id SET apm.proposal_mapping_id = pd.id WHERE pd.is_active = TRUE;
UPDATE `loan_application`.`product_storage_details` apm INNER JOIN `loan_application`.`proposal_details` pd ON apm.application_id=pd.application_id SET apm.proposal_mapping_id = pd.id WHERE pd.is_active = TRUE;
UPDATE `loan_application`.`fs_corporate_promotor_background_details` apm INNER JOIN `loan_application`.`proposal_details` pd ON apm.application_id=pd.application_id SET apm.proposal_mapping_id = pd.id WHERE pd.is_active = TRUE;
UPDATE `loan_application`.`fs_corporate_current_financial_arrangements_details` apm INNER JOIN `loan_application`.`proposal_details` pd ON apm.application_id=pd.application_id SET apm.proposal_mapping_id = pd.id WHERE pd.is_active = TRUE;
UPDATE `loan_application`.`fs_corporate_director_background_details` apm INNER JOIN `loan_application`.`proposal_details` pd ON apm.application_id=pd.application_id SET apm.proposal_mapping_id = pd.id WHERE pd.is_active = TRUE;
UPDATE `loan_application`.`fs_corporate_bs_profitibility_statement_details` apm INNER JOIN `loan_application`.`proposal_details` pd ON apm.application_id=pd.application_id SET apm.proposal_mapping_id = pd.id WHERE pd.is_active = TRUE;
UPDATE `loan_application`.`application_status_audit` apm INNER JOIN `loan_application`.`proposal_details` pd ON apm.application_id=pd.application_id SET apm.proposal_mapping_id = pd.id WHERE pd.is_active = TRUE;
UPDATE `loan_application`.`fs_corporate_ownership_details` apm INNER JOIN `loan_application`.`proposal_details` pd ON apm.application_id=pd.application_id SET apm.proposal_mapping_id = pd.id WHERE pd.is_active = TRUE;
UPDATE `loan_application`.`fs_corporate_achievement_details` apm INNER JOIN `loan_application`.`proposal_details` pd ON apm.application_id=pd.application_id SET apm.proposal_mapping_id = pd.id WHERE pd.is_active = TRUE;
UPDATE `loan_application`.`fs_corporate_guarantors_corporate_details` apm INNER JOIN `loan_application`.`proposal_details` pd ON apm.application_id=pd.application_id SET apm.proposal_mapping_id = pd.id WHERE pd.is_active = TRUE;
UPDATE `loan_application`.`fs_corporate_proposed_product_details` apm INNER JOIN `loan_application`.`proposal_details` pd ON apm.application_id=pd.application_id SET apm.proposal_mapping_id = pd.id WHERE pd.is_active = TRUE;
INSERT INTO `loan_application`.`fs_corporate_applicant_details` (`application_id`,`organisation_name`,`group_name`,`pan`,`landline_no`,`constitution_id`,`establishment_year`,`establishment_month`,`website_address`,`registered_premise_number`,`registered_street_name`,`registered_land_mark`,`registered_city_id`,`registered_state_id`,`registered_country_id`,`registered_pincode`,`same_as`,`administrative_premise_number`,`administrative_street_name`,`administrative_land_mark`,`administrative_city_id`,`administrative_state_id`,`administrative_country_id`,`administrative_pincode`,`about_us`,`key_verical_funding`,`latitude`,`longitude`,`created_by`,-- `modified_by`,
    `created_date`,--`modified_date`,
    `is_active`,`key_vertical_sector`,`key_vertical_subsector`,`gstin`,`email`,`aadhar`,`credit_rating_id`,`cont_liability_fy_amt`,`cont_liability_sy_amt`,`cont_liability_ty_amt`,`cont_liability_year`,`not_applicable`,`total_cost_of_estimate`,`total_means_of_finance`,`collateral_security_amt_total`,`share_price_face_value`,`share_price_market_value`,`msme_registration_number`,`administrative_dist_mapping_id`,`registered_dist_mapping_id`,`establishment_date`,`environmental_impact_id`,`is_gst_completed`,`is_itr_completed`,`proposal_mapping_id`,`business_since_year`,`business_since_month`)
    SELECT fsad.`application_id`,fsad.`organisation_name`,fsad.`group_name`,fsad.`pan`,fsad.`landline_no`,
    fsad.`constitution_id`,fsad.`establishment_year`,fsad.`establishment_month`,fsad.`website_address`,
    fsad.`registered_premise_number`,fsad.`registered_street_name`,fsad.`registered_land_mark`,
    fsad.`registered_city_id`,fsad.`registered_state_id`,fsad.`registered_country_id`,fsad.`registered_pincode`,
    fsad.`same_as`,fsad.`administrative_premise_number`,fsad.`administrative_street_name`,fsad.`administrative_land_mark`,
    fsad.`administrative_city_id`,fsad.`administrative_state_id`,fsad.`administrative_country_id`,fsad.`administrative_pincode`,
    fsad.`about_us`,fsad.`key_verical_funding`,fsad.`latitude`,fsad.`longitude`,fsad.`created_by`,-- fsad.`modified_by`,
    fsad.`created_date`,
    -- fsad.`modified_date`,
    fsad.`is_active`,fsad.`key_vertical_sector`,fsad.`key_vertical_subsector`,fsad.`gstin`,fsad.`email`,fsad.`aadhar`,
    fsad.`credit_rating_id`,fsad.`cont_liability_fy_amt`,fsad.`cont_liability_sy_amt`,fsad.`cont_liability_ty_amt`,fsad.`cont_liability_year`,
    fsad.`not_applicable`,fsad.`total_cost_of_estimate`,fsad.`total_means_of_finance`,fsad.`collateral_security_amt_total`,fsad.`share_price_face_value`,
    fsad.`share_price_market_value`,fsad.`msme_registration_number`,fsad.`administrative_dist_mapping_id`,fsad.`registered_dist_mapping_id`,
    fsad.`establishment_date`,fsad.`environmental_impact_id`,fsad.`is_gst_completed`,fsad.`is_itr_completed`,pd.id AS proposal_mapping_id,
    fsad.`business_since_year`,fsad.`business_since_month` FROM `loan_application`.`fs_corporate_applicant_details` fsad
    INNER JOIN `loan_application`.`proposal_details` pd ON fsad.`application_id` = pd.`application_id` WHERE fsad.`proposal_mapping_id` IS NULL AND pd.is_active=TRUE;

UPDATE `loan_application`.`fs_corporate_applicant_details` AS apm
INNER JOIN `loan_application`.`proposal_details` pd ON pd.application_id=apm.application_id
SET apm.proposal_mapping_id = pd.id
WHERE pd.is_active=TRUE;

INSERT INTO `loan_application`.`fs_corporate_cma_assets_details`
        (
        `advance_payment_taxes`,
        `advance_to_supplier_raw_materials`,
        `advance_to_suppliers_capital_goods`,
        `any_other`,
        `bad_or_doubtful_expenses`,
        `cash_and_bank_balance`,
        `current_ratio`,
        `deferred_receviables`,
        `deferred_receviables_others`,
        `depreciation_to_date`,
        `export_receivables`,
        `finished_goods`,
        `fixed_deposits_with_banks`,
        `good_will`,
        `government_and_other_trustee`,
        `gross_block`,
        `instalments_deferred`,
        `inventory`,
        `investments`,
        `investments_in_subsidiary`,
        `investments_or_book_debts`,
        `net_block`,
        `net_working_capital`,
        `non_consumable_store_and_spares`,
        `other_consumable_spares`,
        `other_consumable_spares_imported`,
        `other_consumable_spares_indegenous`,
        `other_current_assets`,
        `other_non_current_assets`,
        `others`,
        `patents`,
        `prelim_expenses`,
        `raw_material`,
        `raw_material_imported`,
        `raw_material_indegenous`,
        `receivable_other_than_defferred`,
        `stock_in_process`,
        `tangible_net_worth`,
        `total_assets`,
        `total_current_assets`,
        `total_intangible_assets`,
        `total_other_non_current_assets`,
        `total_out_side_liability`,
        `total_term_liability`,
        `year`,
        `deferred_tax_assets`,
        `intangible_assets`,
        `storage_details_id`,
        `application_id`,
        `created_date`,
        -- `modified_date`,
        `created_by`,
        -- `modified_by`,
        `is_active`,
        `land_building`,
        `plant_machines`,
        `impairment_asset`,
        `others_pre_operative_expenses_pending`,
        `others_assets_in_transit`,
        `others_other`,
        `total_other_nca_patent`,
        `total_other_nca_goodwill`,
        `total_other_nca_prelimnary_expenses`,
        `total_other_nca_bad_expenses`,
        `total_other_nca_other`,
        `other_nca_other_capital_work_inprogress`,
        `gross_block_1`,
        `gross_block_2`,
        `gross_block_3`,
        `gross_block_4`,
        `financial_yearly_statement`,
        `other_income_need_to_chek_asset`,
        `proposal_mapping_id`
        )
        SELECT
            fccsd.`advance_payment_taxes`,
            fccsd.`advance_to_supplier_raw_materials`,
            fccsd.`advance_to_suppliers_capital_goods`,
            fccsd.`any_other`,
            fccsd.`bad_or_doubtful_expenses`,
            fccsd.`cash_and_bank_balance`,
            fccsd.`current_ratio`,
            fccsd.`deferred_receviables`,
            fccsd.`deferred_receviables_others`,
            fccsd.`depreciation_to_date`,
            fccsd.`export_receivables`,
            fccsd.`finished_goods`,
            fccsd.`fixed_deposits_with_banks`,
            fccsd.`good_will`,
            fccsd.`government_and_other_trustee`,
            fccsd.`gross_block`,
            fccsd.`instalments_deferred`,
            fccsd.`inventory`,
            fccsd.`investments`,
            fccsd.`investments_in_subsidiary`,
            fccsd.`investments_or_book_debts`,
            fccsd.`net_block`,
            fccsd.`net_working_capital`,
            fccsd.`non_consumable_store_and_spares`,
            fccsd.`other_consumable_spares`,
            fccsd.`other_consumable_spares_imported`,
            fccsd.`other_consumable_spares_indegenous`,
            fccsd.`other_current_assets`,
            fccsd.`other_non_current_assets`,
            fccsd.`others`,
            fccsd.`patents`,
            fccsd.`prelim_expenses`,
            fccsd.`raw_material`,
            fccsd.`raw_material_imported`,
            fccsd.`raw_material_indegenous`,
            fccsd.`receivable_other_than_defferred`,
            fccsd.`stock_in_process`,
            fccsd.`tangible_net_worth`,
            fccsd.`total_assets`,
            fccsd.`total_current_assets`,
            fccsd.`total_intangible_assets`,
            fccsd.`total_other_non_current_assets`,
            fccsd.`total_out_side_liability`,
            fccsd.`total_term_liability`,
            fccsd.`year`,
            fccsd.`deferred_tax_assets`,
            fccsd.`intangible_assets`,
            fccsd.`storage_details_id`,
            fccsd.`application_id`,
            NOW(),
            -- fccsd.`modified_date`,
            fccsd.`created_by`,
            -- fccsd.`modified_by`,
            fccsd.`is_active`,
            fccsd.`land_building`,
            fccsd.`plant_machines`,
            fccsd.`impairment_asset`,
            fccsd.`others_pre_operative_expenses_pending`,
            fccsd.`others_assets_in_transit`,
            fccsd.`others_other`,
            fccsd.`total_other_nca_patent`,
            fccsd.`total_other_nca_goodwill`,
            fccsd.`total_other_nca_prelimnary_expenses`,
            fccsd.`total_other_nca_bad_expenses`,
            fccsd.`total_other_nca_other`,
            fccsd.`other_nca_other_capital_work_inprogress`,
            fccsd.`gross_block_1`,
            fccsd.`gross_block_2`,
            fccsd.`gross_block_3`,
            fccsd.`gross_block_4`,
            fccsd.`financial_yearly_statement`,
            fccsd.`other_income_need_to_chek_asset`,
            -- fccsd.proposal_mapping_id,
            pd.`id` AS proposal_mapping_id
            FROM  `loan_application`.`fs_corporate_cma_assets_details` fccsd
            INNER JOIN `loan_application`.`proposal_details` pd ON fccsd.application_id = pd.application_id
            WHERE fccsd.proposal_mapping_id IS NULL AND fccsd.financial_yearly_statement='Audited' AND pd.is_active=TRUE;

UPDATE `loan_application`.`fs_corporate_cma_assets_details` AS apm
INNER JOIN `loan_application`.`proposal_details` pd ON pd.application_id=apm.application_id
SET apm.proposal_mapping_id = pd.id
WHERE (apm.financial_yearly_statement='Projected' OR apm.financial_yearly_statement='Estimated') AND pd.is_active=TRUE;

INSERT INTO `loan_application`.`fs_corporate_cma_liabilities_details`
	(
	`advance_payments_from_customers`,
	`debentures`,
	`deferred_payments_credits`,
	`deferred_tax_liability`,
	`deposits_or_instalments_of_term_loans`,
	`dividend_payable`,
	`from_application_bank`,
	`from_other_banks`,
	`general_reserve`,
	`net_worth`,
	`which_bp_and_bd`,
	`ordinary_shares_capital`,
	`other_current_liability`,
	`other_reservse`,
	`other_statutory_liability`,
	`other_term_liabilies`,
	`others`,
	`preferences_shares`,
	`provisional_for_taxation`,
	`revaluation_reservse`,
	`short_term_borrowing_from_others`,
	`sub_total_a`,
	`sub_total_b`,
	`sundry_creditors`,
	`surplus_or_deficit`,
	`term_deposits`,
	`term_loans`,
	`total_current_liabilities`,
	`total_liability`,
	`total_outside_liabilities`,
	`total_term_liabilities`,
	`year`,
	`storage_details_id`,
	`application_id`,
	`created_date`,
	-- `modified_date`,
	`created_by`,
	-- `modified_by`,
	`is_active`,
	`term_liabilities_secured`,
	`term_liabilities_unsecured`,
	`share_warrents_outstanding`,
	`minority_interest`,
	`other_ncl_unsecured_loans_from_other`,
	`other_ncl_long_term_provisions`,
	`other_ncl_others`,
	`other_ncl`,
	`other_ncl_unsecured_loans_from_promoters`,
	`financial_yearly_statement`,
	`other_income_need_to_chek_lia`,
	`proposal_mapping_id`
	)
	SELECT
	fccld.`advance_payments_from_customers`,
	fccld.`debentures`,
	fccld.`deferred_payments_credits`,
	fccld.`deferred_tax_liability`,
	fccld.`deposits_or_instalments_of_term_loans`,
	fccld.`dividend_payable`,
	fccld.`from_application_bank`,
	fccld.`from_other_banks`,
	fccld.`general_reserve`,
	fccld.`net_worth`,
	fccld.`which_bp_and_bd`,
	fccld.`ordinary_shares_capital`,
	fccld.`other_current_liability`,
	fccld.`other_reservse`,
	fccld.`other_statutory_liability`,
	fccld.`other_term_liabilies`,
	fccld.`others`,
	fccld.`preferences_shares`,
	fccld.`provisional_for_taxation`,
	fccld.`revaluation_reservse`,
	fccld.`short_term_borrowing_from_others`,
	fccld.`sub_total_a`,
	fccld.`sub_total_b`,
	fccld.`sundry_creditors`,
	fccld.`surplus_or_deficit`,
	fccld.`term_deposits`,
	fccld.`term_loans`,
	fccld.`total_current_liabilities`,
	fccld.`total_liability`,
	fccld.`total_outside_liabilities`,
	fccld.`total_term_liabilities`,
	fccld.`year`,
	fccld.`storage_details_id`,
	fccld.`application_id`,
	fccld.`created_date`,
	-- fccld.`modified_date`,
	fccld.`created_by`,
	-- fccld.`modified_by`,
	fccld.`is_active`,
	fccld.`term_liabilities_secured`,
	fccld.`term_liabilities_unsecured`,
	fccld.`share_warrents_outstanding`,
	fccld.`minority_interest`,
	fccld.`other_ncl_unsecured_loans_from_other`,
	fccld.`other_ncl_long_term_provisions`,
	fccld.`other_ncl_others`,
	fccld.`other_ncl`,
	fccld.`other_ncl_unsecured_loans_from_promoters`,
	fccld.`financial_yearly_statement`,
	fccld.`other_income_need_to_chek_lia`,
	pd.`id` AS proposal_mapping_id
	FROM `loan_application`.`fs_corporate_cma_liabilities_details` fccld
	INNER JOIN `loan_application`.`proposal_details` pd ON pd.application_id = fccld.application_id
	WHERE fccld.proposal_mapping_id IS NULL AND fccld.financial_yearly_statement='Audited' AND pd.is_active=TRUE;


	UPDATE `loan_application`.`fs_corporate_cma_liabilities_details` apm
INNER JOIN `loan_application`.`proposal_details` pd ON pd.application_id=apm.application_id
SET apm.proposal_mapping_id = pd.id
WHERE (apm.financial_yearly_statement='Projected' OR apm.financial_yearly_statement='Estimated') AND pd.is_active=TRUE;

INSERT INTO `loan_application`.`fs_corporate_cma_operating_statement_details`
	(
	`op_profit_before_intrest`,
	`add_operating_stock`,
	`add_operating_stock_fg`,
	`add_other_non_op_income`,
	`add_other_revenue_income`,
	`production_cost`,
	`deduct_cl_stock_fg`,
	`deduct_other_items`,
	`deduct_other_non_op_exp`,
	`deduct_stock_in_process`,
	`depreciation`,
	`direct_labour`,
	`dividend_rate`,
	`domestic_sales`,
	`equity_deividend_paid_amt`,
	`expenses_amortised`,
	`export_sales`,
	`interest`,
	`less_excise_duty`,
	`netof_non_op_income_or_expenses`,
	`net_profit_or_loss`,
	`net_sales`,
	`op_profit_after_interest`,
	`other_mfg_expenses`,
	`other_spares`,
	`other_spares_imported`,
	`other_spares_indigenous`,
	`percentage_rise_or_fall`,
	`power_and_fuel`,
	`profit_before_tax_or_loss`,
	`provision_for_deferred_tax`,
	`provision_for_taxes`,
	`raw_materials`,
	`raw_materials_imported`,
	`raw_materials_indigenous`,
	`retained_profit`,
	`retained_profit_or_net_profit`,
	`selling_genl_admn_expenses`,
	`sub_total_cost_Sales`,
	`sub_total_cost_sales_and_selling`,
	`sub_total_expenses`,
	`sub_total_of_cost_sales_and_operating_stock`,
	`sub_total_deduct_and_cost_of_production`,
	`sub_total_of_income`,
	`total_cost_sales`,
	`total_gross_sales`,
	`year`,
	`storage_details_id`,
	`application_id`,
	`created_date`,
	-- `modified_date`,
	`created_by`,
	-- `modified_by`,
	`is_active`,
	`selling_distribution_exp`,
	`general_admin_exp`,
	`financial_yearly_statement`,
	`other_income_need_to_chek_op`,
	`proposal_mapping_id`
	)

SELECT
	fccosd.`op_profit_before_intrest`,
	fccosd.`add_operating_stock`,
	fccosd.`add_operating_stock_fg`,
	fccosd.`add_other_non_op_income`,
	fccosd.`add_other_revenue_income`,
	fccosd.`production_cost`,
	fccosd.`deduct_cl_stock_fg`,
	fccosd.`deduct_other_items`,
	fccosd.`deduct_other_non_op_exp`,
	fccosd.`deduct_stock_in_process`,
	fccosd.`depreciation`,
	fccosd.`direct_labour`,
	fccosd.`dividend_rate`,
	fccosd.`domestic_sales`,
	fccosd.`equity_deividend_paid_amt`,
	fccosd.`expenses_amortised`,
	fccosd.`export_sales`,
	fccosd.`interest`,
	fccosd.`less_excise_duty`,
	fccosd.`netof_non_op_income_or_expenses`,
	fccosd.`net_profit_or_loss`,
	fccosd.`net_sales`,
	fccosd.`op_profit_after_interest`,
	fccosd.`other_mfg_expenses`,
	fccosd.`other_spares`,
	fccosd.`other_spares_imported`,
	fccosd.`other_spares_indigenous`,
	fccosd.`percentage_rise_or_fall`,
	fccosd.`power_and_fuel`,
	fccosd.`profit_before_tax_or_loss`,
	fccosd.`provision_for_deferred_tax`,
	fccosd.`provision_for_taxes`,
	fccosd.`raw_materials`,
	fccosd.`raw_materials_imported`,
	fccosd.`raw_materials_indigenous`,
	fccosd.`retained_profit`,
	fccosd.`retained_profit_or_net_profit`,
	fccosd.`selling_genl_admn_expenses`,
	fccosd.`sub_total_cost_Sales`,
	fccosd.`sub_total_cost_sales_and_selling`,
	fccosd.`sub_total_expenses`,
	fccosd.`sub_total_of_cost_sales_and_operating_stock`,
	fccosd.`sub_total_deduct_and_cost_of_production`,
	fccosd.`sub_total_of_income`,
	fccosd.`total_cost_sales`,
	fccosd.`total_gross_sales`,
	fccosd.`year`,
	fccosd.`storage_details_id`,
	fccosd.`application_id`,
	fccosd.`created_date`,
	-- fccosd.`modified_date`,
	fccosd.`created_by`,
	-- fccosd.`modified_by`,
	fccosd.`is_active`,
	fccosd.`selling_distribution_exp`,
	fccosd.`general_admin_exp`,
	fccosd.`financial_yearly_statement`,
	fccosd.`other_income_need_to_chek_op`,
	pd.`id` AS proposal_mapping_id
	FROM `loan_application`.`fs_corporate_cma_operating_statement_details` fccosd
	INNER JOIN `loan_application`.`proposal_details` ON pd.application_id = fccosd.application_id
	WHERE proposal_mapping_id IS NULL AND fccosd.financial_yearly_statement='Audited' AND pd.is_active=TRUE

	UPDATE `loan_application`.`fs_corporate_cma_operating_statement_details` apm
INNER JOIN `loan_application`.`proposal_details` pd ON pd.application_id=apm.application_id
SET apm.proposal_mapping_id = pd.id
WHERE (apm.financial_yearly_statement='Projected' OR apm.financial_yearly_statement='Estimated') AND pd.is_active=TRUE;


