/*Table structure for table `fp_ntb_tl_details` */

DROP TABLE IF EXISTS `fp_ntb_tl_details`;

CREATE TABLE `fp_ntb_tl_details` (
  `fp_product_id` bigint(20) unsigned NOT NULL,
  `currency` int(2) DEFAULT NULL,
  `denomination` int(2) DEFAULT NULL,
  `min_tenure` double DEFAULT NULL,
  `max_tenure` double DEFAULT NULL,
  `min_age_individual` int(5) DEFAULT NULL,
  `max_age_individual` int(5) DEFAULT NULL,
  `is_industry_sector_mandatory` bit(1) DEFAULT b'0',
  `is_tenure_display` bit(1) DEFAULT b'0',
  `is_tenure_mandatory` bit(1) DEFAULT b'0',
  `is_age_individual_display` bit(1) DEFAULT b'0',
  `is_industry_sector_display` bit(1) DEFAULT b'0',
  `is_age_individual_mandatory` bit(1) DEFAULT b'0',
  `is_geographical_display` bit(1) DEFAULT b'0',
  `is_geographical_mandatory` bit(1) DEFAULT b'0',
  `min_loan_amount` double DEFAULT NULL,
  `max_loan_amount` double DEFAULT NULL,
  `min_yearly_income_range` double DEFAULT NULL,
  `max_yearly_income_range` double DEFAULT NULL,
  `is_loan_amount_display` bit(1) DEFAULT b'0',
  `is_loan_amount_mandatory` bit(1) DEFAULT b'0',
  `is_yearly_income_display` bit(1) DEFAULT b'0',
  `is_yearly_income_mandatory` bit(1) DEFAULT b'0',
  `min_loan_asset_value` double DEFAULT NULL,
  `max_loan_asset_value` double DEFAULT NULL,
  `is_loan_asset_value_display` bit(1) DEFAULT b'0',
  `is_loan_asset_value_mandatory` bit(1) DEFAULT b'0',
  `min_avg_working_exp` double DEFAULT NULL,
  `max_avg_working_exp` double DEFAULT NULL,
  `is_avg_working_exp_display` bit(1) DEFAULT b'0',
  `is_avg_working_exp_mandatory` bit(1) DEFAULT b'0',
  `min_cibil_score` bigint(20) DEFAULT NULL,
  `max_cibil_score` bigint(20) DEFAULT NULL,
  `is_cibil_score_display` bit(1) DEFAULT b'0',
  `is_cibil_score_mandatory` bit(1) DEFAULT b'0',
  `min_current_foir` double DEFAULT NULL,
  `max_current_foir` double DEFAULT NULL,
  `is_current_foir_display` bit(1) DEFAULT b'0',
  `is_current_foir_mandatory` bit(1) DEFAULT b'0',
  `min_risk_score_model` bigint(20) DEFAULT NULL,
  `max_risk_score_model` bigint(20) DEFAULT NULL,
  `is_risk_score_model_display` bit(1) DEFAULT b'0',
  `is_risk_score_model_mandatory` bit(1) DEFAULT b'0',
  `created_date` datetime DEFAULT NULL,
  `modified_date` datetime DEFAULT NULL,
  `created_by` bigint(20) DEFAULT NULL,
  `modified_by` bigint(20) DEFAULT NULL,
  `is_active` bit(1) DEFAULT NULL,
  PRIMARY KEY (`fp_product_id`),
  CONSTRAINT `fp_ntb_details_ibfk_1` FOREIGN KEY (`fp_product_id`) REFERENCES `fp_product_master` (`fp_product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;