ALTER TABLE `loan_applications`.`fs_ddr_form_details` ADD COLUMN remark_of_company_info VARCHAR(1000), 
ADD COLUMN remark_of_bank_arrangement VARCHAR(1000),
ADD COLUMN remark_of_fin_summary VARCHAR(1000),
ADD COLUMN remark_of_total_sales VARCHAR(1000),
ADD COLUMN remark_of_total_debt VARCHAR(1000),
ADD COLUMN remark_of_latest_debtors_list VARCHAR(1000),
ADD COLUMN remark_of_latest_cred_list VARCHAR(1000),
ADD COLUMN remark_of_business_details VARCHAR(1000),
ADD COLUMN remark_of_personal_details VARCHAR(1000),
ADD COLUMN remark_of_name_of_auth_signatory VARCHAR(1000),
ADD COLUMN remark_of_other_detail VARCHAR(1000),
ADD COLUMN remark_of_detail_of_credcard VARCHAR(1000),
ADD COLUMN remark_of_past_pre_relationship VARCHAR(1000),
ADD COLUMN remark_of_any_other_bank_loan VARCHAR(1000),
ADD COLUMN remark_of_doc_checklist VARCHAR(1000);