ALTER TABLE `loan_application`.`fs_retail_applicant_details` ADD COLUMN `loan_amount_required` DOUBLE DEFAULT NULL;
ALTER TABLE `loan_application`.`fs_retail_applicant_details` ADD COLUMN `loan_purpose` INT DEFAULT NULL;
ALTER TABLE `loan_application`.`fs_retail_applicant_details` ADD COLUMN `loan_purpose_other` VARCHAR(150) DEFAULT NULL;
ALTER TABLE `loan_application`.`fs_retail_applicant_details` ADD COLUMN `tenure_required` INT DEFAULT NULL;
ALTER TABLE `loan_application`.`fs_retail_applicant_details` ADD COLUMN `repayment` INT DEFAULT NULL;
ALTER TABLE `loan_application`.`fs_retail_applicant_details` ADD COLUMN `education_qualification` INT DEFAULT NULL;
ALTER TABLE `loan_application`.`fs_retail_applicant_details` ADD COLUMN `employment_type` INT DEFAULT NULL;
ALTER TABLE `loan_application`.`fs_retail_applicant_details` ADD COLUMN `name_of_employer` VARCHAR(150) DEFAULT NULL;
ALTER TABLE `loan_application`.`fs_retail_applicant_details` ADD COLUMN `key_verical_funding` BIGINT(20) DEFAULT NULL;
ALTER TABLE `loan_application`.`fs_retail_applicant_details` ADD COLUMN `key_vertical_sector` BIGINT(20) DEFAULT NULL;
ALTER TABLE `loan_application`.`fs_retail_applicant_details` ADD COLUMN `key_vertical_subsector` BIGINT(20) DEFAULT NULL;
ALTER TABLE `loan_application`.`fs_retail_applicant_details` ADD COLUMN `email` VARCHAR(50) DEFAULT NULL;
ALTER TABLE `loan_application`.`fs_retail_applicant_details` ADD COLUMN `mobile` VARCHAR(10) DEFAULT NULL;
ALTER TABLE `loan_application`.`fs_retail_applicant_details` ADD COLUMN `permanent_district_mapping_id` BIGINT(20) DEFAULT NULL;
ALTER TABLE `loan_application`.`fs_retail_applicant_details` ADD COLUMN `address_district_mapping_id` BIGINT(20) DEFAULT NULL;
ALTER TABLE `loan_application`.`fs_retail_applicant_details` ADD COLUMN `employment_with` INT DEFAULT NULL;
ALTER TABLE `loan_application`.`fs_retail_applicant_details` ADD COLUMN `central_gov_id` INT DEFAULT NULL;
ALTER TABLE `loan_application`.`fs_retail_applicant_details` ADD COLUMN `state_gov_id` INT DEFAULT NULL;
ALTER TABLE `loan_application`.`fs_retail_applicant_details` ADD COLUMN `psu_id` INT DEFAULT NULL;
ALTER TABLE `loan_application`.`fs_retail_applicant_details` ADD COLUMN `corporate_id` INT DEFAULT NULL;
ALTER TABLE `loan_application`.`fs_retail_applicant_details` ADD COLUMN `edu_inst_id` INT DEFAULT NULL;
ALTER TABLE `loan_application`.`fs_retail_applicant_details`
ADD COLUMN `office_district_mapping_id` BIGINT(20) NULL;
